{
  "name": "BPR Finance Detailed EU Region",
  "compatibilityLevel": 1567,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true,
      "fastCombine": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DateTableTemplate_25777040-2091-4b14-8dcb-c46e013700a4",
        "isPrivate": true,
        "lineageTag": "0f320adf-19c0-4ad3-8f9f-509320a65f4e",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "fb99e48e-c463-4dc7-a7cc-418d26894e34",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "63a219fe-8db7-4b9c-ad69-fb7e33f42c03",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "5972d2d0-77bb-4850-935e-40c8d6489479",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "8a38b6ee-3805-4806-8ef6-00af75b3c8ee",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "lineageTag": "b63ce662-53fd-455a-b56f-404321daa6e7",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "6989f6b8-bfb5-45cc-af82-af2e5bd6b73b",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "09afb726-9e56-42d6-b674-ca6213e4a783",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DateTableTemplate_25777040-2091-4b14-8dcb-c46e013700a4-67e50e35-4e6d-4d27-9072-0d264d309251",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "47bc3b2e-17c3-4bd4-a3c0-654973169599",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "0c2ac5e3-7be8-406e-bed2-e725a93b6201"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "c9524bce-0aeb-4582-8491-041396ccfbd6"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "f0f3285a-89e4-4e64-b00d-22aa0e73ad6e"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "813c4ab0-9be2-4fff-8370-52fcdc218dd9"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ]
      },
      {
        "name": "Customer Measures",
        "lineageTag": "fd5cbb4d-5887-492a-82f6-0a5dabc4b391",
        "partitions": [
          {
            "name": "Customer Measures-f78f6070-8fdd-4335-a3a5-f47e2ed019cc",
            "mode": "import",
            "queryGroup": "Customer",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "B2B/B2C Title",
            "expression": "SELECTEDVALUE ( FCT_COMMERCIAL_SUMMARY[B2C Flag] )",
            "displayFolder": "Others",
            "lineageTag": "e66ff6e7-cafd-4c7f-80ab-42ef8c74af7d",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "Avg Trad Portfolio",
            "expression": [
              "IF (",
              "    SELECTEDVALUE ( 'Period Filter'[Period] ) = \"YTD\",",
              "    \"(Avg Trading Portfolio YTD)\",",
              "    IF (",
              "        SELECTEDVALUE ( 'Period Filter'[Period] ) = \"LM\",",
              "        \"(Avg Trading Portfolio LM)\",",
              "        BLANK ()",
              "    )",
              ")"
            ],
            "displayFolder": "Others",
            "lineageTag": "efaf08ef-fc2f-4a58-94c8-f364f1c6e075"
          },
          {
            "name": "Active Customers YTD C_New",
            "expression": [
              "VAR ActiveCustomer =",
              "    CALCULATE (",
              "        DISTINCTCOUNT ( VW_DIM_CUSTOMER[Customer GSFA ID] ),",
              "        FCT_COMMERCIAL_SUMMARY[Base Revenue LCY] > 0,",
              "        FILTER (",
              "            DIM_PERIOD,",
              "            YEAR ( DIM_PERIOD[Billing Period Date] ) = [YTD]",
              "        )",
              "    )",
              "RETURN",
              "    ActiveCustomer"
            ],
            "formatString": "0",
            "displayFolder": "Avg Active Customer",
            "lineageTag": "8ea517f3-61d2-4e9c-a371-14b820c9b86a",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Avg Spend YTD C_New",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "    \"Total Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Total Revenue EUR YTD],",
              "                    [Active Customers YTD C_New]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Total Revenue USD YTD],",
              "                    [Active Customers YTD C_New]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Total Revenue LCY YTD],",
              "                    [Active Customers YTD C_New]",
              "                )",
              "        ),",
              "    \"Base Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Base Revenue EUR YTD],",
              "                    [Active Customers YTD C_New]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Base Revenue USD YTD],",
              "                    [Active Customers YTD C_New]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Base Revenue LCY YTD],",
              "                    [Active Customers YTD C_New]",
              "                )",
              "        ),",
              "    \"Shipment\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Base Revenue EUR YTD],",
              "                    [Active Customers YTD C_New]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Base Revenue USD YTD],",
              "                    [Active Customers YTD C_New]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Base Revenue LCY YTD],",
              "                    [Active Customers YTD C_New]",
              "                )",
              "        ),",
              "    \"Weight\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Base Revenue EUR YTD],",
              "                    [Active Customers YTD C_New]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Base Revenue USD YTD],",
              "                    [Active Customers YTD C_New]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Base Revenue LCY YTD],",
              "                    [Active Customers YTD C_New]",
              "                )",
              "        )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Avg Spend",
            "lineageTag": "c3b8fd57-e381-408a-8c3f-162bd9d6b6f8",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Avg Spend L13 C_New",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "    \"Total Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Total Revenue EUR L13],",
              "                    [Active Customer L13 C_New]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Total Revenue USD L13],",
              "                    [Active Customer L13 C_New]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Total Revenue LCY L13],",
              "                    [Active Customer L13 C_New]",
              "                )",
              "        ),",
              "    \"Base Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Base Revenue EUR L13],",
              "                    [Active Customer L13 C_New]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Base Revenue USD L13],",
              "                    [Active Customer L13 C_New]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Base Revenue LCY L13],",
              "                    [Active Customer L13 C_New]",
              "                )",
              "        ),",
              "    \"Shipment\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Base Revenue EUR L13],",
              "                    [Active Customer L13 C_New]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Base Revenue USD L13],",
              "                    [Active Customer L13 C_New]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Base Revenue LCY L13],",
              "                    [Active Customer L13 C_New]",
              "                )",
              "        ),",
              "    \"Weight\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Base Revenue EUR L13],",
              "                    [Active Customer L13 C_New]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Base Revenue USD L13],",
              "                    [Active Customer L13 C_New]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Base Revenue LCY L13],",
              "                    [Active Customer L13 C_New]",
              "                )",
              "        )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "L13 Month",
            "lineageTag": "a402bb2d-a65a-4243-825e-7e103c3a6891",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Trading Portfolio L13 C_New",
            "expression": [
              "DIVIDE (",
              "    [Active Customer L13 C_New],",
              "    [Totalcustomers C_New]",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "L13 Month",
            "lineageTag": "57c3e6a1-03f2-4a7c-b0c1-b94fc67eaa79",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Customer Trend line YTD C_New",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Customer Filters'[Cust Filters] ),",
              "    \"Active Customers\", [Active Customers YTD C_New],",
              "    \"Average Spends\", [Avg Spend YTD C_New],",
              "    \"% of TradingPortfolio\",",
              "        [Trading Portfolio YTD C_New] * 100",
              ")"
            ],
            "displayFolder": "Trendline",
            "lineageTag": "539fccea-436c-4c90-aa50-bc0f4b58c9b4",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Customer Trend line LY C_New",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Customer Filters'[Cust Filters] ),",
              "    \"Active Customers\", [Active Customers LY C_New],",
              "    \"Average Spends\", [Avg Spend LY C_New],",
              "    \"% of TradingPortfolio\",",
              "        [Trading Portfolio LY C_New] * 100",
              ")"
            ],
            "displayFolder": "Trendline",
            "lineageTag": "db7a0cd8-3331-47ff-b260-bf0001381f88",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Customer Trend Line %",
            "expression": "( [Customer Trend line YTD C_New] - [Customer Trend line LY C_New] ) / [Customer Trend line LY C_New]",
            "formatString": "0%;-0%;0%",
            "displayFolder": "Trendline",
            "lineageTag": "0eed0d70-b3d4-4f72-aef4-b259fd9a76d2",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Customer Trend Line Growth",
            "expression": "[Customer Trend line YTD C_New] - [Customer Trend line LY C_New]",
            "formatString": "#,0.0",
            "displayFolder": "Trendline",
            "lineageTag": "49412804-db20-42ac-9628-f1c5ebe54235",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Avg Spend Label",
            "expression": [
              "IF (",
              "    SELECTEDVALUE ( 'Period Filter'[Period] ) = \"YTD\",",
              "    \"(Avg spend YTD)\",",
              "    IF (",
              "        SELECTEDVALUE ( 'Period Filter'[Period] ) = \"LM\",",
              "        \"(Avg spend LM)\",",
              "        BLANK ()",
              "    )",
              ")"
            ],
            "displayFolder": "Others",
            "lineageTag": "2622638f-34e1-40b7-ad67-56653ee5d03e"
          },
          {
            "name": "TotalCustomers LM C_New",
            "expression": [
              "VAR _Result =",
              "    CALCULATE (",
              "        DISTINCTCOUNT ( VW_DIM_CUSTOMER[Customer GSFA ID] ),",
              "        ALL ( DIM_PERIOD )",
              "    )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( _Result ),",
              "        0,",
              "        _Result",
              "    )"
            ],
            "formatString": "0",
            "displayFolder": "Others",
            "lineageTag": "fcb6659e-3d0b-484a-8606-cc3342b29a72"
          },
          {
            "name": "TotalCustomers AVG YTD C_New",
            "expression": [
              "VAR TotalCustomer =",
              "    AVERAGEX (",
              "        VALUES ( DIM_PERIOD[Billing Month Name] ),",
              "        [TotalCustomers YTD]",
              "    )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( TotalCustomer ),",
              "        0,",
              "        TotalCustomer",
              "    )"
            ],
            "displayFolder": "Others",
            "lineageTag": "4e8d87f8-bdb7-4d39-8f88-20c651df66d3",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Avg Total Customer C_New",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Period Filter'[Period] ),",
              "    \"YTD\", [TotalCustomers AVG YTD C_New],",
              "    \"LM\", [TotalCustomers LM C_New]",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Others",
            "lineageTag": "2d41cfa9-bbf2-4576-967e-31e5465f9774",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Active Customer L13 C_New",
            "expression": [
              "CALCULATE (",
              "    DISTINCTCOUNT ( VW_DIM_CUSTOMER[Customer GSFA ID] ),",
              "    FCT_COMMERCIAL_SUMMARY[Base Revenue LCY] > 0,",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date].[Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 14",
              "            )",
              "            && DIM_PERIOD[Billing Period Date].[Date]",
              "                <= EOMONTH (",
              "                    [Today],",
              "                    -1",
              "                )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "L13 Month",
            "lineageTag": "b63d148b-baf1-4493-a261-99854a12a724"
          },
          {
            "name": "Totalcustomers C_New",
            "expression": [
              "CALCULATE (",
              "    DISTINCTCOUNT ( VW_DIM_CUSTOMER[Customer GSFA ID] ),",
              "    ALL ( DIM_PERIOD )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Others",
            "lineageTag": "d100dd2d-494f-480a-b694-95b16a6fe7fb"
          },
          {
            "name": "Active Customers LY C_New",
            "expression": [
              "VAR ActiveCustomer =",
              "    CALCULATE (",
              "        DISTINCTCOUNT ( VW_DIM_CUSTOMER[Customer GSFA ID] ),",
              "        FCT_COMMERCIAL_SUMMARY[Base Revenue LCY] > 0,",
              "        FILTER (",
              "            DIM_PERIOD,",
              "            YEAR ( DIM_PERIOD[Billing Period Date] ) = [LY]",
              "        )",
              "    )",
              "RETURN",
              "    ActiveCustomer"
            ],
            "formatString": "0",
            "displayFolder": "Avg Active Customer",
            "lineageTag": "e885dc36-64e7-44d3-a357-294a999fb727"
          },
          {
            "name": "Avg Spend LY C_New",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "    \"Total Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Total Revenue EUR LY],",
              "                    [Active Customers LY C_New]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Total Revenue USD LY],",
              "                    [Active Customers LY C_New]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Total Revenue LCY LY],",
              "                    [Active Customers LY C_New]",
              "                )",
              "        ),",
              "    \"Base Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Base Revenue EUR LY],",
              "                    [Active Customers LY C_New]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Base Revenue USD LY],",
              "                    [Active Customers LY C_New]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Base Revenue LCY LY],",
              "                    [Active Customers LY C_New]",
              "                )",
              "        )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Avg Spend",
            "lineageTag": "86a6344b-d220-49d9-a59a-cec0f32a24bb",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Trading Portfolio YTD C_New",
            "expression": [
              "DIVIDE (",
              "    [Active Customers YTD C_New],",
              "    [Totalcustomers C_New]",
              ")"
            ],
            "displayFolder": "Trading Portfolio",
            "lineageTag": "6bccf803-31ee-4a3a-add3-5a0e8ba206dd",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Trading Portfolio LY C_New",
            "expression": [
              "DIVIDE (",
              "    [Active Customers LY C_New],",
              "    [Totalcustomers C_New]",
              ")"
            ],
            "displayFolder": "Trading Portfolio",
            "lineageTag": "6331f074-c4fc-48e2-92bc-aec529b48c5d",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Active Customers LM C_New",
            "expression": [
              "VAR ActiveCustomer =",
              "    CALCULATE (",
              "        DISTINCTCOUNT ( VW_DIM_CUSTOMER[Customer GSFA ID] ),",
              "        FCT_COMMERCIAL_SUMMARY[Base Revenue LCY] > 0,",
              "        FILTER (",
              "            DIM_PERIOD,",
              "            YEAR ( DIM_PERIOD[Billing Period Date] ) = [YTD]",
              "        ),",
              "        FILTER (",
              "            DIM_PERIOD,",
              "            MONTH ( DIM_PERIOD[Billing Period Date] ) = [LM]",
              "        )",
              "    )",
              "RETURN",
              "    ActiveCustomer"
            ],
            "formatString": "0",
            "displayFolder": "Avg Active Customer",
            "lineageTag": "510f7223-21a9-412b-8e75-78f42bc77329"
          },
          {
            "name": "Active Customers LYLM C_New",
            "expression": [
              "VAR ActiveCustomer =",
              "    CALCULATE (",
              "        DISTINCTCOUNT ( VW_DIM_CUSTOMER[Customer GSFA ID] ),",
              "        FCT_COMMERCIAL_SUMMARY[Base Revenue LCY] > 0,",
              "        FILTER (",
              "            DIM_PERIOD,",
              "            YEAR ( DIM_PERIOD[Billing Period Date] ) = [LY]",
              "        ),",
              "        FILTER (",
              "            DIM_PERIOD,",
              "            MONTH ( DIM_PERIOD[Billing Period Date] ) = [LM]",
              "        )",
              "    )",
              "RETURN",
              "    ActiveCustomer"
            ],
            "formatString": "0",
            "displayFolder": "Avg Active Customer",
            "lineageTag": "096aff68-7f5d-416b-895c-882096a121d9"
          },
          {
            "name": "Active Customers LYTD C_New",
            "expression": [
              "VAR ActiveCustomer =",
              "    CALCULATE (",
              "        DISTINCTCOUNT ( VW_DIM_CUSTOMER[Customer GSFA ID] ),",
              "        FCT_COMMERCIAL_SUMMARY[Base Revenue LCY] > 0,",
              "        FILTER (",
              "            DIM_PERIOD,",
              "            DIM_PERIOD[Billing Year] = [LY]",
              "        ),",
              "        FILTER (",
              "            DIM_PERIOD,",
              "            MONTH ( DIM_PERIOD[Billing Period Date] ) <= [LM]",
              "        )",
              "    )",
              "RETURN",
              "    ActiveCustomer"
            ],
            "formatString": "0",
            "displayFolder": "Avg Active Customer",
            "lineageTag": "2c6f6103-ffa5-4955-98ce-470376c44101"
          },
          {
            "name": "Active Customers YTD AVG C_New",
            "expression": [
              "VAR _Result =",
              "    AVERAGEX (",
              "        VALUES ( DIM_PERIOD[Billing Month Name] ),",
              "        [Active Customers YTD C_New]",
              "    )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( _Result ),",
              "        0,",
              "        _Result",
              "    )"
            ],
            "formatString": "#,0",
            "displayFolder": "Avg Active Customer",
            "lineageTag": "17c0321b-6ee0-4e92-883a-184ed2a845cd",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Active Customers LYTD AVG C_New",
            "expression": [
              "VAR _Result =",
              "    AVERAGEX (",
              "        VALUES ( DIM_PERIOD[Billing Month Name] ),",
              "        [Active Customers LYTD C_New]",
              "    )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( _Result ),",
              "        0,",
              "        _Result",
              "    )"
            ],
            "displayFolder": "Avg Active Customer",
            "lineageTag": "d3753d58-ff10-4c7d-adf1-ab3d7e491449",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Active Customers YTD/LM C_New",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Period Filter'[Period] ),",
              "    \"YTD\", [Active Customers YTD AVG C_New],",
              "    \"LM\", [Active Customers LM C_New]",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Avg Active Customer",
            "lineageTag": "acf5687b-66e8-48e7-a3ab-3d7c9ebcb23b",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Active Customers LYTD/LYLM C_New",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Period Filter'[Period] ),",
              "    \"YTD\", [Active Customers LYTD AVG C_New],",
              "    \"LM\", [Active Customers LYLM C_New]",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Avg Active Customer",
            "lineageTag": "47078073-c4ac-4a23-876c-7d416d4de94e",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Active Customers YTD/LM/LYTD/LYLM YOY% C_New",
            "expression": [
              "VAR _Growth = [Active Customers YTD/LM C_New] - [Active Customers LYTD/LYLM C_New]",
              "VAR _Result =",
              "    DIVIDE (",
              "        _Growth,",
              "        [Active Customers LYTD/LYLM C_New]",
              "    )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( _Result ),",
              "        0,",
              "        _Result",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "Avg Active Customer",
            "lineageTag": "b53d0725-6a08-4f12-88ba-f39ce45e418c",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Trading Portfolio LM C_New",
            "expression": [
              "DIVIDE (",
              "    [Active Customers LM C_New],",
              "    [Totalcustomers C_New]",
              ")"
            ],
            "displayFolder": "Trading Portfolio",
            "lineageTag": "607e847b-5c7b-41ab-a9c2-f5452fa3bb7d",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Trading Portfolio LYLM C_New",
            "expression": [
              "DIVIDE (",
              "    [Active Customers LYLM C_New],",
              "    [Totalcustomers C_New]",
              ")"
            ],
            "displayFolder": "Trading Portfolio",
            "lineageTag": "ffdc07e9-b352-46b8-a83f-f7700b5b710e",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Trading Portfolio YTD/LM C_New",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Period Filter'[Period] ),",
              "    \"YTD\", [Trading Portfolio YTD AVG C_New],",
              "    \"LM\", [Trading Portfolio LM C_New]",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "Trading Portfolio",
            "lineageTag": "b8ed6e5b-fb18-4e9c-a72e-baf4207e70d9",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Trading Portfolio YTD AVG C_New",
            "expression": [
              "VAR _Result =",
              "    AVERAGEX (",
              "        VALUES ( DIM_PERIOD[Billing Month Name] ),",
              "        [Trading Portfolio YTD C_New]",
              "    )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( _Result ),",
              "        0,",
              "        _Result",
              "    )"
            ],
            "displayFolder": "Trading Portfolio",
            "lineageTag": "c8461aca-9f27-48a2-b499-2fe328c6e69a",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Trading Portfolio LYTD AVG C_New",
            "expression": [
              "VAR _Result =",
              "    AVERAGEX (",
              "        VALUES ( DIM_PERIOD[Billing Month Name] ),",
              "        [Trading Portfolio lYTD C_New]",
              "    )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( _Result ),",
              "        0,",
              "        _Result",
              "    )"
            ],
            "displayFolder": "Trading Portfolio",
            "lineageTag": "90602d27-2da2-4f65-b21e-10570b576625"
          },
          {
            "name": "Trading Portfolio LYTD C_New",
            "expression": [
              "DIVIDE (",
              "    [Active Customers LYTD C_New],",
              "    [Totalcustomers C_New]",
              ")"
            ],
            "displayFolder": "Trading Portfolio",
            "lineageTag": "e342a744-17c0-4345-8864-e9c155607db3",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Trading Portfolio LYTD/LYLM C_New",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Period Filter'[Period] ),",
              "    \"YTD\", [Trading Portfolio LYTD AVG C_New],",
              "    \"LM\", [Trading Portfolio LYLM C_New]",
              ")"
            ],
            "displayFolder": "Trading Portfolio",
            "lineageTag": "2adfdb0b-8ca8-48fe-8455-97d2c8f52096",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Trading Portfolio YTD/LM/LYTD/LYLM YOY% C_New",
            "expression": [
              "VAR _Growth = [Trading Portfolio YTD/LM C_New] - [Trading Portfolio LYTD/LYLM C_New]",
              "VAR _Result =",
              "    DIVIDE (",
              "        _Growth,",
              "        [Trading Portfolio LYTD/LYLM C_New]",
              "    )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( _Result ),",
              "        0,",
              "        _Result",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "Trading Portfolio",
            "lineageTag": "958c1b49-ee86-424f-9115-fbb2483f4456",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Avg Spend LYTD C_New",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "    \"Total Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Total Revenue EUR LYTD],",
              "                    [Active Customers LYTD C_New]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Total Revenue USD LYTD],",
              "                    [Active Customers LYTD C_New]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Total Revenue LCY LYTD],",
              "                    [Active Customers LYTD C_New]",
              "                )",
              "        ),",
              "    \"Base Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Base Revenue EUR LYTD],",
              "                    [Active Customers LYTD C_New]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Base Revenue USD LYTD],",
              "                    [Active Customers LYTD C_New]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Base Revenue LCY LYTD],",
              "                    [Active Customers LYTD C_New]",
              "                )",
              "        ),",
              "    \"Shipment\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Base Revenue EUR LYTD],",
              "                    [Active Customers LYTD C_New]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Base Revenue USD LYTD],",
              "                    [Active Customers LYTD C_New]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Base Revenue LCY LYTD],",
              "                    [Active Customers LYTD C_New]",
              "                )",
              "        ),",
              "    \"Weight\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Base Revenue EUR LYTD],",
              "                    [Active Customers LYTD C_New]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Base Revenue USD LYTD],",
              "                    [Active Customers LYTD C_New]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Base Revenue LCY LYTD],",
              "                    [Active Customers LYTD C_New]",
              "                )",
              "        )",
              ")"
            ],
            "displayFolder": "Avg Spend",
            "lineageTag": "c4974125-1ced-43a1-8222-e135c0998a1d",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Avg Spend LM C_New",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "    \"Total Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Total Revenue EUR LM],",
              "                    [Active Customers LM C_New]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Total Revenue USD LM],",
              "                    [Active Customers LM C_New]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Total Revenue LCY LM],",
              "                    [Active Customers LM C_New]",
              "                )",
              "        ),",
              "    \"Base Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Base Revenue EUR LM],",
              "                    [Active Customers LM C_New]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Base Revenue USD LM],",
              "                    [Active Customers LM C_New]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Base Revenue LCY LM],",
              "                    [Active Customers LM C_New]",
              "                )",
              "        ),",
              "    \"Shipment\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Base Revenue EUR LM],",
              "                    [Active Customers LM C_New]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Base Revenue USD LM],",
              "                    [Active Customers LM C_New]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Base Revenue LCY LM],",
              "                    [Active Customers LM C_New]",
              "                )",
              "        ),",
              "    \"Weight\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Base Revenue EUR LM],",
              "                    [Active Customers LM C_New]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Base Revenue USD LM],",
              "                    [Active Customers LM C_New]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Base Revenue LCY LM],",
              "                    [Active Customers LM C_New]",
              "                )",
              "        )",
              ")"
            ],
            "displayFolder": "Avg Spend",
            "lineageTag": "2c72530a-2909-4f2d-b7da-2085586785a1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Avg Spend LYLM C_New",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "    \"Total Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Total Revenue EUR LYLM],",
              "                    [Active Customers LYLM C_New]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Total Revenue USD LYLM],",
              "                    [Active Customers LYLM C_New]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Total Revenue LCY LYLM],",
              "                    [Active Customers LYLM C_New]",
              "                )",
              "        ),",
              "    \"Base Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Base Revenue EUR LYLM],",
              "                    [Active Customers LYLM C_New]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Base Revenue USD LYLM],",
              "                    [Active Customers LYLM C_New]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Base Revenue LCY LYLM],",
              "                    [Active Customers LYLM C_New]",
              "                )",
              "        ),",
              "    \"Shipment\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Base Revenue EUR LYLM],",
              "                    [Active Customers LYLM C_New]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Base Revenue USD LYLM],",
              "                    [Active Customers LYLM C_New]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Base Revenue LCY LYLM],",
              "                    [Active Customers LYLM C_New]",
              "                )",
              "        ),",
              "    \"Weight\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Base Revenue EUR LYLM],",
              "                    [Active Customers LYLM C_New]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Base Revenue USD LYLM],",
              "                    [Active Customers LYLM C_New]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Base Revenue LCY LYLM],",
              "                    [Active Customers LYLM C_New]",
              "                )",
              "        )",
              ")"
            ],
            "displayFolder": "Avg Spend",
            "lineageTag": "3dc37b81-5bf9-4016-b999-33eefdff12c4",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Avg Spend YTD AVG C_New",
            "expression": [
              "VAR _Result =",
              "    AVERAGEX (",
              "        VALUES ( DIM_PERIOD[Billing Month Name] ),",
              "        [Avg Spend YTD C_New]",
              "    )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( _Result ),",
              "        0,",
              "        _Result",
              "    )"
            ],
            "displayFolder": "Avg Spend",
            "lineageTag": "b1380a3f-27b9-49c5-895f-3d0b2c96940c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Avg Spend LYTD AVG C_New",
            "expression": [
              "VAR _Result =",
              "    AVERAGEX (",
              "        VALUES ( DIM_PERIOD[Billing Month Name] ),",
              "        [Avg Spend LYTD C_New]",
              "    )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( _Result ),",
              "        0,",
              "        _Result",
              "    )"
            ],
            "displayFolder": "Avg Spend",
            "lineageTag": "3557773a-cec1-4cc8-841e-8af13eee3d13",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Avg Spend YTD/LM",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Period Filter'[Period] ),",
              "    \"YTD\", [Avg Spend YTD AVG C_New],",
              "    \"LM\", [Avg Spend LM C_New]",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Avg Spend",
            "lineageTag": "0a0d4177-91af-4fd4-bd74-6864a508deac",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Avg Spend LYTD/LYLM",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Period Filter'[Period] ),",
              "    \"YTD\", [Avg Spend LYTD AVG C_New],",
              "    \"LM\", [Avg Spend LYLM C_New]",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Avg Spend",
            "lineageTag": "654420ae-372d-4aa6-acfc-48f3b1b90bb2",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Avg Spend YTD/LM/LYTD/LYLM YOY%",
            "expression": [
              "VAR _Result =",
              "    SWITCH (",
              "        SELECTEDVALUE ( 'Period Filter'[Period] ),",
              "        \"YTD\",",
              "            DIVIDE (",
              "                ( [Avg Spend YTD AVG C_New] - [Avg Spend LYTD AVG C_New] ),",
              "                [Avg Spend LYTD AVG C_New]",
              "            ),",
              "        \"LM\",",
              "            DIVIDE (",
              "                ( [Avg Spend LM C_New] - [Avg Spend LYLM C_New] ),",
              "                [Avg Spend LYLM C_New]",
              "            )",
              "    )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( _Result ),",
              "        0,",
              "        _Result",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "Avg Spend",
            "lineageTag": "7e2c9470-ffb0-4b5e-8e7f-97eb23d7f2b0",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Avg Spend YTD/LM/LYTD/LYLM Growth C_New",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Period Filter'[Period] ),",
              "    \"YTD\",",
              "        [Avg Spend YTD AVG C_New] - [Avg Spend LYTD AVG C_New],",
              "    \"LM\",",
              "        [Avg Spend LM C_New] - [Avg Spend LYLM C_New]",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Avg Spend",
            "lineageTag": "1f761aa4-8968-43e1-a220-89cc781f4cb1",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Inactive Customers C_New",
            "expression": [
              "IF (",
              "    [Trading Portfolio YTD/LM C_New] = 0,",
              "    0,",
              "    1 - [Trading Portfolio YTD/LM C_New]",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "Others",
            "lineageTag": "f7e48c72-9826-46f6-8a10-8d7ce33597d2",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "TotalCustomers YTD",
            "expression": [
              "VAR CustomerCount =",
              "    CALCULATE (",
              "        DISTINCTCOUNT ( VW_DIM_CUSTOMER[Customer GSFA ID] ),",
              "        ALL ( DIM_PERIOD )",
              "    )",
              "RETURN",
              "    CustomerCount"
            ],
            "formatString": "0",
            "displayFolder": "Others",
            "lineageTag": "0e7ba6c5-bbc8-49f9-ab3e-5e3477d489ea"
          },
          {
            "name": "Active Customers YTD/LM/LYTD/LYLM Growth C_New",
            "expression": "[Active Customers YTD/LM C_New] - [Active Customers LYTD/LYLM C_New]",
            "formatString": "#,0",
            "displayFolder": "Avg Active Customer",
            "lineageTag": "1e729f3e-996e-4488-91c0-50539254e274",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Avg Active Cust Lable",
            "expression": [
              "IF (",
              "    SELECTEDVALUE ( 'Period Filter'[Period] ) = \"YTD\",",
              "    \"(Avg Active Customers YTD)\",",
              "    IF (",
              "        SELECTEDVALUE ( 'Period Filter'[Period] ) = \"LM\",",
              "        \"(Avg Active Customers LM)\",",
              "        BLANK ()",
              "    )",
              ")"
            ],
            "displayFolder": "Others",
            "lineageTag": "f941feba-814f-4889-b60c-b1dda1dc6b3e"
          },
          {
            "name": "Avg Spend YTD Avg Growth C_New",
            "expression": "[Avg Spend YTD AVG C_New] - [Avg Spend LYTD AVG C_New]",
            "displayFolder": "Avg Spend",
            "lineageTag": "18708c10-376f-4c75-874d-c0d2c81b874b",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Avg Spend LM Growth C_New",
            "expression": "[Avg Spend LM C_New] - [Avg Spend LYLM C_New]",
            "displayFolder": "Avg Spend",
            "lineageTag": "c36c47a3-4285-44e0-8475-81c5ddc228af",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Metrics",
        "lineageTag": "3eb89e14-7a95-40f8-9069-5bedefd5f78c",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Value1",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value1]",
            "formatString": "0",
            "lineageTag": "80ef11cf-3ed8-4255-a028-83711c001086",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Value2",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value2]",
            "lineageTag": "8ca3ba44-c6f3-4bbf-a7cb-37a69cbff59b",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Value3",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value3]",
            "lineageTag": "4435c178-fcf0-4c9d-81a8-6a8013d92f6c",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Metrics-d8a2e249-47d9-44a9-b051-6854f8d82b0d",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "{",
                "    (1,\"Customers\",\"Text\"),",
                "    (2,\"Revenue\",\"Currency\"),",
                "    (3,\"Shipments\",\"Number\"),",
                "    (4,\"Weight\",\"Number\")",
                "    }"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "481c75410ba641c88837426a2adab5f5"
          }
        ]
      },
      {
        "name": "RevType",
        "lineageTag": "f5bdc09b-e508-4ffe-b258-a4e00c2c50a0",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Value",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value]",
            "lineageTag": "07aae52e-208c-4b36-b7f7-dd549e405935",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "RevType-555ec19f-d242-4fd2-be98-e172faa99aff",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "{",
                "    (\"Total Revenue\"),",
                "    (\"Base Revenue\")",
                "    }"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "b0a491520dcc43b395b1f97619c15797"
          }
        ]
      },
      {
        "name": "Loyalty Measures",
        "lineageTag": "5f56aea3-6046-4229-b2ab-8dd2f3308b65",
        "columns": [
          {
            "name": "Column1",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Column1",
            "lineageTag": "c9bf7d8c-1992-4412-a15a-a2a1aec6e883",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Loyalty Measures-79a13e92-5093-4388-871e-7044a504d51e",
            "mode": "import",
            "queryGroup": "Loyalty",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Customers YTD",
            "expression": [
              "VAR Customers =",
              "    CALCULATE (",
              "        DISTINCTCOUNT ( VW_DIM_CUSTOMER[Customer GSFA ID] ),",
              "        FILTER (",
              "            DIM_PERIOD,",
              "            YEAR ( DIM_PERIOD[Billing Period Date] ) = [YTD]",
              "        )",
              "    )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( Customers ),",
              "        0,",
              "        Customers",
              "    )"
            ],
            "formatString": "0",
            "displayFolder": "YTD",
            "lineageTag": "9101432e-fc05-4b2f-869a-aaa4a4f08f3d",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "Total/Base Revenue YTD",
            "expression": [
              "VAR _Result =",
              "    SWITCH (",
              "        SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "        \"Total Revenue\",",
              "            SWITCH (",
              "                SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                \"BER - Euro\", [Total Revenue EUR YTD],",
              "                \"BER - USD\", [Total Revenue USD YTD],",
              "                \"Local Currency\", [Total Revenue LCY YTD]",
              "            ),",
              "        \"Base Revenue\",",
              "            SWITCH (",
              "                SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                \"BER - Euro\", [Base Revenue EUR YTD],",
              "                \"BER - USD\", [Base Revenue USD YTD],",
              "                \"Local Currency\", [Base Revenue LCY YTD]",
              "            ),",
              "        \"Shipment\",",
              "            SWITCH (",
              "                SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                \"BER - Euro\", [Base Revenue EUR YTD],",
              "                \"BER - USD\", [Base Revenue USD YTD],",
              "                \"Local Currency\", [Base Revenue LCY YTD]",
              "            ),",
              "        \"Weight\",",
              "            SWITCH (",
              "                SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                \"BER - Euro\", [Base Revenue EUR YTD],",
              "                \"BER - USD\", [Base Revenue USD YTD],",
              "                \"Local Currency\", [Base Revenue LCY YTD]",
              "            ),",
              "        \"Customers\",",
              "            SWITCH (",
              "                SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                \"BER - Euro\", [Base Revenue EUR YTD],",
              "                \"BER - USD\", [Base Revenue USD YTD],",
              "                \"Local Currency\", [Base Revenue LCY YTD]",
              "            )",
              "    )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( _Result ),",
              "        0,",
              "        _Result",
              "    )"
            ],
            "formatString": "#,0.0",
            "displayFolder": "YTD",
            "lineageTag": "05a61833-a94c-4150-b307-819b7a36830e",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "Shipment YTD",
            "expression": [
              "VAR Shipment =",
              "    CALCULATE (",
              "        SUM ( FCT_COMMERCIAL_SUMMARY[Number of Shipments] ),",
              "        FILTER (",
              "            DIM_PERIOD,",
              "            YEAR ( DIM_PERIOD[Billing Period Date] ) = [YTD]",
              "        )",
              "    )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( Shipment ),",
              "        0,",
              "        Shipment",
              "    )"
            ],
            "formatString": "#,0",
            "displayFolder": "YTD",
            "lineageTag": "78d0bbd1-55c1-4d38-846a-9c17a006284b",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Weight YTD",
            "expression": [
              "VAR Weight_KG =",
              "    CALCULATE (",
              "        SUM ( FCT_COMMERCIAL_SUMMARY[Billed Weight KG] ),",
              "        FILTER (",
              "            DIM_PERIOD,",
              "            YEAR ( DIM_PERIOD[Billing Period Date] ) = [YTD]",
              "        )",
              "    )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( Weight_KG ),",
              "        0,",
              "        Weight_KG",
              "    )"
            ],
            "formatString": "#,0.0",
            "displayFolder": "YTD",
            "lineageTag": "196d02b6-c081-49e9-98a0-0aeec66cde94",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "Loyalty Waterfall YTD",
            "expression": [
              "VAR Customers =",
              "    CALCULATE (",
              "        DISTINCTCOUNT ( VW_DIM_CUSTOMER[Customer GSFA ID] ),",
              "        FILTER (",
              "            DIM_PERIOD,",
              "            YEAR ( DIM_PERIOD[Billing Period Date] ) = [YTD]",
              "        )",
              "    )",
              "VAR Result =",
              "    SWITCH (",
              "        SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "        \"Customers\", Customers,",
              "        \"Total Revenue\",",
              "            SWITCH (",
              "                SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                \"BER - Euro\", [Total Revenue EUR YTD],",
              "                \"BER - USD\", [Total Revenue USD YTD],",
              "                \"Local Currency\", [Total Revenue LCY YTD]",
              "            ),",
              "        \"Base Revenue\",",
              "            SWITCH (",
              "                SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                \"BER - Euro\", [Base Revenue EUR YTD],",
              "                \"BER - USD\", [Base Revenue USD YTD],",
              "                \"Local Currency\", [Base Revenue LCY YTD]",
              "            ),",
              "        \"Shipment\", [Number of Shipments YTD],",
              "        \"Weight\", [Billed Weight KG YTD]",
              "    )",
              "RETURN",
              "    Result"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Waterfall Chart",
            "lineageTag": "e2f926bc-2763-4270-87ca-b195a641caff",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Loyalty Waterfall LYTD",
            "expression": [
              "VAR Customers =",
              "    CALCULATE (",
              "        DISTINCTCOUNT ( VW_DIM_CUSTOMER[Customer GSFA ID] ),",
              "        FILTER (",
              "            DIM_PERIOD,",
              "            DIM_PERIOD[Billing Year] = [LY]",
              "        ),",
              "        FILTER (",
              "            DIM_PERIOD,",
              "            MONTH ( DIM_PERIOD[Billing Period Date] ) <= [LM]",
              "        )",
              "    )",
              "VAR Result =",
              "    SWITCH (",
              "        SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "        \"Customers\", Customers,",
              "        \"Total Revenue\",",
              "            SWITCH (",
              "                SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                \"BER - Euro\", [Total Revenue EUR LYTD],",
              "                \"BER - USD\", [Total Revenue USD LYTD],",
              "                \"Local Currency\", [Total Revenue LCY LYTD]",
              "            ),",
              "        \"Base Revenue\",",
              "            SWITCH (",
              "                SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                \"BER - Euro\", [Base Revenue EUR LYTD],",
              "                \"BER - USD\", [Base Revenue USD LYTD],",
              "                \"Local Currency\", [Base Revenue LCY LYTD]",
              "            ),",
              "        \"Shipment\", [Number of Shipments LYTD],",
              "        \"Weight\", [Billed Weight KG LYTD]",
              "    )",
              "RETURN",
              "    Result"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Waterfall Chart",
            "lineageTag": "2e676e85-852f-494e-a781-ac61991d2da1",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Loyalty Waterfall Growth",
            "expression": "[Loyalty Waterfall YTD] - [Loyalty Waterfall LYTD]",
            "formatString": "#,0.0",
            "displayFolder": "Waterfall Chart",
            "lineageTag": "47704bb8-dd44-4d7a-9c84-2f25a9d77923",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Loyalty Waterfall Growth YOY%",
            "expression": [
              "DIVIDE (",
              "    [Loyalty Waterfall YTD] - [Loyalty Waterfall LYTD],",
              "    [Loyalty Waterfall LYTD]",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "Waterfall Chart",
            "lineageTag": "a1347eba-7d8b-46d1-9482-3d7a814df964",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RSW LYTD/LYLM L",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Period Filter'[Period] ),",
              "    \"YTD\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "            \"Total Revenue\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\", [Total Revenue EUR LYTD],",
              "                    \"BER - USD\", [Total Revenue USD LYTD],",
              "                    \"Local Currency\", [Total Revenue LCY LYTD]",
              "                ),",
              "            \"Base Revenue\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\", [Base Revenue EUR LYTD],",
              "                    \"BER - USD\", [Base Revenue USD LYTD],",
              "                    \"Local Currency\", [Base Revenue LCY LYTD]",
              "                ),",
              "            \"Shipment\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\", [Base Revenue EUR LYTD],",
              "                    \"BER - USD\", [Base Revenue USD LYTD],",
              "                    \"Local Currency\", [Base Revenue LCY LYTD]",
              "                ),",
              "            \"Weight\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\", [Base Revenue EUR LYTD],",
              "                    \"BER - USD\", [Base Revenue USD LYTD],",
              "                    \"Local Currency\", [Base Revenue LCY LYTD]",
              "                ),",
              "            \"Customers\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\", [Base Revenue EUR LYTD],",
              "                    \"BER - USD\", [Base Revenue USD LYTD],",
              "                    \"Local Currency\", [Base Revenue LCY LYTD]",
              "                )",
              "        ),",
              "    \"LM\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "            \"Total Revenue\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\", [Total Revenue EUR LYLM],",
              "                    \"BER - USD\", [Total Revenue USD LYLM],",
              "                    \"Local Currency\", [Total Revenue LCY LYLM]",
              "                ),",
              "            \"Base Revenue\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\", [Base Revenue EUR LYLM],",
              "                    \"BER - USD\", [Base Revenue USD LYLM],",
              "                    \"Local Currency\", [Base Revenue LCY LYLM]",
              "                ),",
              "            \"Shipment\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\", [Base Revenue EUR LYLM],",
              "                    \"BER - USD\", [Base Revenue USD LYLM],",
              "                    \"Local Currency\", [Base Revenue LCY LYLM]",
              "                ),",
              "            \"Weight\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\", [Base Revenue EUR LYLM],",
              "                    \"BER - USD\", [Base Revenue USD LYLM],",
              "                    \"Local Currency\", [Base Revenue LCY LYLM]",
              "                ),",
              "            \"Customers\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\", [Base Revenue EUR LYLM],",
              "                    \"BER - USD\", [Base Revenue USD LYLM],",
              "                    \"Local Currency\", [Base Revenue LCY LYLM]",
              "                )",
              "        )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "YTD",
            "lineageTag": "3c82ab43-1433-4eb5-aa0f-4e78b9fcbe6a",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RSW YTD/LM L",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Period Filter'[Period] ),",
              "    \"YTD\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "            \"Total Revenue\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\", [Total Revenue EUR YTD],",
              "                    \"BER - USD\", [Total Revenue USD YTD],",
              "                    \"Local Currency\", [Total Revenue LCY YTD]",
              "                ),",
              "            \"Base Revenue\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\", [Base Revenue EUR YTD],",
              "                    \"BER - USD\", [Base Revenue USD YTD],",
              "                    \"Local Currency\", [Base Revenue LCY YTD]",
              "                ),",
              "            \"Shipment\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\", [Base Revenue EUR YTD],",
              "                    \"BER - USD\", [Base Revenue USD YTD],",
              "                    \"Local Currency\", [Base Revenue LCY YTD]",
              "                ),",
              "            \"Customers\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\", [Base Revenue EUR YTD],",
              "                    \"BER - USD\", [Base Revenue USD YTD],",
              "                    \"Local Currency\", [Base Revenue LCY YTD]",
              "                ),",
              "            \"Weight\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\", [Base Revenue EUR YTD],",
              "                    \"BER - USD\", [Base Revenue USD YTD],",
              "                    \"Local Currency\", [Base Revenue LCY YTD]",
              "                )",
              "        ),",
              "    \"LM\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "            \"Total Revenue\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\", [Total Revenue EUR LM],",
              "                    \"BER - USD\", [Total Revenue USD LM],",
              "                    \"Local Currency\", [Total Revenue LCY LM]",
              "                ),",
              "            \"Base Revenue\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\", [Base Revenue EUR LM],",
              "                    \"BER - USD\", [Base Revenue USD LM],",
              "                    \"Local Currency\", [Base Revenue LCY LM]",
              "                ),",
              "            \"Shipment\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\", [Base Revenue EUR LM],",
              "                    \"BER - USD\", [Base Revenue USD LM],",
              "                    \"Local Currency\", [Base Revenue LCY LM]",
              "                ),",
              "            \"Weight\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\", [Base Revenue EUR LM],",
              "                    \"BER - USD\", [Base Revenue USD LM],",
              "                    \"Local Currency\", [Base Revenue LCY LM]",
              "                ),",
              "            \"Customers\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\", [Base Revenue EUR LM],",
              "                    \"BER - USD\", [Base Revenue USD LM],",
              "                    \"Local Currency\", [Base Revenue LCY LM]",
              "                )",
              "        )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "YTD",
            "lineageTag": "d5b035b7-96b5-4f1e-8369-58751aeccdd9",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RSW YTD/LM L/LYTD/LYLM L YOY%",
            "expression": [
              "VAR _Growth = [RSW YTD/LM L] - [RSW LYTD/LYLM L]",
              "RETURN",
              "    DIVIDE (",
              "        _Growth,",
              "        [RSW LYTD/LYLM L]",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "YTD",
            "lineageTag": "2ab652aa-1544-42ba-b326-fd63b4485b02",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Working Days",
        "lineageTag": "a00676f7-6d9f-425f-b11e-5091b850f727",
        "columns": [
          {
            "name": "Column1",
            "dataType": "string",
            "sourceColumn": "Column1",
            "lineageTag": "e1a5ba85-cc1c-43eb-b7e6-fc78d72ca71f",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Working Days-1657d894-cadc-40b2-9da5-88ea09293267",
            "mode": "import",
            "queryGroup": "Static Filter Table",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "_Working Days",
            "expression": [
              "VAR country =",
              "    SELECTEDVALUE ( DIM_SALES_FUNCTION[Owner Country Code] )",
              "VAR region =",
              "    SELECTEDVALUE ( DIM_SALES_FUNCTION[Owner Region Code] )",
              "VAR count_region =",
              "    DISTINCTCOUNTNOBLANK ( DIM_SALES_FUNCTION[Owner Region Code] )",
              "VAR count_country =",
              "    DISTINCTCOUNTNOBLANK ( DIM_SALES_FUNCTION[Owner Country Code] )",
              "RETURN",
              "    IF (",
              "        NOT (",
              "            ISFILTERED ( DIM_SALES_FUNCTION[Sales Function - Country Code] )",
              "        )",
              "            || count_region > 1,",
              "        CALCULATE (",
              "            SUM ( 'DIM_WORK_DAYS_GEO'[Number of Working Days] ),",
              "            'DIM_WORK_DAYS_GEO'[GEO CODE] = \"Global\",",
              "            'DIM_WORK_DAYS_GEO'[GEO TYPE] = \"G\"",
              "        ),",
              "        IF (",
              "            count_region = 1",
              "                && count_country = 1,",
              "            CALCULATE (",
              "                SUM ( 'DIM_WORK_DAYS_GEO'[Number of Working Days] ),",
              "                'DIM_WORK_DAYS_GEO'[GEO CODE] = country,",
              "                'DIM_WORK_DAYS_GEO'[GEO TYPE] = \"C\"",
              "            ),",
              "            IF (",
              "                count_region = 1",
              "                    && count_country > 1,",
              "                CALCULATE (",
              "                    SUM ( 'DIM_WORK_DAYS_GEO'[Number of Working Days] ),",
              "                    'DIM_WORK_DAYS_GEO'[GEO CODE] = region,",
              "                    'DIM_WORK_DAYS_GEO'[GEO TYPE] = \"R\"",
              "                ),",
              "                BLANK ()",
              "            )",
              "        )",
              "    )"
            ],
            "formatString": "0.00",
            "lineageTag": "5f74e727-bcda-4ef5-bebc-696eb562f7e6",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "Working Days YTD",
            "expression": [
              "CALCULATE (",
              "    [_Working Days],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Year] = [YTD]",
              "    ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        MONTH ( DIM_PERIOD[Billing Period Date] ) <= [LM]",
              "    )",
              ")"
            ],
            "lineageTag": "fb04490e-b3aa-4a6c-91a1-a353e342ea91",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "_Working Days LM13",
            "expression": [
              "CALCULATE (",
              "    [_Working Days],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 14",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                < EOMONTH (",
              "                    [Today],",
              "                    -1",
              "                )",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "lineageTag": "a174d508-b4e2-435b-a017-5e8c4f7ab7df",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "_Working Days LM13L",
            "expression": [
              "CALCULATE (",
              "    [_Working Days],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                TODAY (),",
              "                - 26",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                < EOMONTH (",
              "                    TODAY (),",
              "                    -13",
              "                )",
              "    )",
              ")"
            ],
            "lineageTag": "3fbbd7eb-2429-41cd-aefb-5b0c63573c92",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "_Working Days LYTD",
            "expression": [
              "CALCULATE (",
              "    [_Working Days],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Year] = [LYTD]",
              "    ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        MONTH ( DIM_PERIOD[Billing Period Date] ) <= [LM]",
              "    )",
              ")"
            ],
            "lineageTag": "e426c73f-b1bf-4969-abe3-779cd8331d54",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "_Working Days LM",
            "expression": [
              "CALCULATE (",
              "    [_Working Days],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Year] = [YTD]",
              "    ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        MONTH ( DIM_PERIOD[Billing Period Date] ) = [LM]",
              "    )",
              ")"
            ],
            "lineageTag": "1afda7ea-c577-4fed-958a-3188e5a27613",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "_Working Days LYLM",
            "expression": [
              "CALCULATE (",
              "    [_Working Days],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Year] = [LY]",
              "    ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        MONTH ( DIM_PERIOD[Billing Period Date] ) = [LM]",
              "    )",
              ")"
            ],
            "lineageTag": "ba95f191-b7d2-410f-9aa0-567acf69f65b",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "_Working Days LY",
            "expression": [
              "CALCULATE (",
              "    [_Working Days],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Year] = [LY]",
              "    )",
              ")"
            ],
            "lineageTag": "d9ba1c39-b24b-47d6-ae7b-b86dbff14e2c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Key Measures",
        "lineageTag": "a817a33a-453c-4717-ad32-5bd2d0af0ec4",
        "columns": [
          {
            "name": "Column1",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Column1",
            "lineageTag": "1a3d35ad-cd6f-44f7-b687-16d864585d0a",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Key Measures-55cfbc3c-7ec5-4681-b5db-4ca3c2f1eb93",
            "mode": "import",
            "queryGroup": "Static Filter Table",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Base Revenue EUR LYLM",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Base Revenue EUR@BER] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Year] = [LY]",
              "    ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        MONTH ( DIM_PERIOD[Billing Period Date] ) = [LM]",
              "    )",
              ")"
            ],
            "displayFolder": "Base Revenue LYLM",
            "lineageTag": "b687ccb9-6d91-4539-a9f8-36f23f17b11f",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Base Revenue EUR YTD",
            "expression": [
              "CALCULATE (",
              "    [Base Revenue EUR],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        YEAR ( DIM_PERIOD[Billing Period Date] ) = [YTD]",
              "    )",
              ")"
            ],
            "displayFolder": "Base Revenue YTD",
            "lineageTag": "21d753ab-2edc-4a1a-9139-13f1bc1e468c",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Billed Weight KG LY",
            "expression": [
              "CALCULATE (",
              "    [Billed Weight KG],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        YEAR ( DIM_PERIOD[Billing Period Date] ) = [LY]",
              "    )",
              ")"
            ],
            "displayFolder": "Weight",
            "lineageTag": "2af717c8-3766-4dab-9e10-ef3c73f607a9",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Billed Weight KG LYLM",
            "expression": [
              "CALCULATE (",
              "    [Billed Weight KG],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        YEAR ( DIM_PERIOD[Billing Period Date] ) = [LY]",
              "    ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        MONTH ( DIM_PERIOD[Billing Period Date] ) = [LM]",
              "    )",
              ")"
            ],
            "displayFolder": "Weight",
            "lineageTag": "270e1ef2-ae04-4529-a98b-2c93b437d532",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Base Revenue LCY",
            "expression": "SUM ( FCT_COMMERCIAL_SUMMARY[Base Revenue LCY] )",
            "displayFolder": "Sum of Base Revenue",
            "lineageTag": "d2fa3516-415b-42ac-9131-8a873eabeeef",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Base Revenue LCY LM",
            "expression": [
              "CALCULATE (",
              "    [Base Revenue LCY],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        YEAR ( DIM_PERIOD[Billing Period Date] ) = [YTD]",
              "    ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        MONTH ( DIM_PERIOD[Billing Period Date] ) = [LM]",
              "    )",
              ")"
            ],
            "displayFolder": "Base Revenue Month 0-5",
            "lineageTag": "93cf6108-8070-4149-a7de-fe86ab444d83",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Base Revenue LCY LY",
            "expression": [
              "CALCULATE (",
              "    [Base Revenue LCY],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        YEAR ( DIM_PERIOD[Billing Period Date] ) = [LY]",
              "    )",
              ")"
            ],
            "displayFolder": "Base Revenue LY",
            "lineageTag": "97423be3-1067-477e-88d2-0300a7c1340b",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Base Revenue LCY LYLM",
            "expression": [
              "CALCULATE (",
              "    [Base Revenue LCY],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        YEAR ( DIM_PERIOD[Billing Period Date] ) = [LY]",
              "    ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        MONTH ( DIM_PERIOD[Billing Period Date] ) = [LM]",
              "    )",
              ")"
            ],
            "displayFolder": "Base Revenue LYLM",
            "lineageTag": "49745913-398f-498e-96d3-cb6fdb18d5a8",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Base Revenue LCY YTD",
            "expression": [
              "CALCULATE (",
              "    [Base Revenue LCY],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        YEAR ( DIM_PERIOD[Billing Period Date] ) = [YTD]",
              "    )",
              ")"
            ],
            "displayFolder": "Base Revenue YTD",
            "lineageTag": "359d714d-964a-469c-bf8a-3347de1aab5a",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Base Revenue USD LM",
            "expression": [
              "CALCULATE (",
              "    [Base Revenue USD],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        YEAR ( DIM_PERIOD[Billing Period Date] ) = [YTD]",
              "    ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        MONTH ( DIM_PERIOD[Billing Period Date] ) = [LM]",
              "    )",
              ")"
            ],
            "displayFolder": "Base Revenue Month 0-5",
            "lineageTag": "9b2c4293-c23d-4598-b3e3-d3bdf44c5d67",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Base Revenue USD LY",
            "expression": [
              "CALCULATE (",
              "    [Base Revenue USD],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        YEAR ( DIM_PERIOD[Billing Period Date] ) = [LY]",
              "    )",
              ")"
            ],
            "displayFolder": "Base Revenue LY",
            "lineageTag": "fc859c21-a6ca-46d9-9747-6d95842d9e00",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Base Revenue USD LYLM",
            "expression": [
              "CALCULATE (",
              "    [Base Revenue USD],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        YEAR ( DIM_PERIOD[Billing Period Date] ) = [LY]",
              "    ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        MONTH ( DIM_PERIOD[Billing Period Date] ) = [LM]",
              "    )",
              ")"
            ],
            "displayFolder": "Base Revenue LYLM",
            "lineageTag": "d0c7cfc3-8584-468c-8a0e-cbe224c088ae",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Base Revenue USD YTD",
            "expression": [
              "CALCULATE (",
              "    [Base Revenue USD],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        YEAR ( DIM_PERIOD[Billing Period Date] ) = [YTD]",
              "    )",
              ")"
            ],
            "displayFolder": "Base Revenue YTD",
            "lineageTag": "8e4b1049-f935-4773-8d8e-344f61949ada",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Base Revenue USD",
            "expression": "SUM ( FCT_COMMERCIAL_SUMMARY[Base Revenue USD@BER] )",
            "displayFolder": "Sum of Base Revenue",
            "lineageTag": "fec2ff9e-7e4c-48fa-a248-575e5b1498b7",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "RSW YTD",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "    \"Total Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\", [Total Revenue EUR YTD],",
              "            \"BER - USD\", [Total Revenue USD YTD],",
              "            \"Local Currency\", [Total Revenue LCY YTD]",
              "        ),",
              "    \"Base Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\", [Base Revenue EUR YTD],",
              "            \"BER - USD\", [Base Revenue USD YTD],",
              "            \"Local Currency\", [Base Revenue LCY YTD]",
              "        ),",
              "    \"Shipment\", [Number of Shipments YTD],",
              "    \"Weight\", [Billed Weight KG YTD]",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "RSW",
            "lineageTag": "f59bdb13-c901-4054-ad6a-a524fdc05824",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "RSW YTD/LM",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Period Filter'[Period] ),",
              "    \"YTD\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "            \"Total Revenue\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\", [Total Revenue EUR YTD],",
              "                    \"BER - USD\", [Total Revenue USD YTD],",
              "                    \"Local Currency\", [Total Revenue LCY YTD]",
              "                ),",
              "            \"Base Revenue\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\", [Base Revenue EUR YTD],",
              "                    \"BER - USD\", [Base Revenue USD YTD],",
              "                    \"Local Currency\", [Base Revenue LCY YTD]",
              "                ),",
              "            \"Shipment\", [Number of Shipments YTD],",
              "            \"Weight\", [Billed Weight KG YTD]",
              "        ),",
              "    \"LM\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "            \"Total Revenue\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\", [Total Revenue EUR LM],",
              "                    \"BER - USD\", [Total Revenue USD LM],",
              "                    \"Local Currency\", [Total Revenue LCY LM]",
              "                ),",
              "            \"Base Revenue\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\", [Base Revenue EUR LM],",
              "                    \"BER - USD\", [Base Revenue USD LM],",
              "                    \"Local Currency\", [Base Revenue LCY LM]",
              "                ),",
              "            \"Shipment\", [Number of Shipments LM],",
              "            \"Weight\", [Billed Weight KG LM]",
              "        )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "RSW",
            "lineageTag": "59b0fa5f-95e0-4750-84cf-4818b2c1c45e",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "Total Revenue LCY",
            "expression": "SUM ( FCT_COMMERCIAL_SUMMARY[Total Revenue LCY] )",
            "displayFolder": "Sum of Total Revenue",
            "lineageTag": "bcd73250-69ee-4a8f-91f3-83e0ed6415bf",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue LCY LM",
            "expression": [
              "CALCULATE (",
              "    [Total Revenue LCY],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        YEAR ( DIM_PERIOD[Billing Period Date] ) = [YTD]",
              "    ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        MONTH ( DIM_PERIOD[Billing Period Date] ) = [LM]",
              "    )",
              ")"
            ],
            "displayFolder": "Total Revenue LM",
            "lineageTag": "f1513cfe-f5f7-448f-a898-5bbbf4ba761f",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue LCY LY",
            "expression": [
              "CALCULATE (",
              "    [Total Revenue LCY],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        YEAR ( DIM_PERIOD[Billing Period Date] ) = [LY]",
              "    )",
              ")"
            ],
            "displayFolder": "Total Revenue LY",
            "lineageTag": "3f0c299f-ab30-424a-9ec2-1d0e015f9793",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue LCY LYLM",
            "expression": [
              "CALCULATE (",
              "    [Total Revenue LCY],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        YEAR ( DIM_PERIOD[Billing Period Date] ) = [LY]",
              "    ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        MONTH ( DIM_PERIOD[Billing Period Date] ) = [LM]",
              "    )",
              ")"
            ],
            "displayFolder": "Total Revenue LYLM",
            "lineageTag": "32ae538f-ac98-493b-800a-8d334ec76d05",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue LCY YTD",
            "expression": [
              "CALCULATE (",
              "    [Total Revenue LCY],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        YEAR ( DIM_PERIOD[Billing Period Date] ) = [YTD]",
              "    )",
              ")"
            ],
            "displayFolder": "Total Revenue YTD",
            "lineageTag": "b0c1b906-b779-415a-8850-e2a18699710c",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue USD LM",
            "expression": [
              "CALCULATE (",
              "    [Total Revenue USD],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        YEAR ( DIM_PERIOD[Billing Period Date] ) = [YTD]",
              "    ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        MONTH ( DIM_PERIOD[Billing Period Date] ) = [LM]",
              "    )",
              ")"
            ],
            "displayFolder": "Total Revenue LM",
            "lineageTag": "ba4ef147-754c-4c14-ad2a-39d808d77f2f",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue USD LY",
            "expression": [
              "CALCULATE (",
              "    [Total Revenue USD],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        YEAR ( DIM_PERIOD[Billing Period Date] ) = [LY]",
              "    )",
              ")"
            ],
            "displayFolder": "Total Revenue LY",
            "lineageTag": "9f9bf841-0c4a-4e41-bcc8-16cfaaf73cac",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue USD LYLM",
            "expression": [
              "CALCULATE (",
              "    [Total Revenue USD],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        YEAR ( DIM_PERIOD[Billing Period Date] ) = [LY]",
              "    ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        MONTH ( DIM_PERIOD[Billing Period Date] ) = [LM]",
              "    )",
              ")"
            ],
            "displayFolder": "Total Revenue LYLM",
            "lineageTag": "59aa9f9c-1ae2-4ccb-86af-f93c10f94897",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue USD YTD",
            "expression": [
              "CALCULATE (",
              "    [Total Revenue USD],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        YEAR ( DIM_PERIOD[Billing Period Date] ) = [YTD]",
              "    )",
              ")"
            ],
            "displayFolder": "Total Revenue YTD",
            "lineageTag": "e180b377-8995-4ee8-be5c-729db4105185",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue USD",
            "expression": "SUM ( FCT_COMMERCIAL_SUMMARY[Total Revenue USD@BER] )",
            "displayFolder": "Sum of Total Revenue",
            "lineageTag": "d6cf36dc-7d58-45ff-8e2a-551b804d9961",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Billed Weight KG",
            "expression": "SUM ( FCT_COMMERCIAL_SUMMARY[Billed Weight KG] )",
            "displayFolder": "Weight",
            "lineageTag": "ca0aa96e-7f8b-4b5b-a03a-4ee9f16d5f48",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Number of Shipments",
            "expression": "SUM ( FCT_COMMERCIAL_SUMMARY[Number of Shipments] )",
            "displayFolder": "Shipments",
            "lineageTag": "412c24f2-f31c-4763-b724-9022746ea7d5",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Number of Shipments LY",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Number of Shipments] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        YEAR ( DIM_PERIOD[Billing Period Date] ) = [LY]",
              "    )",
              ")"
            ],
            "displayFolder": "Shipments",
            "lineageTag": "152d9466-de07-43e0-b52c-c1e52720b65b",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Number of Shipments YTD",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Number of Shipments] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Year] = [YTD]",
              "    )",
              ")"
            ],
            "displayFolder": "Shipments",
            "lineageTag": "b075a40e-c390-4a97-86de-52f83e1e9b8b",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Billed Weight KG YTD",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Billed Weight KG] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        YEAR ( DIM_PERIOD[Billing Period Date] ) = [YTD]",
              "    )",
              ")"
            ],
            "displayFolder": "Weight",
            "lineageTag": "fce68b8b-3e53-496f-951e-90c955bc0bb8",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue EUR YTD",
            "expression": [
              "CALCULATE (",
              "    [Total Revenue EUR],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        YEAR ( DIM_PERIOD[Billing Period Date] ) = [YTD]",
              "    )",
              ")"
            ],
            "displayFolder": "Total Revenue YTD",
            "lineageTag": "e207bb16-ffc7-44b4-998d-916007675a76",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue EUR LM",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Total Revenue EUR@BER] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        YEAR ( DIM_PERIOD[Billing Period Date] ) = [YTD]",
              "    ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        MONTH ( DIM_PERIOD[Billing Period Date] ) = [LM]",
              "    )",
              ")"
            ],
            "displayFolder": "Total Revenue LM",
            "lineageTag": "d159cc03-8898-4df8-b8d5-45ae3845d610",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue EUR",
            "expression": "SUM ( FCT_COMMERCIAL_SUMMARY[Total Revenue EUR@BER] )",
            "displayFolder": "Sum of Total Revenue",
            "lineageTag": "86675c25-8762-465e-b851-959eb3ecda6a",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue EUR PLY",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Base Revenue EUR@BER] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        YEAR ( DIM_PERIOD[Billing Period Date] ) = [PLY]",
              "    )",
              ")"
            ],
            "displayFolder": "Total Revenue PLY",
            "lineageTag": "954efd1a-0006-4dc9-af10-9ca5bde09791",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Base Revenue EUR PLY",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Base Revenue EUR@BER] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Year] = [PLY]",
              "    )",
              ")"
            ],
            "displayFolder": "Base Revenue PLY",
            "lineageTag": "2b73259e-5191-40d1-b214-8f0f8eb3b389",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue USD PLY",
            "expression": [
              "CALCULATE (",
              "    [Total Revenue USD],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        YEAR ( DIM_PERIOD[Billing Period Date] ) = [PLY]",
              "    )",
              ")"
            ],
            "displayFolder": "Total Revenue PLY",
            "lineageTag": "95fff820-8785-42eb-87be-e2c22ea827ae",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Base Revenue USD PLY",
            "expression": [
              "CALCULATE (",
              "    [Base Revenue USD],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        YEAR ( DIM_PERIOD[Billing Period Date] ) = [PLY]",
              "    )",
              ")"
            ],
            "displayFolder": "Base Revenue PLY",
            "lineageTag": "04b0af7c-eabc-4616-9c29-2c825f397292",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue LCY PLY",
            "expression": [
              "CALCULATE (",
              "    [Total Revenue LCY],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        YEAR ( DIM_PERIOD[Billing Period Date] ) = [PLY]",
              "    )",
              ")"
            ],
            "displayFolder": "Total Revenue PLY",
            "lineageTag": "90f3f2e3-75bb-46de-91bb-bbb002d1ecf6",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Base Revenue LCY PLY",
            "expression": [
              "CALCULATE (",
              "    [Base Revenue LCY],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        YEAR ( DIM_PERIOD[Billing Period Date] ) = [PLY]",
              "    )",
              ")"
            ],
            "displayFolder": "Base Revenue PLY",
            "lineageTag": "cbb6cacf-bbe8-4ae4-b535-44fea8fb50f9",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Number of Shipments PLY",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Number of Shipments] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        YEAR ( DIM_PERIOD[Billing Period Date] ) = [PLY]",
              "    )",
              ")"
            ],
            "displayFolder": "Shipments",
            "lineageTag": "3e2f6d72-9ad5-4e16-95a8-21daa5012e00",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "Billed Weight KG PLY",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Billed Weight KG] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        YEAR ( DIM_PERIOD[Billing Period Date] ) = [PLY]",
              "    )",
              ")"
            ],
            "displayFolder": "Weight",
            "lineageTag": "6c826d9d-95d0-4982-8812-39e8c9ad793e",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Base Revenue EUR",
            "expression": "SUM ( FCT_COMMERCIAL_SUMMARY[Base Revenue EUR@BER] )",
            "formatString": "#,0.0",
            "displayFolder": "Sum of Base Revenue",
            "lineageTag": "819a3b12-1a36-427a-b197-11babae549ab",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "RSW Title",
            "expression": [
              "\"Total\"",
              "    && SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] )"
            ],
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "displayFolder": "RSW",
            "lineageTag": "0a89f71f-cfea-4638-b091-501fa931179e",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "Base Revenue LM",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "    \"BER - Euro\", [Base Revenue EUR LM],",
              "    \"BER - USD\", [Base Revenue USD LM],",
              "    \"Local Currency\", [Base Revenue LCY LM]",
              ")"
            ],
            "displayFolder": "Base Revenue CUR Filter Mon 1-5",
            "lineageTag": "b72f2afc-ad5c-4945-856e-c466d8e02129",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Number of Shipments LM",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Number of Shipments] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Year] = [YTD]",
              "    ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        MONTH ( DIM_PERIOD[Billing Period Date] ) = [LM]",
              "    )",
              ")"
            ],
            "displayFolder": "Shipments",
            "lineageTag": "114090c6-86db-4704-9ec0-8ee4c9b96916",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Billed Weight KG LM",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Billed Weight KG] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        YEAR ( DIM_PERIOD[Billing Period Date] ) = [YTD]",
              "            && MONTH ( DIM_PERIOD[Billing Period Date] ) = [LM]",
              "    )",
              ")"
            ],
            "displayFolder": "Weight",
            "lineageTag": "05bbdfc7-3592-45a2-a6f9-88f5ba37266d",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Number of Shipments LYLM",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Number of Shipments] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        YEAR ( DIM_PERIOD[Billing Period Date] ) = [LY]",
              "    ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        MONTH ( DIM_PERIOD[Billing Period Date] ) = [LM]",
              "    )",
              ")"
            ],
            "displayFolder": "Shipments",
            "lineageTag": "9b8773b4-6178-44cf-8d9f-141ee457b582",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Base Revenue EUR LM-1",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Base Revenue EUR@BER] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 3",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                < EOMONTH (",
              "                    [Today],",
              "                    -2",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Base Revenue Month 0-5",
            "lineageTag": "6dadc387-4379-4abf-b301-3992de6fedbc",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Base Revenue USD LM-1",
            "expression": [
              "CALCULATE (",
              "    [Base Revenue USD],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 3",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                < EOMONTH (",
              "                    [Today],",
              "                    -2",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Base Revenue Month 0-5",
            "lineageTag": "b1f372e3-ab2e-4a8f-93e0-41e9cc2db805",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Base Revenue LCY LM-1",
            "expression": [
              "CALCULATE (",
              "    [Base Revenue LCY],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 3",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                < EOMONTH (",
              "                    [Today],",
              "                    -2",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Base Revenue Month 0-5",
            "lineageTag": "13c773e7-d50e-4bdd-9b89-a87637468b14",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Base Revenue LM-1",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "    \"BER - Euro\", [Base Revenue EUR LM-1],",
              "    \"BER - USD\", [Base Revenue USD LM-1],",
              "    \"Local Currency\", [Base Revenue LCY LM-1]",
              ")"
            ],
            "displayFolder": "Base Revenue CUR Filter Mon 1-5",
            "lineageTag": "a9953580-2cfb-4e76-a25f-993ed5fec57f",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Number of Shipments LM-1",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Number of Shipments] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 3",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                < EOMONTH (",
              "                    [Today],",
              "                    -2",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Shipments",
            "lineageTag": "a5195ba1-aa8d-4445-b91c-b78b018b9bd7",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Billed Weight KG LM-1",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Billed Weight KG] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 3",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                < EOMONTH (",
              "                    [Today],",
              "                    -2",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Weight",
            "lineageTag": "203c2ee8-de53-48c6-85a6-388072c42c17",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "RSW with BaseRevenue LM-1",
            "expression": [
              "VAR LMNumber =",
              "    SWITCH (",
              "        SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "        \"Revenue\", [Base Revenue LM-1],",
              "        \"Shipment\", [Number of Shipments LM-1],",
              "        \"Weight\", [Billed Weight KG LM-1]",
              "    )",
              "RETURN",
              "    LMNumber"
            ],
            "formatString": "#,0.0",
            "displayFolder": "RSW",
            "lineageTag": "12fccdb2-5810-4a98-bab1-5f92a2b6a838",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Base Revenue LCY LM-2",
            "expression": [
              "CALCULATE (",
              "    [Base Revenue LCY],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 4",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                < EOMONTH (",
              "                    [Today],",
              "                    -3",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Base Revenue Month 0-5",
            "lineageTag": "7896afbd-70e0-44aa-b8c4-231b335ae034",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Base Revenue USD LM-2",
            "expression": [
              "CALCULATE (",
              "    [Base Revenue USD],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 4",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                < EOMONTH (",
              "                    [Today],",
              "                    -3",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Base Revenue Month 0-5",
            "lineageTag": "b73c8253-81fd-4dd6-9ed5-764617c6d303",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Billed Weight KG LM-2",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Billed Weight KG] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 4",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                < EOMONTH (",
              "                    [Today],",
              "                    -3",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Weight",
            "lineageTag": "5d25ac0b-664d-4c29-89dc-4f6a5b3a27b6",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Number of Shipments LM-2",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Number of Shipments] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 4",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                < EOMONTH (",
              "                    [Today],",
              "                    -3",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Shipments",
            "lineageTag": "769ce2a0-cca9-47f6-b144-8d114487e8e5",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Base Revenue EUR LM-2",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Base Revenue EUR@BER] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 4",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                < EOMONTH (",
              "                    [Today],",
              "                    -3",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Base Revenue Month 0-5",
            "lineageTag": "6b8c9a15-951c-4697-8fcb-4c66a2c91f8c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Base Revenue LM-2",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "    \"BER - Euro\", [Base Revenue EUR LM-2],",
              "    \"BER - USD\", [Base Revenue USD LM-2],",
              "    \"Local Currency\", [Base Revenue LCY LM-2]",
              ")"
            ],
            "displayFolder": "Base Revenue CUR Filter Mon 1-5",
            "lineageTag": "a4a9a699-78a8-4d3f-a8b1-40fee14395ba",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "RSW with BaseRevenue LM-2",
            "expression": [
              "VAR LMNumber =",
              "    SWITCH (",
              "        SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "        \"Revenue\", [Base Revenue LM-2],",
              "        \"Shipment\", [Number of Shipments LM-2],",
              "        \"Weight\", [Billed Weight KG LM-2]",
              "    )",
              "RETURN",
              "    LMNumber"
            ],
            "formatString": "#,0.0",
            "displayFolder": "RSW",
            "lineageTag": "97088252-e776-4812-a3a5-82ce2bb839ac",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Base Revenue LCY LM-3",
            "expression": [
              "CALCULATE (",
              "    [Base Revenue LCY],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 5",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                < EOMONTH (",
              "                    [Today],",
              "                    -4",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Base Revenue Month 0-5",
            "lineageTag": "753d4ffd-307b-411b-8688-fdbd90ec9d3d",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Base Revenue USD LM-3",
            "expression": [
              "CALCULATE (",
              "    [Base Revenue USD],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 5",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                < EOMONTH (",
              "                    [Today],",
              "                    -4",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Base Revenue Month 0-5",
            "lineageTag": "5594f969-98ad-462b-b4f3-393ec173428b",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Billed Weight KG LM-3",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Billed Weight KG] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 5",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                < EOMONTH (",
              "                    [Today],",
              "                    -4",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Weight",
            "lineageTag": "4d115a02-068d-4ae3-9e85-592834bb56ce",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Number of Shipments LM-3",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Number of Shipments] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 5",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                < EOMONTH (",
              "                    [Today],",
              "                    -4",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Shipments",
            "lineageTag": "405eae80-b7e9-4ec2-99e0-9d18a32d96eb",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Base Revenue EUR LM-3",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Base Revenue EUR@BER] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 5",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                < EOMONTH (",
              "                    [Today],",
              "                    -4",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Base Revenue Month 0-5",
            "lineageTag": "277aa9d8-bd0b-44ea-9827-7ae1889731f6",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Base Revenue LM-3",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "    \"BER - Euro\", [Base Revenue EUR LM-3],",
              "    \"BER - USD\", [Base Revenue USD LM-3],",
              "    \"Local Currency\", [Base Revenue LCY LM-3]",
              ")"
            ],
            "displayFolder": "Base Revenue CUR Filter Mon 1-5",
            "lineageTag": "265ae8b1-685f-499f-852d-0a20ef4974dc",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "RSW with BaseRevenue LM-3",
            "expression": [
              "VAR LMNumber =",
              "    SWITCH (",
              "        SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "        \"Revenue\", [Base Revenue LM-3],",
              "        \"Shipment\", [Number of Shipments LM-3],",
              "        \"Weight\", [Billed Weight KG LM-3]",
              "    )",
              "RETURN",
              "    LMNumber"
            ],
            "formatString": "#,0.0",
            "displayFolder": "RSW",
            "lineageTag": "9e8f14f1-79a8-4f50-a2c0-efe43791effb",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Base Revenue LCY LM-4",
            "expression": [
              "CALCULATE (",
              "    [Base Revenue LCY],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 6",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                < EOMONTH (",
              "                    [Today],",
              "                    -5",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Base Revenue Month 0-5",
            "lineageTag": "c5394c5c-9177-4a35-a9e9-058735fa206c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Base Revenue USD LM-4",
            "expression": [
              "CALCULATE (",
              "    [Base Revenue USD],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 6",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                < EOMONTH (",
              "                    [Today],",
              "                    -5",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Base Revenue Month 0-5",
            "lineageTag": "9d34a1b4-7396-4246-b208-75cbfe7d97dd",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Billed Weight KG LM-4",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Billed Weight KG] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 6",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                < EOMONTH (",
              "                    [Today],",
              "                    -5",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Weight",
            "lineageTag": "b95f83e0-dfef-461a-9d9a-bae12b2520d7",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Number of Shipments LM-4",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Number of Shipments] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 6",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                < EOMONTH (",
              "                    [Today],",
              "                    -5",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Shipments",
            "lineageTag": "36349f35-d093-4a61-8d48-4bb16e54fced",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Base Revenue EUR LM-4",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Base Revenue EUR@BER] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 6",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                < EOMONTH (",
              "                    [Today],",
              "                    -5",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Base Revenue Month 0-5",
            "lineageTag": "c6f3d649-df02-41a5-b2b2-281755ecf953",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Base Revenue LM-4",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "    \"BER - Euro\", [Base Revenue EUR LM-4],",
              "    \"BER - USD\", [Base Revenue USD LM-4],",
              "    \"Local Currency\", [Base Revenue LCY LM-4]",
              ")"
            ],
            "displayFolder": "Base Revenue CUR Filter Mon 1-5",
            "lineageTag": "b98a7572-b2e9-4ddd-b9d0-ee6757b901e2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "RSW with BaseRevenue LM-4",
            "expression": [
              "VAR LMNumber =",
              "    SWITCH (",
              "        SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "        \"Revenue\", [Base Revenue LM-4],",
              "        \"Shipment\", [Number of Shipments LM-4],",
              "        \"Weight\", [Billed Weight KG LM-4]",
              "    )",
              "RETURN",
              "    LMNumber"
            ],
            "formatString": "#,0.0",
            "displayFolder": "RSW",
            "lineageTag": "ff4290aa-45f1-4da1-98a4-5054e4c6021b",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Base Revenue LCY LM-5",
            "expression": [
              "CALCULATE (",
              "    [Base Revenue LCY],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 7",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                < EOMONTH (",
              "                    [Today],",
              "                    -6",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Base Revenue Month 0-5",
            "lineageTag": "811d3d78-1fbd-4ea0-8d77-cec14f3874e9",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Base Revenue USD LM-5",
            "expression": [
              "CALCULATE (",
              "    [Base Revenue USD],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 7",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                < EOMONTH (",
              "                    [Today],",
              "                    -6",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Base Revenue Month 0-5",
            "lineageTag": "d506e045-45c3-41dd-ae45-a2c798fdbe10",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Billed Weight KG LM-5",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Billed Weight KG] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 7",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                < EOMONTH (",
              "                    [Today],",
              "                    -6",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Weight",
            "lineageTag": "1e0d6e72-127c-4e51-af2d-aa557c37d227",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Number of Shipments LM-5",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Number of Shipments] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 7",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                < EOMONTH (",
              "                    [Today],",
              "                    -6",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Shipments",
            "lineageTag": "70d047ea-81c1-47b1-aaf8-9bf0c7dc84eb",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Base Revenue EUR LM-5",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Base Revenue EUR@BER] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 7",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                < EOMONTH (",
              "                    [Today],",
              "                    -6",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Base Revenue Month 0-5",
            "lineageTag": "7a74c99a-a9d6-4fcc-b401-75195046896d",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Base Revenue LM-5",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "    \"BER - Euro\", [Base Revenue EUR LM-5],",
              "    \"BER - USD\", [Base Revenue USD LM-5],",
              "    \"Local Currency\", [Base Revenue LCY LM-5]",
              ")"
            ],
            "displayFolder": "Base Revenue CUR Filter Mon 1-5",
            "lineageTag": "9f053158-9b61-4462-88ca-9e5a3db1e064",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "RSW with BaseRevenue LM-5",
            "expression": [
              "VAR LMNumber =",
              "    SWITCH (",
              "        SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "        \"Revenue\", [Base Revenue LM-5],",
              "        \"Shipment\", [Number of Shipments LM-5],",
              "        \"Weight\", [Billed Weight KG LM-5]",
              "    )",
              "RETURN",
              "    LMNumber"
            ],
            "formatString": "#,0.0",
            "displayFolder": "RSW",
            "lineageTag": "7bea5cd2-06d1-4b24-bf02-39f031955674",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Base Revenue EUR LM",
            "expression": [
              "CALCULATE (",
              "    [Base Revenue EUR],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        YEAR ( DIM_PERIOD[Billing Period Date] ) = [YTD]",
              "    ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        MONTH ( DIM_PERIOD[Billing Period Date] ) = [LM]",
              "    )",
              ")"
            ],
            "displayFolder": "Base Revenue Month 0-5",
            "lineageTag": "f32576c4-4d4d-4a11-aa0f-d96845cf6883",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue EUR LYTD",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Total Revenue EUR@BER] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Year] = [LY]",
              "    ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        MONTH ( DIM_PERIOD[Billing Period Date] ) <= [LM]",
              "    )",
              ")"
            ],
            "displayFolder": "Total Revenue LYTD",
            "lineageTag": "ae7af534-1432-4e2f-a637-3393d4cc5821",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue LCY LYTD",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Total Revenue LCY] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Year] = [LY]",
              "    ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        MONTH ( DIM_PERIOD[Billing Period Date] ) <= [LM]",
              "    )",
              ")"
            ],
            "displayFolder": "Total Revenue LYTD",
            "lineageTag": "6a4a18f2-1660-47f7-8b97-9766569f1849",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue USD LYTD",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Total Revenue USD@BER] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Year] = [LY]",
              "    ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        MONTH ( DIM_PERIOD[Billing Period Date] ) <= [LM]",
              "    )",
              ")"
            ],
            "displayFolder": "Total Revenue LYTD",
            "lineageTag": "3c0c8212-75ed-4bdb-abc4-3ef9e4576e52",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue EUR LYLM",
            "expression": [
              "CALCULATE (",
              "    [Total Revenue EUR],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        YEAR ( DIM_PERIOD[Billing Period Date] ) = [LY]",
              "    ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        MONTH ( DIM_PERIOD[Billing Period Date] ) = [LM]",
              "    )",
              ")"
            ],
            "displayFolder": "Total Revenue LYLM",
            "lineageTag": "39317d13-3b48-4bb8-911a-9d628f05fdf8",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Number of Shipments LYTD",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Number of Shipments] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        YEAR ( DIM_PERIOD[Billing Period Date] ) = [LY]",
              "    ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        MONTH ( DIM_PERIOD[Billing Period Date] ) <= [LM]",
              "    )",
              ")"
            ],
            "displayFolder": "Shipments",
            "lineageTag": "5cfcfa4c-4e09-4c1a-b500-c8642c840a3a",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Base Revenue EUR LYTD",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Base Revenue EUR@BER] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Year] = [LY]",
              "    ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        MONTH ( DIM_PERIOD[Billing Period Date] ) <= [LM]",
              "    )",
              ")"
            ],
            "displayFolder": "Base Revenue LYTD",
            "lineageTag": "6512a0f2-2773-4fea-b271-4cae2e79b4f2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Base Revenue USD LYTD",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Base Revenue USD@BER] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Year] = [LY]",
              "    ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        MONTH ( DIM_PERIOD[Billing Period Date] ) <= [LM]",
              "    )",
              ")"
            ],
            "displayFolder": "Base Revenue LYTD",
            "lineageTag": "4e179791-9306-4029-a3c5-ea9317b44e42",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Base Revenue LCY LYTD",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Base Revenue LCY] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Year] = [LY]",
              "    ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        MONTH ( DIM_PERIOD[Billing Period Date] ) <= [LM]",
              "    )",
              ")"
            ],
            "displayFolder": "Base Revenue LYTD",
            "lineageTag": "54f63799-e334-4dec-adfb-8afd14b078c8",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue EUR LY",
            "expression": [
              "CALCULATE (",
              "    [Total Revenue EUR],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        YEAR ( DIM_PERIOD[Billing Period Date] ) = [LY]",
              "    )",
              ")"
            ],
            "displayFolder": "Total Revenue LY",
            "lineageTag": "eca6c6d8-1b63-46fc-8c55-b7d29eb28b1e",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Billed Weight KG LYTD",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Billed Weight KG] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Year] = [LY]",
              "            && MONTH ( DIM_PERIOD[Billing Period Date] ) <= [LM]",
              "    )",
              ")"
            ],
            "displayFolder": "Weight",
            "lineageTag": "6f24bd50-1995-4ce9-930d-2e89aabc39b7",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Base Revenue EUR LY",
            "expression": [
              "CALCULATE (",
              "    [Base Revenue EUR],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        YEAR ( DIM_PERIOD[Billing Period Date] ) = [LY]",
              "    )",
              ")"
            ],
            "displayFolder": "Base Revenue LY",
            "lineageTag": "795d045e-4473-4943-bbbf-aedbad9d1d9a",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "RSW LYTD/LYLM",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Period Filter'[Period] ),",
              "    \"YTD\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "            \"Total Revenue\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\", [Total Revenue EUR LYTD],",
              "                    \"BER - USD\", [Total Revenue USD LYTD],",
              "                    \"Local Currency\", [Total Revenue LCY LYTD]",
              "                ),",
              "            \"Base Revenue\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\", [Base Revenue EUR LYTD],",
              "                    \"BER - USD\", [Base Revenue USD LYTD],",
              "                    \"Local Currency\", [Base Revenue LCY LYTD]",
              "                ),",
              "            \"Shipment\", [Number of Shipments LYTD],",
              "            \"Weight\", [Billed Weight KG LYTD]",
              "        ),",
              "    \"LM\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "            \"Total Revenue\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\", [Total Revenue EUR LYLM],",
              "                    \"BER - USD\", [Total Revenue USD LYLM],",
              "                    \"Local Currency\", [Total Revenue LCY LYLM]",
              "                ),",
              "            \"Base Revenue\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\", [Base Revenue EUR LYLM],",
              "                    \"BER - USD\", [Base Revenue USD LYLM],",
              "                    \"Local Currency\", [Base Revenue LCY LYLM]",
              "                ),",
              "            \"Shipment\", [Number of Shipments LYLM],",
              "            \"Weight\", [Billed Weight KG LYLM]",
              "        )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "RSW",
            "lineageTag": "51e0c3ef-340a-4a0d-96c0-ec4b392b87f9",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RSW YTD/LM/LYTD/LYLM YOY %",
            "expression": [
              "VAR _Growth = [RSW YTD/LM] - [RSW LYTD/LYLM]",
              "RETURN",
              "    DIVIDE (",
              "        _Growth,",
              "        [RSW LYTD/LYLM]",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "RSW",
            "lineageTag": "8d680525-ed1d-4d26-b314-75117ac04c11",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RSW YTD/LM/LYTD/LYLM Growth",
            "expression": [
              "VAR _Growth = [RSW YTD/LM] - [RSW LYTD/LYLM]",
              "RETURN",
              "    _Growth"
            ],
            "formatString": "#,0.0",
            "displayFolder": "RSW",
            "lineageTag": "b759edec-2379-4e20-802e-d9dab25c6a0e",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RPD YTD/LM",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Period Filter'[Period] ),",
              "    \"YTD\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "            \"Total Revenue\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Total Revenue EUR YTD],",
              "                            [Working Days YTD]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Total Revenue USD YTD],",
              "                            [Working Days YTD]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Total Revenue LCY YTD],",
              "                            [Working Days YTD]",
              "                        )",
              "                ),",
              "            \"Base Revenue\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Base Revenue EUR YTD],",
              "                            [Working Days YTD]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Base Revenue USD YTD],",
              "                            [Working Days YTD]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Base Revenue LCY YTD],",
              "                            [Working Days YTD]",
              "                        )",
              "                ),",
              "            \"Shipment\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Base Revenue EUR YTD],",
              "                            [Working Days YTD]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Base Revenue USD YTD],",
              "                            [Working Days YTD]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Base Revenue LCY YTD],",
              "                            [Working Days YTD]",
              "                        )",
              "                ),",
              "            \"Weight\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Base Revenue EUR YTD],",
              "                            [Working Days YTD]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Base Revenue USD YTD],",
              "                            [Working Days YTD]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Base Revenue LCY YTD],",
              "                            [Working Days YTD]",
              "                        )",
              "                )",
              "        ),",
              "    \"LM\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "            \"Total Revenue\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Total Revenue EUR LM],",
              "                            [_Working Days LM]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Total Revenue USD LM],",
              "                            [_Working Days LM]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Total Revenue LCY LM],",
              "                            [_Working Days LM]",
              "                        )",
              "                ),",
              "            \"Base Revenue\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Base Revenue EUR LM],",
              "                            [_Working Days LM]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Base Revenue USD LM],",
              "                            [_Working Days LM]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Base Revenue LCY LM],",
              "                            [_Working Days LM]",
              "                        )",
              "                ),",
              "            \"Shipment\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Base Revenue EUR LM],",
              "                            [_Working Days LM]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Base Revenue USD LM],",
              "                            [_Working Days LM]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Base Revenue LCY LM],",
              "                            [_Working Days LM]",
              "                        )",
              "                ),",
              "            \"Weight\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Base Revenue EUR LM],",
              "                            [_Working Days LM]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Base Revenue USD LM],",
              "                            [_Working Days LM]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Base Revenue LCY LM],",
              "                            [_Working Days LM]",
              "                        )",
              "                )",
              "        )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "RPD",
            "lineageTag": "10b4ddb0-6808-4552-9caa-645b15103be4",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RPD LYTD/LYLM",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Period Filter'[Period] ),",
              "    \"YTD\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "            \"Total Revenue\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Total Revenue EUR LYTD],",
              "                            [_Working Days LYTD]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Total Revenue USD LYTD],",
              "                            [_Working Days LYTD]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Total Revenue LCY LYTD],",
              "                            [_Working Days LYTD]",
              "                        )",
              "                ),",
              "            \"Base Revenue\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Base Revenue EUR LYTD],",
              "                            [_Working Days LYTD]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Base Revenue USD LYTD],",
              "                            [_Working Days LYTD]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Base Revenue LCY LYTD],",
              "                            [_Working Days LYTD]",
              "                        )",
              "                ),",
              "            \"Shipment\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Base Revenue EUR LYTD],",
              "                            [_Working Days LYTD]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Base Revenue USD LYTD],",
              "                            [_Working Days LYTD]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Base Revenue LCY LYTD],",
              "                            [_Working Days LYTD]",
              "                        )",
              "                ),",
              "            \"Weight\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Base Revenue EUR LYTD],",
              "                            [_Working Days LYTD]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Base Revenue USD LYTD],",
              "                            [_Working Days LYTD]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Base Revenue LCY LYTD],",
              "                            [_Working Days LYTD]",
              "                        )",
              "                )",
              "        ),",
              "    \"LM\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "            \"Total Revenue\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Total Revenue EUR LYLM],",
              "                            [_Working Days LYLM]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Total Revenue USD LYLM],",
              "                            [_Working Days LYLM]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Total Revenue LCY LYLM],",
              "                            [_Working Days LYLM]",
              "                        )",
              "                ),",
              "            \"Base Revenue\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Base Revenue EUR LYLM],",
              "                            [_Working Days LYLM]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Base Revenue USD LYLM],",
              "                            [_Working Days LYLM]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Base Revenue LCY LYLM],",
              "                            [_Working Days LYLM]",
              "                        )",
              "                ),",
              "            \"Shipment\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Base Revenue EUR LYLM],",
              "                            [_Working Days LYLM]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Base Revenue USD LYLM],",
              "                            [_Working Days LYLM]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Base Revenue LCY LYLM],",
              "                            [_Working Days LYLM]",
              "                        )",
              "                ),",
              "            \"Weight\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Base Revenue EUR LYLM],",
              "                            [_Working Days LYLM]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Base Revenue USD LYLM],",
              "                            [_Working Days LYLM]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Base Revenue LCY LYLM],",
              "                            [_Working Days LYLM]",
              "                        )",
              "                )",
              "        )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "RPD",
            "lineageTag": "a68e08b2-0380-42a1-a5f6-6ca7aa39aa2e",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RPD YTD/LM/LYTD/LYLM Growth",
            "expression": "[RPD YTD/LM] - [RPD LYTD/LYLM]",
            "formatString": "#,0.0",
            "displayFolder": "RPD",
            "lineageTag": "ade8556c-4ea7-4b98-962c-d9d906463290",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RPD YTD/LM/LYTD/LYLM YOY%",
            "expression": [
              "VAR _Growth = [RPD YTD/LM] - [RPD LYTD/LYLM]",
              "RETURN",
              "    DIVIDE (",
              "        _Growth,",
              "        [RPD LYTD/LYLM]",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "RPD",
            "lineageTag": "0f26d7ec-a5d0-4b36-9c76-ed3add88179a",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RPD LY",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "    \"Total Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Total Revenue EUR LY],",
              "                    [_Working Days LY]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Total Revenue USD LY],",
              "                    [_Working Days LY]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Total Revenue LCY LY],",
              "                    [_Working Days LY]",
              "                )",
              "        ),",
              "    \"Base Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Base Revenue EUR LY],",
              "                    [_Working Days LY]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Base Revenue USD LY],",
              "                    [_Working Days LY]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Base Revenue LCY LY],",
              "                    [_Working Days LY]",
              "                )",
              "        )",
              ")"
            ],
            "displayFolder": "RPD",
            "lineageTag": "4a71fd25-95c0-4bc5-9d87-b7065662e601",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "RPD YTD",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "    \"Total Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Total Revenue EUR YTD],",
              "                    [Working Days YTD]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Total Revenue USD YTD],",
              "                    [Working Days YTD]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Total Revenue LCY YTD],",
              "                    [Working Days YTD]",
              "                )",
              "        ),",
              "    \"Base Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Base Revenue EUR YTD],",
              "                    [Working Days YTD]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Base Revenue USD YTD],",
              "                    [Working Days YTD]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Base Revenue LCY YTD],",
              "                    [Working Days YTD]",
              "                )",
              "        )",
              ")"
            ],
            "displayFolder": "RPD",
            "lineageTag": "0f3c7ea7-f37b-44f6-834f-fde249f50d99",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "SPD YTD/LM",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Period Filter'[Period] ),",
              "    \"YTD\",",
              "        DIVIDE (",
              "            [Number of Shipments YTD],",
              "            [Working Days YTD]",
              "        ),",
              "    \"LM\",",
              "        DIVIDE (",
              "            [Number of Shipments LM],",
              "            [_Working Days LM]",
              "        )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "SPD",
            "lineageTag": "92dfd02a-546c-4607-9d24-bf720948d971",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "SPD LYTD/LYLM",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Period Filter'[Period] ),",
              "    \"YTD\",",
              "        DIVIDE (",
              "            [Number of Shipments LYTD],",
              "            [_Working Days LYTD]",
              "        ),",
              "    \"LM\",",
              "        DIVIDE (",
              "            [Number of Shipments LYLM],",
              "            [_Working Days LYLM]",
              "        )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "SPD",
            "lineageTag": "d0d04ccd-8545-472f-a604-455c73436ff2",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "SPD YTD/LM/LYTD/LYLM Growth",
            "expression": "[SPD YTD/LM] - [SpD LYTD/LYLM]",
            "formatString": "#,0.0",
            "displayFolder": "SPD",
            "lineageTag": "4e5e4cbb-bdd2-43b3-b982-d50ee1aeed4c",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "SPD YTD/LM/LYTD/LYLM YOY%",
            "expression": [
              "VAR _Growth = [SPD YTD/LM] - [SpD LYTD/LYLM]",
              "RETURN",
              "    DIVIDE (",
              "        _Growth,",
              "        [SpD LYTD/LYLM]",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "SPD",
            "lineageTag": "968dedb4-141f-4096-8b4c-f15507e044f4",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "SPD LY",
            "expression": [
              "DIVIDE (",
              "    [Number of Shipments LY],",
              "    [_Working Days LY]",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "SPD",
            "lineageTag": "a05633b4-8d66-4295-ad42-ee87f7e01da0",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "SPD YTD",
            "expression": [
              "DIVIDE (",
              "    [Number of Shipments YTD],",
              "    [Working Days YTD]",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "SPD",
            "lineageTag": "9248db83-e80b-466c-87fa-ad5d331e9575",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RSW LY",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "    \"Total Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\", [Total Revenue EUR LY],",
              "            \"BER - USD\", [Total Revenue USD LY],",
              "            \"Local Currency\", [Total Revenue LCY LY]",
              "        ),",
              "    \"Base Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\", [Base Revenue EUR LY],",
              "            \"BER - USD\", [Base Revenue USD LY],",
              "            \"Local Currency\", [Base Revenue LCY LY]",
              "        ),",
              "    \"Shipment\", [Number of Shipments LY],",
              "    \"Weight\", [Billed Weight KG LY]",
              ")"
            ],
            "displayFolder": "RSW",
            "lineageTag": "dcd0265d-28ea-4827-9316-c61b08d50bc1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "WPD YTD",
            "expression": [
              "DIVIDE (",
              "    [Billed Weight KG YTD],",
              "    [Working Days YTD]",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "WPD",
            "lineageTag": "78f6017e-ad0d-4e45-a354-d6a387142f03",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "WPD LY",
            "expression": [
              "DIVIDE (",
              "    [Billed Weight KG LY],",
              "    [_Working Days LY]",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "WPD",
            "lineageTag": "6f0e0856-b877-42c1-b853-d0696924fe08",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "WPD YTD/LM",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Period Filter'[Period] ),",
              "    \"YTD\",",
              "        DIVIDE (",
              "            [Billed Weight KG YTD],",
              "            [Working Days YTD]",
              "        ),",
              "    \"LM\",",
              "        DIVIDE (",
              "            [Billed Weight KG LM],",
              "            [_Working Days LM]",
              "        )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "WPD",
            "lineageTag": "0f4beafa-e4d0-4165-a7c1-9c5a3f0d425c",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "WPD LYTD/LYLM",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Period Filter'[Period] ),",
              "    \"YTD\",",
              "        DIVIDE (",
              "            [Billed Weight KG LYTD],",
              "            [_Working Days LYTD]",
              "        ),",
              "    \"LM\",",
              "        DIVIDE (",
              "            [Billed Weight KG LYLM],",
              "            [_Working Days LYLM]",
              "        )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "WPD",
            "lineageTag": "4a1eee23-4243-49b2-80e7-f95fa38e8259",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "WPD YTD/LM/LYTD/LYLM Growth",
            "expression": "[WPD YTD/LM] - [WPD LYTD/LYLM]",
            "formatString": "#,0.0",
            "displayFolder": "WPD",
            "lineageTag": "2a50cef9-f6d7-4352-9fda-7fddc493bb12",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "WPD YTD/LM/LYTD/LYLM YOY%",
            "expression": [
              "VAR _Growth = [WPD YTD/LM] - [WPD LYTD/LYLM]",
              "RETURN",
              "    DIVIDE (",
              "        _Growth,",
              "        [WPD LYTD/LYLM]",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "WPD",
            "lineageTag": "06287c89-c8dc-4572-8dfd-6d391fadeb08",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RPK YTD",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "    \"Total Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Total Revenue EUR YTD],",
              "                    [Billed Weight KG YTD]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Total Revenue USD YTD],",
              "                    [Billed Weight KG YTD]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Total Revenue LCY YTD],",
              "                    [Billed Weight KG YTD]",
              "                )",
              "        ),",
              "    \"Base Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Base Revenue EUR YTD],",
              "                    [Billed Weight KG YTD]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Base Revenue USD YTD],",
              "                    [Billed Weight KG YTD]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Base Revenue LCY YTD],",
              "                    [Billed Weight KG YTD]",
              "                )",
              "        )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "RPK",
            "lineageTag": "4888cc50-995b-47e7-9986-452247b9d272",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RPK LY",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "    \"Total Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Total Revenue EUR LY],",
              "                    [Billed Weight KG LY]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Total Revenue USD LY],",
              "                    [Billed Weight KG LY]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Total Revenue LCY LY],",
              "                    [Billed Weight KG LY]",
              "                )",
              "        ),",
              "    \"Base Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Base Revenue EUR LY],",
              "                    [Billed Weight KG LY]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Base Revenue USD LY],",
              "                    [Billed Weight KG LY]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Base Revenue LCY LY],",
              "                    [Billed Weight KG LY]",
              "                )",
              "        )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "RPK",
            "lineageTag": "42005687-199d-443d-9ecf-a789624ffe6e",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RPS LYTD/LYLM",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Period Filter'[Period] ),",
              "    \"YTD\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "            \"Total Revenue\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Total Revenue EUR LYTD],",
              "                            [Number of Shipments LYTD]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Total Revenue USD LYTD],",
              "                            [Number of Shipments LYTD]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Total Revenue LCY LYTD],",
              "                            [Number of Shipments LYTD]",
              "                        )",
              "                ),",
              "            \"Base Revenue\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Base Revenue EUR LYTD],",
              "                            [Number of Shipments LYTD]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Base Revenue USD LYTD],",
              "                            [Number of Shipments LYTD]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Base Revenue LCY LYTD],",
              "                            [Number of Shipments LYTD]",
              "                        )",
              "                ),",
              "            \"Shipment\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Base Revenue EUR LYTD],",
              "                            [Number of Shipments LYTD]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Base Revenue USD LYTD],",
              "                            [Number of Shipments LYTD]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Base Revenue LCY LYTD],",
              "                            [Number of Shipments LYTD]",
              "                        )",
              "                ),",
              "            \"Weight\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Base Revenue EUR LYTD],",
              "                            [Number of Shipments LYTD]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Base Revenue USD LYTD],",
              "                            [Number of Shipments LYTD]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Base Revenue LCY LYTD],",
              "                            [Number of Shipments LYTD]",
              "                        )",
              "                )",
              "        ),",
              "    \"LM\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "            \"Total Revenue\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Total Revenue EUR LYLM],",
              "                            [Number of Shipments LYLM]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Total Revenue USD LYLM],",
              "                            [Number of Shipments LYLM]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Total Revenue LCY LYLM],",
              "                            [Number of Shipments LYLM]",
              "                        )",
              "                ),",
              "            \"Base Revenue\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Base Revenue EUR LYLM],",
              "                            [Number of Shipments LYLM]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Base Revenue USD LYLM],",
              "                            [Number of Shipments LYLM]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Base Revenue LCY LYLM],",
              "                            [Number of Shipments LYLM]",
              "                        )",
              "                ),",
              "            \"Shipment\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Base Revenue EUR LYLM],",
              "                            [Number of Shipments LYLM]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Base Revenue USD LYLM],",
              "                            [Number of Shipments LYLM]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Base Revenue LCY LYLM],",
              "                            [Number of Shipments LYLM]",
              "                        )",
              "                ),",
              "            \"Weight\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Base Revenue EUR LYLM],",
              "                            [Number of Shipments LYLM]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Base Revenue USD LYLM],",
              "                            [Number of Shipments LYLM]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Base Revenue LCY LYLM],",
              "                            [Number of Shipments LYLM]",
              "                        )",
              "                )",
              "        )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "RPS",
            "lineageTag": "1fec3773-ba4c-4368-9eb4-24f207f4b00c",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RPK LYTD/LYLM",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Period Filter'[Period] ),",
              "    \"YTD\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "            \"Total Revenue\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Total Revenue EUR LYTD],",
              "                            [Billed Weight KG LYTD]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Total Revenue USD LYTD],",
              "                            [Billed Weight KG LYTD]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Total Revenue LCY LYTD],",
              "                            [Billed Weight KG LYTD]",
              "                        )",
              "                ),",
              "            \"Base Revenue\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Base Revenue EUR LYTD],",
              "                            [Billed Weight KG LYTD]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Base Revenue USD LYTD],",
              "                            [Billed Weight KG LYTD]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Base Revenue LCY LYTD],",
              "                            [Billed Weight KG LYTD]",
              "                        )",
              "                ),",
              "            \"Shipment\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Base Revenue EUR LYTD],",
              "                            [Billed Weight KG LYTD]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Base Revenue USD LYTD],",
              "                            [Billed Weight KG LYTD]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Base Revenue LCY LYTD],",
              "                            [Billed Weight KG LYTD]",
              "                        )",
              "                ),",
              "            \"Weight\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Base Revenue EUR LYTD],",
              "                            [Billed Weight KG LYTD]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Base Revenue USD LYTD],",
              "                            [Billed Weight KG LYTD]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Base Revenue LCY LYTD],",
              "                            [Billed Weight KG LYTD]",
              "                        )",
              "                )",
              "        ),",
              "    \"LM\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "            \"Total Revenue\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Total Revenue EUR LYLM],",
              "                            [Billed Weight KG LYLM]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Total Revenue USD LYLM],",
              "                            [Billed Weight KG LYLM]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Total Revenue LCY LYLM],",
              "                            [Billed Weight KG LYLM]",
              "                        )",
              "                ),",
              "            \"Base Revenue\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Base Revenue EUR LYLM],",
              "                            [Billed Weight KG LYLM]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Base Revenue USD LYLM],",
              "                            [Billed Weight KG LYLM]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Base Revenue LCY LYLM],",
              "                            [Billed Weight KG LYLM]",
              "                        )",
              "                ),",
              "            \"Shipment\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Base Revenue EUR LYLM],",
              "                            [Billed Weight KG LYLM]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Base Revenue USD LYLM],",
              "                            [Billed Weight KG LYLM]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Base Revenue LCY LYLM],",
              "                            [Billed Weight KG LYLM]",
              "                        )",
              "                ),",
              "            \"Weight\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Base Revenue EUR LYLM],",
              "                            [Billed Weight KG LYLM]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Base Revenue USD LYLM],",
              "                            [Billed Weight KG LYLM]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Base Revenue LCY LYLM],",
              "                            [Billed Weight KG LYLM]",
              "                        )",
              "                )",
              "        )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "RPK",
            "lineageTag": "859ec9ed-195e-450b-9a5b-8fe678d0e676",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RPK YTD/LM/LYTD/LYLM Growth",
            "expression": "[RPK YTD/LM] - [RPK LYTD/LYLM]",
            "formatString": "#,0.0",
            "displayFolder": "RPK",
            "lineageTag": "16249d5b-64c5-4643-8490-af9e35b558eb",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RPK YTD/LM/LYTD/LYLM YOY%",
            "expression": [
              "VAR _Growth = [RPK YTD/LM] - [RPK LYTD/LYLM]",
              "RETURN",
              "    DIVIDE (",
              "        _Growth,",
              "        [RPK LYTD/LYLM]",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "RPK",
            "lineageTag": "9898a676-e4a0-4e1f-917a-ea7a920e6d73",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RPS YTD",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "    \"Total Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Total Revenue EUR YTD],",
              "                    [Number of Shipments YTD]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Total Revenue USD YTD],",
              "                    [Number of Shipments YTD]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Total Revenue LCY YTD],",
              "                    [Number of Shipments YTD]",
              "                )",
              "        ),",
              "    \"Base Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Base Revenue EUR YTD],",
              "                    [Number of Shipments YTD]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Base Revenue USD YTD],",
              "                    [Number of Shipments YTD]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Base Revenue LCY YTD],",
              "                    [Number of Shipments YTD]",
              "                )",
              "        )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "RPS",
            "lineageTag": "28eb7e4b-fc53-4c6c-bbb2-12333a167b14",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RPS LY",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "    \"Total Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Total Revenue EUR LY],",
              "                    [Number of Shipments LY]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Total Revenue USD LY],",
              "                    [Number of Shipments LY]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Total Revenue LCY LY],",
              "                    [Number of Shipments LY]",
              "                )",
              "        ),",
              "    \"Base Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Base Revenue EUR LY],",
              "                    [Number of Shipments LY]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Base Revenue USD LY],",
              "                    [Number of Shipments LY]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Base Revenue LCY LY],",
              "                    [Number of Shipments LY]",
              "                )",
              "        )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "RPS",
            "lineageTag": "4f490b7c-13b6-4281-babb-4c910566b65b",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RPS YTD/LM",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Period Filter'[Period] ),",
              "    \"YTD\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "            \"Total Revenue\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Total Revenue EUR YTD],",
              "                            [Number of Shipments YTD]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Total Revenue USD YTD],",
              "                            [Number of Shipments YTD]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Total Revenue LCY YTD],",
              "                            [Number of Shipments YTD]",
              "                        )",
              "                ),",
              "            \"Base Revenue\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Base Revenue EUR YTD],",
              "                            [Number of Shipments YTD]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Base Revenue USD YTD],",
              "                            [Number of Shipments YTD]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Base Revenue LCY YTD],",
              "                            [Number of Shipments YTD]",
              "                        )",
              "                ),",
              "            \"Shipment\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Base Revenue EUR YTD],",
              "                            [Number of Shipments YTD]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Base Revenue USD YTD],",
              "                            [Number of Shipments YTD]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Base Revenue LCY YTD],",
              "                            [Number of Shipments YTD]",
              "                        )",
              "                ),",
              "            \"Weight\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Base Revenue EUR YTD],",
              "                            [Number of Shipments YTD]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Base Revenue USD YTD],",
              "                            [Number of Shipments YTD]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Base Revenue LCY YTD],",
              "                            [Number of Shipments YTD]",
              "                        )",
              "                )",
              "        ),",
              "    \"LM\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "            \"Total Revenue\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Total Revenue EUR LM],",
              "                            [Number of Shipments LM]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Total Revenue USD LM],",
              "                            [Number of Shipments LM]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Total Revenue LCY LM],",
              "                            [Number of Shipments LM]",
              "                        )",
              "                ),",
              "            \"Base Revenue\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Base Revenue EUR LM],",
              "                            [Number of Shipments LM]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Base Revenue USD LM],",
              "                            [Number of Shipments LM]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Base Revenue LCY LM],",
              "                            [Number of Shipments LM]",
              "                        )",
              "                ),",
              "            \"Shipment\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Base Revenue EUR LM],",
              "                            [Number of Shipments LM]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Base Revenue USD LM],",
              "                            [Number of Shipments LM]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Base Revenue LCY LM],",
              "                            [Number of Shipments LM]",
              "                        )",
              "                ),",
              "            \"Weight\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Base Revenue EUR LM],",
              "                            [Number of Shipments LM]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Base Revenue USD LM],",
              "                            [Number of Shipments LM]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Base Revenue LCY LM],",
              "                            [Number of Shipments LM]",
              "                        )",
              "                )",
              "        )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "RPS",
            "lineageTag": "d6937aa6-3af6-40d6-8c08-f3c84bb58f70",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RPS YTD/LM/LYTD/LYLM Growth",
            "expression": "[RPS YTD/LM] - [RPS LYTD/LYLM]",
            "formatString": "#,0.0",
            "displayFolder": "RPS",
            "lineageTag": "21f8c4a0-142c-4280-b461-9851134bcff4",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RPK YTD/LM",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Period Filter'[Period] ),",
              "    \"YTD\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "            \"Total Revenue\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Total Revenue EUR YTD],",
              "                            [Billed Weight KG YTD]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Total Revenue USD YTD],",
              "                            [Billed Weight KG YTD]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Total Revenue LCY YTD],",
              "                            [Billed Weight KG YTD]",
              "                        )",
              "                ),",
              "            \"Base Revenue\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Base Revenue EUR YTD],",
              "                            [Billed Weight KG YTD]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Base Revenue USD YTD],",
              "                            [Billed Weight KG YTD]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Base Revenue LCY YTD],",
              "                            [Billed Weight KG YTD]",
              "                        )",
              "                ),",
              "            \"Shipment\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Base Revenue EUR YTD],",
              "                            [Billed Weight KG YTD]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Base Revenue USD YTD],",
              "                            [Billed Weight KG YTD]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Base Revenue LCY YTD],",
              "                            [Billed Weight KG YTD]",
              "                        )",
              "                ),",
              "            \"Weight\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Base Revenue EUR YTD],",
              "                            [Billed Weight KG YTD]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Base Revenue USD YTD],",
              "                            [Billed Weight KG YTD]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Base Revenue LCY YTD],",
              "                            [Billed Weight KG YTD]",
              "                        )",
              "                )",
              "        ),",
              "    \"LM\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "            \"Total Revenue\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Total Revenue EUR LM],",
              "                            [Billed Weight KG LM]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Total Revenue USD LM],",
              "                            [Billed Weight KG LM]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Total Revenue LCY LM],",
              "                            [Billed Weight KG LM]",
              "                        )",
              "                ),",
              "            \"Base Revenue\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Base Revenue EUR LM],",
              "                            [Billed Weight KG LM]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Base Revenue USD LM],",
              "                            [Billed Weight KG LM]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Base Revenue LCY LM],",
              "                            [Billed Weight KG LM]",
              "                        )",
              "                ),",
              "            \"Shipment\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Base Revenue EUR LM],",
              "                            [Billed Weight KG LM]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Base Revenue USD LM],",
              "                            [Billed Weight KG LM]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Base Revenue LCY LM],",
              "                            [Billed Weight KG LM]",
              "                        )",
              "                ),",
              "            \"Weight\",",
              "                SWITCH (",
              "                    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "                    \"BER - Euro\",",
              "                        DIVIDE (",
              "                            [Base Revenue EUR LM],",
              "                            [Billed Weight KG LM]",
              "                        ),",
              "                    \"BER - USD\",",
              "                        DIVIDE (",
              "                            [Base Revenue USD LM],",
              "                            [Billed Weight KG LM]",
              "                        ),",
              "                    \"Local Currency\",",
              "                        DIVIDE (",
              "                            [Base Revenue LCY LM],",
              "                            [Billed Weight KG LM]",
              "                        )",
              "                )",
              "        )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "RPK",
            "lineageTag": "614f7415-c13d-4ba2-ad1c-71de29e7807e"
          },
          {
            "name": "RPS YTD/LM/LYTD/LYLM YOY%",
            "expression": [
              "VAR _Growth = [RPS YTD/LM] - [RPS LYTD/LYLM]",
              "RETURN",
              "    DIVIDE (",
              "        _Growth,",
              "        [RPS LYTD/LYLM]",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "RPS",
            "lineageTag": "a1ba8e0c-ecfc-4ad2-948a-491f47d2c000",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "WPS YTD",
            "expression": [
              "DIVIDE (",
              "    [Billed Weight KG YTD],",
              "    [Number of Shipments YTD]",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "WPS",
            "lineageTag": "41e4e4ec-0410-48ce-906a-6a03575830ec",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "WPS LY",
            "expression": [
              "DIVIDE (",
              "    [Billed Weight KG LY],",
              "    [Number of Shipments LY]",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "WPS",
            "lineageTag": "a4e9e8a5-9e53-4f1f-9996-6fd853e816fe",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "WPS YTD/LM",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Period Filter'[Period] ),",
              "    \"YTD\",",
              "        DIVIDE (",
              "            [Billed Weight KG YTD],",
              "            [Number of Shipments YTD]",
              "        ),",
              "    \"LM\",",
              "        DIVIDE (",
              "            [Billed Weight KG LM],",
              "            [Number of Shipments LM]",
              "        )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "WPS",
            "lineageTag": "81b95b19-b7df-4d4e-8032-73c40f8da3b9",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "WPS LYTD/LYLM",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Period Filter'[Period] ),",
              "    \"YTD\",",
              "        DIVIDE (",
              "            [Billed Weight KG LYTD],",
              "            [Number of Shipments LYTD]",
              "        ),",
              "    \"LM\",",
              "        DIVIDE (",
              "            [Billed Weight KG LYLM],",
              "            [Number of Shipments LYLM]",
              "        )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "WPS",
            "lineageTag": "24480fce-8910-45a7-8d1f-0d6081e822cc",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "WPS YTD/LM/LYTD/LYLM Growth",
            "expression": "[WPS YTD/LM] - [WPS LYTD/LYLM]",
            "formatString": "#,0.0",
            "displayFolder": "WPS",
            "lineageTag": "bf963280-004e-46c9-827b-e83242832038",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "WPS YTD/LM/LYTD/LYLM YOY%",
            "expression": [
              "VAR _Growth = [WPS YTD/LM] - [WPS LYTD/LYLM]",
              "RETURN",
              "    DIVIDE (",
              "        _Growth,",
              "        [WPS LYTD/LYLM]",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "WPS",
            "lineageTag": "476becbc-be75-432b-997e-17ebfe804e58",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RPD YTD/LM Z",
            "expression": [
              "IF (",
              "    ISBLANK ( [RPD YTD/LM] ),",
              "    0,",
              "    [RPD YTD/LM]",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "RPD",
            "lineageTag": "73302ccf-f94f-4c8e-9bca-bf96fb17c1ca",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RPD YTD/LM/LYTD/LYLM YOY% Z",
            "expression": [
              "IF (",
              "    ISBLANK ( [RPD YTD/LM/LYTD/LYLM YOY%] ),",
              "    0,",
              "    [RPD YTD/LM/LYTD/LYLM YOY%]",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "RPD",
            "lineageTag": "62be5cea-fdaa-4739-9120-d74961ef27a0",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Billed Weight KG L13",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Billed Weight KG] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 14",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                <= EOMONTH (",
              "                    [Today],",
              "                    -1",
              "                )",
              "    )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Weight",
            "lineageTag": "19ea9873-fb52-4fde-af8a-fef3bc38de54",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "SPD YTD/LM Z",
            "expression": [
              "IF (",
              "    ISBLANK ( [SPD YTD/LM] ),",
              "    0,",
              "    [SPD YTD/LM]",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "SPD",
            "lineageTag": "72182b70-67e0-47f7-b925-bcb6bf3b1e4b",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "SPD YTD/LM/LYTD/LYLM YOY% Z",
            "expression": [
              "IF (",
              "    ISBLANK ( [SPD YTD/LM/LYTD/LYLM YOY%] ),",
              "    0,",
              "    [SPD YTD/LM/LYTD/LYLM YOY%]",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "SPD",
            "lineageTag": "341640ae-3879-4764-a3aa-113e28870494",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "WPD YTD/LM Z",
            "expression": [
              "IF (",
              "    ISBLANK ( [WPD YTD/LM] ),",
              "    0,",
              "    [WPD YTD/LM]",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "WPD",
            "lineageTag": "a36bf7b5-1390-46e6-83db-275535193f5c",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "WPD YTD/LM/LYTD/LYLM YOY% Z",
            "expression": [
              "IF (",
              "    ISBLANK ( [WPD YTD/LM/LYTD/LYLM YOY%] ),",
              "    0,",
              "    [WPD YTD/LM/LYTD/LYLM YOY%]",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "WPD",
            "lineageTag": "b970b5be-486b-4c5d-8509-7fed98369ce7",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RPK YTD/LM Z",
            "expression": [
              "IF (",
              "    ISBLANK ( [RPK YTD/LM] ),",
              "    0,",
              "    [RPK YTD/LM]",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "RPK",
            "lineageTag": "8cb445cd-8c49-417f-b9d3-8fd36e61fa63",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RPK YTD/LM/LYTD/LYLM YOY% Z",
            "expression": [
              "IF (",
              "    ISBLANK ( [RPK YTD/LM/LYTD/LYLM YOY%] ),",
              "    0,",
              "    [RPK YTD/LM/LYTD/LYLM YOY%]",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "RPK",
            "lineageTag": "aafec3e5-6aa4-4ef2-9576-54769c67c4ca",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RPS YTD/LM Z",
            "expression": [
              "IF (",
              "    ISBLANK ( [RPS YTD/LM] ),",
              "    0,",
              "    [RPS YTD/LM]",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "RPS",
            "lineageTag": "cb57ea7b-4cb3-4a80-a0df-88604e13dfb5",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RPS YTD/LM/LYTD/LYLM YOY% Z",
            "expression": [
              "IF (",
              "    ISBLANK ( [RPS YTD/LM/LYTD/LYLM YOY%] ),",
              "    0,",
              "    [RPS YTD/LM/LYTD/LYLM YOY%]",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "RPS",
            "lineageTag": "c0dc1948-25de-43d1-b6e6-829610a13aca",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "WPS YTD/LM Z",
            "expression": [
              "IF (",
              "    ISBLANK ( [WPS YTD/LM] ),",
              "    0,",
              "    [WPS YTD/LM]",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "WPS",
            "lineageTag": "43b60f10-59f2-4e40-aa6d-7f1283c41c48",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "WPS YTD/LM/LYTD/LYLM YOY% Z",
            "expression": [
              "IF (",
              "    ISBLANK ( [WPS YTD/LM/LYTD/LYLM YOY%] ),",
              "    0,",
              "    [WPS YTD/LM/LYTD/LYLM YOY%]",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "WPS",
            "lineageTag": "4a48827f-1441-4e66-9775-fdc6e5d0aa32",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RSW YTD/LM Z",
            "expression": [
              "IF (",
              "    ISBLANK ( [RSW YTD/LM] ),",
              "    0,",
              "    [RSW YTD/LM]",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "RSW",
            "lineageTag": "21a8d0bb-dd96-43a7-961d-525cd297b382",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RSW LYTD/LYLM Z",
            "expression": [
              "IF (",
              "    ISBLANK ( [RSW LYTD/LYLM] ),",
              "    0,",
              "    [RSW LYTD/LYLM]",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "RSW",
            "lineageTag": "34888647-a8eb-4d0d-98c8-c61875583de0",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RSW YTD/LM/LYTD/LYLM YOY % Z",
            "expression": [
              "IF (",
              "    ISBLANK ( [RSW YTD/LM/LYTD/LYLM YOY %] ),",
              "    0,",
              "    [RSW YTD/LM/LYTD/LYLM YOY %]",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "RSW",
            "lineageTag": "347d3940-6f5d-47ad-a22e-81ff3f59951a",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Total Revenue EUR L13",
            "expression": [
              "CALCULATE (",
              "    [Total Revenue EUR],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 14",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                <= EOMONTH (",
              "                    [Today],",
              "                    -1",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Total Revenue L13",
            "lineageTag": "fe484081-11f6-46ba-a0c4-ed91635ef7ab",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue USD L13",
            "expression": [
              "CALCULATE (",
              "    [Total Revenue USD],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 14",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                <= EOMONTH (",
              "                    [Today],",
              "                    -1",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Total Revenue L13",
            "lineageTag": "62519cea-6416-4e99-baf6-a4098bc4d5c1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue LCY L13",
            "expression": [
              "CALCULATE (",
              "    [Total Revenue LCY],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 14",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                <= EOMONTH (",
              "                    [Today],",
              "                    -1",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Total Revenue L13",
            "lineageTag": "792e8504-13f6-4df3-b851-52f7391e29c3",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Base Revenue LCY L13",
            "expression": [
              "CALCULATE (",
              "    [Base Revenue LCY],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 14",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                <= EOMONTH (",
              "                    [Today],",
              "                    -1",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Base Revenue L13",
            "lineageTag": "d1dcca3a-f4bb-4824-baa5-fae52efad4fa",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Base Revenue USD L13",
            "expression": [
              "CALCULATE (",
              "    [Base Revenue USD],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 14",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                <= EOMONTH (",
              "                    [Today],",
              "                    -1",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Base Revenue L13",
            "lineageTag": "d0a9d01d-3483-4d23-8ed7-1c122ec3e504",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Base Revenue EUR L13",
            "expression": [
              "CALCULATE (",
              "    [Base Revenue EUR],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 14",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                <= EOMONTH (",
              "                    [Today],",
              "                    -1",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Base Revenue L13",
            "lineageTag": "d9f97be4-2c2f-4f40-a919-96d1d62a39c2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Number of Shipments L13",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Number of Shipments] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 14",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                <= EOMONTH (",
              "                    [Today],",
              "                    -1",
              "                )",
              "    )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Shipments",
            "lineageTag": "ada68f84-61c9-41c6-8a63-d79aa2f4dc08",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RSW LYTD",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "    \"Total Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\", [Total Revenue EUR LYTD],",
              "            \"BER - USD\", [Total Revenue USD LYTD],",
              "            \"Local Currency\", [Total Revenue LCY LYTD]",
              "        ),",
              "    \"Base Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\", [Base Revenue EUR LYTD],",
              "            \"BER - USD\", [Base Revenue USD LYTD],",
              "            \"Local Currency\", [Base Revenue LCY LYTD]",
              "        ),",
              "    \"Shipment\", [Number of Shipments LYTD],",
              "    \"Weight\", [Billed Weight KG LYTD]",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "RSW",
            "lineageTag": "bdbc4096-dfbe-4899-8d2b-f977cc1c1cb0",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Number of Shipments YTD/LM",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Period Filter'[Period] ),",
              "    \"YTD\", [Number of Shipments YTD],",
              "    \"LM\", [Number of Shipments LM]",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Shipments",
            "lineageTag": "8074a7a6-c93a-4a95-a82e-ca8a1712f78a",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Number of Shipments LYTD/LYLM",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Period Filter'[Period] ),",
              "    \"YTD\", [Number of Shipments LYTD],",
              "    \"LM\", [Number of Shipments LYLM]",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Shipments",
            "lineageTag": "56bad4be-6a34-4a50-84a6-fd04cc701e4c",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Number of Shipments YTD/LM/LYTD/LYLM",
            "expression": [
              "VAR _Growth = [Number of Shipments YTD/LM] - [Number of Shipments LYTD/LYLM]",
              "RETURN",
              "    DIVIDE (",
              "        _Growth,",
              "        [Number of Shipments LYTD/LYLM]",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "Shipments",
            "lineageTag": "a84cc93c-09a5-4dcc-aad8-ee0e546679da",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Billed Weight KG YTD/LM",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Period Filter'[Period] ),",
              "    \"YTD\", [Billed Weight KG YTD],",
              "    \"LM\", [Billed Weight KG LM]",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Weight",
            "lineageTag": "9966a37d-887c-4711-bee6-73880ebffcb9",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Billed Weight KG LYTD/LYLM",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Period Filter'[Period] ),",
              "    \"YTD\", [Billed Weight KG LYTD],",
              "    \"LM\", [Billed Weight KG LYLM]",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Weight",
            "lineageTag": "c92fcb99-f041-4152-91e1-a5776c3c2706",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Billed Weight KG YTD/LM/LYTD/LYLM YOY%",
            "expression": [
              "VAR _Growth = [Billed Weight KG YTD/LM] - [Billed Weight KG LYTD/LYLM]",
              "RETURN",
              "    DIVIDE (",
              "        _Growth,",
              "        [Billed Weight KG LYTD/LYLM]",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "Weight",
            "lineageTag": "afac4ac5-529b-441b-9016-11fdb70856fe",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RSW YTD/LYTD Growth",
            "expression": "[RSW YTD] - [RSW LYTD]",
            "formatString": "#,0.0",
            "displayFolder": "RSW",
            "lineageTag": "19679c70-ed6d-46cb-90f2-d84b857142d8",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RSW YTD/LYTD YOY %",
            "expression": [
              "VAR _Growth = [RSW YTD] - [RSW LYTD]",
              "RETURN",
              "    DIVIDE (",
              "        _Growth,",
              "        [RSW LYTD]",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "RSW",
            "lineageTag": "992d528d-aa8c-4a57-b6cb-a721ffd3b738",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Total Revenue EUR LM-1",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Total Revenue EUR@BER] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 3",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                < EOMONTH (",
              "                    [Today],",
              "                    -2",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Total Revenue Month 1-5",
            "lineageTag": "4c1c5e3c-b5dc-438c-873c-66a29dcea947",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue EUR LM-2",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Total Revenue EUR@BER] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 4",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                < EOMONTH (",
              "                    [Today],",
              "                    -3",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Total Revenue Month 1-5",
            "lineageTag": "e4fcb77f-63f4-4ede-b26a-d78df499402a",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue EUR LM-3",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Total Revenue EUR@BER] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 5",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                < EOMONTH (",
              "                    [Today],",
              "                    -4",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Total Revenue Month 1-5",
            "lineageTag": "c155d19d-e565-4643-b95f-1842c6ac98ec",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue EUR LM-4",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Total Revenue EUR@BER] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 6",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                < EOMONTH (",
              "                    [Today],",
              "                    -5",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Total Revenue Month 1-5",
            "lineageTag": "f539acbf-679b-486d-be07-b497ff44d742",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue EUR LM-5",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Total Revenue EUR@BER] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 7",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                < EOMONTH (",
              "                    [Today],",
              "                    -6",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Total Revenue Month 1-5",
            "lineageTag": "b1fadc3e-3428-49ed-8340-a928f6f78e44",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue USD LM-1",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Total Revenue USD@BER] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 3",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                < EOMONTH (",
              "                    [Today],",
              "                    -2",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Total Revenue Month 1-5",
            "lineageTag": "4724f75d-b73d-4eda-932c-3bd6f6aea695",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue USD LM-2",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Total Revenue USD@BER] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 4",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                < EOMONTH (",
              "                    [Today],",
              "                    -3",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Total Revenue Month 1-5",
            "lineageTag": "b9b9e2df-9814-451c-a0f1-2bb557aedbdb",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue USD LM-3",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Total Revenue USD@BER] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 5",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                < EOMONTH (",
              "                    [Today],",
              "                    -4",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Total Revenue Month 1-5",
            "lineageTag": "96f6e99f-b4fb-471c-a42f-e17ddb98f585",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue USD LM-4",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Total Revenue USD@BER] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 6",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                < EOMONTH (",
              "                    [Today],",
              "                    -5",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Total Revenue Month 1-5",
            "lineageTag": "74339e83-61ab-48e0-a27a-e769fbc394a9",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue USD LM-5",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Total Revenue USD@BER] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 7",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                < EOMONTH (",
              "                    [Today],",
              "                    -6",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Total Revenue Month 1-5",
            "lineageTag": "8fc18ecc-943d-49e2-bb46-919d11956206",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue LCY LM-1",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Total Revenue LCY] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 3",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                < EOMONTH (",
              "                    [Today],",
              "                    -2",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Total Revenue Month 1-5",
            "lineageTag": "fb11737c-0f97-4826-91a5-120e8ba2e4c1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue LCY LM-2",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Total Revenue LCY] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 4",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                < EOMONTH (",
              "                    [Today],",
              "                    -3",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Total Revenue Month 1-5",
            "lineageTag": "13196064-504a-493a-93e3-7ab666f6fb19",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue LCY LM-3",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Total Revenue LCY] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 5",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                < EOMONTH (",
              "                    [Today],",
              "                    -4",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Total Revenue Month 1-5",
            "lineageTag": "4f7d932e-c0a9-4bd8-80c1-470d7c330b5c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue LCY LM-4",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Total Revenue LCY] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 6",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                < EOMONTH (",
              "                    [Today],",
              "                    -5",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Total Revenue Month 1-5",
            "lineageTag": "ddb36430-b3de-426d-a4a8-611fb38c9522",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue LCY LM-5",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Total Revenue LCY] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 7",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                < EOMONTH (",
              "                    [Today],",
              "                    - 6",
              "                )",
              "    )",
              ")"
            ],
            "displayFolder": "Total Revenue Month 1-5",
            "lineageTag": "c0f2dd6e-a828-4865-8de8-968d24ef3d2e",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "RM-1",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "    \"Total Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\", [Total Revenue EUR LM-1],",
              "            \"BER - USD\", [Total Revenue USD LM-1],",
              "            \"Local Currency\", [Total Revenue LCY LM-1]",
              "        ),",
              "    \"Base Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\", [Base Revenue EUR LM-1],",
              "            \"BER - USD\", [Base Revenue USD LM-1],",
              "            \"Local Currency\", [Base Revenue LCY LM-1]",
              "        ),",
              "    \"Shipment\", [Number of Shipments LM-1],",
              "    \"Weight\", [Billed Weight KG LM-1]",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "B2B/B2C RM 0 - 5",
            "lineageTag": "c4276e94-8e1a-4012-ae11-43e76a42423e",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RM-2",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "    \"Total Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\", [Total Revenue EUR LM-2],",
              "            \"BER - USD\", [Total Revenue USD LM-2],",
              "            \"Local Currency\", [Total Revenue LCY LM-2]",
              "        ),",
              "    \"Base Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\", [Base Revenue EUR LM-2],",
              "            \"BER - USD\", [Base Revenue USD LM-2],",
              "            \"Local Currency\", [Base Revenue LCY LM-2]",
              "        ),",
              "    \"Shipment\", [Number of Shipments LM-2],",
              "    \"Weight\", [Billed Weight KG LM-2]",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "B2B/B2C RM 0 - 5",
            "lineageTag": "3a31f7de-5651-4430-ad7f-4c6a94c81cfc",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RM-3",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "    \"Total Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\", [Total Revenue EUR LM-3],",
              "            \"BER - USD\", [Total Revenue USD LM-3],",
              "            \"Local Currency\", [Total Revenue LCY LM-3]",
              "        ),",
              "    \"Base Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\", [Base Revenue EUR LM-3],",
              "            \"BER - USD\", [Base Revenue USD LM-3],",
              "            \"Local Currency\", [Base Revenue LCY LM-3]",
              "        ),",
              "    \"Shipment\", [Number of Shipments LM-3],",
              "    \"Weight\", [Billed Weight KG LM-3]",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "B2B/B2C RM 0 - 5",
            "lineageTag": "869c56ad-5a4f-40f7-80a0-a272bf7b23f0",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RM-4",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "    \"Total Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\", [Total Revenue EUR LM-4],",
              "            \"BER - USD\", [Total Revenue USD LM-4],",
              "            \"Local Currency\", [Total Revenue LCY LM-4]",
              "        ),",
              "    \"Base Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\", [Base Revenue EUR LM-4],",
              "            \"BER - USD\", [Base Revenue USD LM-4],",
              "            \"Local Currency\", [Base Revenue LCY LM-4]",
              "        ),",
              "    \"Shipment\", [Number of Shipments LM-4],",
              "    \"Weight\", [Billed Weight KG LM-4]",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "B2B/B2C RM 0 - 5",
            "lineageTag": "a4f71d80-1ebc-46bc-bdb5-cede75119da4",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RM-5",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "    \"Total Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\", [Total Revenue EUR LM-5],",
              "            \"BER - USD\", [Total Revenue USD LM-5],",
              "            \"Local Currency\", [Total Revenue LCY LM-5]",
              "        ),",
              "    \"Base Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\", [Base Revenue EUR LM-5],",
              "            \"BER - USD\", [Base Revenue USD LM-5],",
              "            \"Local Currency\", [Base Revenue LCY LM-5]",
              "        ),",
              "    \"Shipment\", [Number of Shipments LM-5],",
              "    \"Weight\", [Billed Weight KG LM-5]",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "B2B/B2C RM 0 - 5",
            "lineageTag": "dd9ff185-81f7-43e1-abff-5a9f28199d4a",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RM",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "    \"Total Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\", [Total Revenue EUR LM],",
              "            \"BER - USD\", [Total Revenue USD LM],",
              "            \"Local Currency\", [Total Revenue LCY LM]",
              "        ),",
              "    \"Base Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\", [Base Revenue EUR LM],",
              "            \"BER - USD\", [Base Revenue USD LM],",
              "            \"Local Currency\", [Base Revenue LCY LM]",
              "        ),",
              "    \"Shipment\", [Number of Shipments LM],",
              "    \"Weight\", [Billed Weight KG LM]",
              ")"
            ],
            "displayFolder": "B2B/B2C RM 0 - 5",
            "lineageTag": "be4497a0-7d59-4707-891b-4b4e408526f9",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "RSW YTD/LM/LYTD/LYLM YOY % ZC",
            "expression": [
              "IF (",
              "    ISBLANK ( [RSW YTD/LM/LYTD/LYLM YOY %] ),",
              "    0,",
              "    [RSW YTD/LM/LYTD/LYLM YOY %]",
              ")"
            ],
            "displayFolder": "RSW",
            "lineageTag": "36d46eec-d7d6-4b2d-8940-cf09abe6c324",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Revenue Filter",
        "lineageTag": "9798db93-d35f-44e3-a9b7-3b933ed2cf65",
        "columns": [
          {
            "name": "Filter",
            "dataType": "string",
            "sourceColumn": "Filter",
            "sortByColumn": "Value",
            "lineageTag": "92ded6bf-e5e0-4ca4-8c32-39983c3f4d40",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "SortByColumn"
              },
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Value",
            "dataType": "int64",
            "sourceColumn": "Value",
            "formatString": "0",
            "lineageTag": "11bf871b-7159-4404-8ef1-e384d1f16376",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Revenue Filter-0494de6e-9fee-44ff-8555-075a882ece71",
            "mode": "import",
            "queryGroup": "Static Filter Table",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WCskvScxRCEotS80rTVXSUTJUitWJVnJKLE5FEjRSio0FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Filter = _t, Value = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Filter\", type text}, {\"Value\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Year Sort",
        "lineageTag": "06c431a6-9b99-4a60-aa53-5881f8e1f204",
        "columns": [
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year",
            "formatString": "0",
            "lineageTag": "f45e177e-e032-405e-ae24-f40331023156",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "No",
            "dataType": "int64",
            "sourceColumn": "No",
            "formatString": "0",
            "lineageTag": "f20b92e3-6c86-4744-82e1-f1e301026612",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Year Sort-a7c4a16a-a12a-4940-acb3-2e85a5565386",
            "mode": "import",
            "queryGroup": "Static Filter Table",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMjIwMlTSUTJUitUBc4yAHCOl2FgA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Year = _t, No = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Year\", Int64.Type}, {\"No\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "FTB Measures",
        "lineageTag": "8b4ab077-d18b-4573-92e0-62bb3a5489fc",
        "columns": [
          {
            "name": "Column1",
            "dataType": "string",
            "sourceColumn": "Column1",
            "lineageTag": "01a9a55b-2659-40ad-82a7-dc3db28a7249",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "FTB Measures-45d421b3-b449-4931-be80-4d0d9b0958c4",
            "mode": "import",
            "queryGroup": "Static Filter Table",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Total Number of FTBs",
            "expression": [
              "CALCULATE (",
              "    DISTINCTCOUNT ( VW_DIM_CUSTOMER[Customer GSFA ID] ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        VW_DIM_CUSTOMER[FTB Reason] = \"New & Regained\"",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "1439c5c2-5f4d-41a9-96df-bb1f50f57149",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "Total Number of FTBs YTD",
            "expression": [
              "CALCULATE (",
              "    DISTINCTCOUNT ( VW_DIM_CUSTOMER[Customer GSFA ID] ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        YEAR ( VW_DIM_CUSTOMER[FTB Month] ) = [YTD]",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "e29df14a-e06d-4701-9f1a-5105efbd1440",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "Total Number of FTBs LM",
            "expression": [
              "CALCULATE (",
              "    DISTINCTCOUNT ( VW_DIM_CUSTOMER[Customer GSFA ID] ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        VW_DIM_CUSTOMER[FTB Reason] = \"New & Regained\"",
              "    ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        YEAR ( VW_DIM_CUSTOMER[FTB Month] ) = [YTD]",
              "    ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        MONTH ( VW_DIM_CUSTOMER[FTB Month] ) = [LM]",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "0f81b46f-c7c2-473e-9b75-6103473d3d94",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "Total Number of FTBs LYTD",
            "expression": [
              "CALCULATE (",
              "    DISTINCTCOUNT ( VW_DIM_CUSTOMER[Customer GSFA ID] ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        YEAR ( VW_DIM_CUSTOMER[FTB Month] ) = [LYTD]",
              "    ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        MONTH ( VW_DIM_CUSTOMER[FTB Month] ) <= [LYLM]",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "0580bb58-8e2b-4ea2-966e-6452b3d175a3",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "Total Number of FTBs LYLM",
            "expression": [
              "CALCULATE (",
              "    DISTINCTCOUNT ( VW_DIM_CUSTOMER[Customer GSFA ID] ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        VW_DIM_CUSTOMER[FTB Reason] = \"New & Regained\"",
              "    ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        YEAR ( VW_DIM_CUSTOMER[FTB Month] ) = [LY]",
              "    ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        MONTH ( VW_DIM_CUSTOMER[FTB Month] ) = [LM]",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "38b8d47f-591b-49c8-9640-6832e0942707",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "Avg Customer Retention Count LM",
            "expression": [
              "CALCULATE (",
              "    DISTINCTCOUNT ( FCT_COMMERCIAL_SUMMARY[Customer Name] ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        VW_DIM_CUSTOMER[FTB Month]",
              "            = DATE ( [YTD], [LM], 1 )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "0f13f9c0-fd2b-4267-abf9-3a868f98ad5f",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "Avg Customer Retention Count L12M",
            "expression": [
              "CALCULATE (",
              "    DISTINCTCOUNT ( DIM_ACCOUNT[Customer Name] ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        VW_DIM_CUSTOMER[FTB Month]",
              "            >= DATE ( YEAR (",
              "                TODAY ()",
              "            ), MONTH (",
              "                TODAY ()",
              "            ), 1 ) - 365",
              "    ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        VW_DIM_CUSTOMER[FTB Month]",
              "            <= DATE ( YEAR (",
              "                TODAY ()",
              "            ), MONTH (",
              "                TODAY ()",
              "            ) - 2, 1 )",
              "    )",
              ") / 11"
            ],
            "formatString": "0",
            "lineageTag": "d1faf588-9f7c-4803-98d0-46747a6a58a4",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "Customer Retention Ratio",
            "expression": "[Avg Customer Retention Count LM] / [Avg Customer Retention Count L12M]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "40e8b2fa-c47e-4e45-99dc-fa46b461d829",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "Avg Revenue Retention Count L12M",
            "expression": [
              "CALCULATE (",
              "    IF (",
              "        SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ) = \"BER - Euro\",",
              "        SUM ( FCT_COMMERCIAL_SUMMARY[Base Revenue EUR@BER] ),",
              "        IF (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ) = \"BER - USD\",",
              "            SUM ( FCT_COMMERCIAL_SUMMARY[Base Revenue USD@BER] ),",
              "            IF (",
              "                SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ) = \"Local Currency\",",
              "                SUM ( FCT_COMMERCIAL_SUMMARY[Base Revenue LCY] ),",
              "                0",
              "            )",
              "        )",
              "    ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        VW_DIM_CUSTOMER[FTB Month]",
              "            >= DATE ( YEAR (",
              "                TODAY ()",
              "            ), MONTH (",
              "                TODAY ()",
              "            ), 1 ) - 365",
              "    ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        VW_DIM_CUSTOMER[FTB Month]",
              "            <= DATE ( YEAR (",
              "                TODAY ()",
              "            ), MONTH (",
              "                TODAY ()",
              "            ) - 2, 1 )",
              "    )",
              ")"
            ],
            "lineageTag": "5de3b2e3-d636-4682-b935-de94a3864d41",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Avg Revenue Retention Count LM",
            "expression": [
              "CALCULATE (",
              "    IF (",
              "        SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ) = \"BER - Euro\",",
              "        SUM ( FCT_COMMERCIAL_SUMMARY[Base Revenue EUR@BER] ),",
              "        IF (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ) = \"BER - USD\",",
              "            SUM ( FCT_COMMERCIAL_SUMMARY[Base Revenue USD@BER] ),",
              "            IF (",
              "                SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ) = \"Local Currency\",",
              "                SUM ( FCT_COMMERCIAL_SUMMARY[Base Revenue LCY] ),",
              "                0",
              "            )",
              "        )",
              "    ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        VW_DIM_CUSTOMER[FTB Month]",
              "            = DATE ( [YTD], [LM], 1 )",
              "    )",
              ")"
            ],
            "lineageTag": "ae04684a-8c66-455d-82df-dcc8c6db3afc",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Revenue Retention Ratio",
            "expression": "[Avg Revenue Retention Count LM] / [Avg Revenue Retention Count L12M]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "a5e9f421-75f1-4bc2-9cbf-d257ac860dca",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "Total Revenue of FTBs YTD EUR",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Base Revenue EUR@BER] ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        YEAR ( VW_DIM_CUSTOMER[FTB Month] ) = [YTD]",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "lineageTag": "6d64aed1-49ad-4dd1-90d9-996041013b23",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "Total Revenue of FTBs LYTD EUR",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Base Revenue EUR@BER] ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        YEAR ( VW_DIM_CUSTOMER[FTB Month] ) = [LYTD]",
              "    ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        MONTH ( VW_DIM_CUSTOMER[FTB Month] ) <= [LM]",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "lineageTag": "e3df214f-33e5-4e9b-a86d-62ddfbb25eaf",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "Total Revenue of FTBs LM",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Base Revenue EUR@BER] ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        VW_DIM_CUSTOMER[FTB Reason] = \"New & Regained\"",
              "    ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        YEAR ( VW_DIM_CUSTOMER[FTB Month] ) = [YTD]",
              "    ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        MONTH ( VW_DIM_CUSTOMER[FTB Month] ) = [LM]",
              "    )",
              ")"
            ],
            "lineageTag": "3e9baa9b-f35e-49d8-b0c3-41b7c25a9e97",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue of FTBs LYLM",
            "expression": [
              "CALCULATE (",
              "    SUM ( VW_DIM_CUSTOMER[Customer GSFA ID] ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        VW_DIM_CUSTOMER[FTB Reason] = \"New & Regained\"",
              "    ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        YEAR ( VW_DIM_CUSTOMER[FTB Month] ) = [LY]",
              "    ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        MONTH ( VW_DIM_CUSTOMER[FTB Month] ) = [LM]",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "0f9663bd-174c-499e-9f1f-18013dac07d5",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "YoY Revenue Growth",
            "expression": "( [Total Revenue of FTBs YTD EUR] - [Total Revenue of FTBs LYTD EUR] )",
            "lineageTag": "d8534521-7946-4afa-bedb-07b1ef13c34b",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "% YoY Revenue Growth",
            "expression": [
              "DIVIDE (",
              "    [YoY Revenue Growth],",
              "    [Total Revenue of FTBs LYTD EUR]",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "b1c365d0-8f55-4978-ae6e-663eff339490",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "YoY Customer Growth",
            "expression": "( [Total Number of FTBs YTD] - [Total Number of FTBs LYTD] )",
            "formatString": "0",
            "lineageTag": "80784d9b-c5b4-4f7b-a104-7e360c7fdeec",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "Revenue Retention Count YTD",
            "expression": [
              "CALCULATE (",
              "    IF (",
              "        SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ) = \"BER - Euro\",",
              "        [Base Revenue EUR YTD],",
              "        IF (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ) = \"BER - USD\",",
              "            [Base Revenue USD YTD],",
              "            IF (",
              "                SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ) = \"Local Currency\",",
              "                [Base Revenue LCY YTD],",
              "                0",
              "            )",
              "        )",
              "    ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        YEAR ( VW_DIM_CUSTOMER[FTB Month] ) = [YTD]",
              "    )",
              ")"
            ],
            "lineageTag": "d8308814-2ddc-4d30-a3d7-197e94520a8a",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Revenue Retention Count LY",
            "expression": [
              "CALCULATE (",
              "    IF (",
              "        SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ) = \"BER - Euro\",",
              "        [Base Revenue EUR LY],",
              "        IF (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ) = \"BER - USD\",",
              "            [Base Revenue USD LY],",
              "            IF (",
              "                SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ) = \"Local Currency\",",
              "                [Base Revenue LCY LY],",
              "                0",
              "            )",
              "        )",
              "    ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        YEAR ( VW_DIM_CUSTOMER[FTB Month] ) = [LY]",
              "    )",
              ")"
            ],
            "lineageTag": "2c955687-c0e3-4161-97e9-1278e3c04fed",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Revenue Retention Growth No",
            "expression": "[Revenue Retention Count YTD] - [Revenue Retention Count LY]",
            "lineageTag": "4f17a6fd-fea3-4e42-b650-00a0ab27fe4a",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Reveunue Retention Growth %",
            "expression": [
              "DIVIDE (",
              "    [Revenue Retention Growth No],",
              "    [Revenue Retention Count LY]",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "c2d75834-a683-407c-96e6-b173d69f1873",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "Customer Retention  YTD",
            "expression": [
              "CALCULATE (",
              "    DISTINCTCOUNT ( VW_DIM_CUSTOMER[Customer GSFA ID] ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        YEAR ( VW_DIM_CUSTOMER[FTB Month] ) = [YTD]",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "5b7c2d9f-c0ae-4b6a-94b5-0c7eb1be1fe3",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "Customer Retention  LY",
            "expression": [
              "CALCULATE (",
              "    DISTINCTCOUNT ( VW_DIM_CUSTOMER[Customer GSFA ID] ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        YEAR ( VW_DIM_CUSTOMER[FTB Month] ) = [LY]",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "893bf53d-685a-4484-b3b5-681404eb6b04",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "Customer Retention Growth",
            "expression": "[Customer Retention  YTD] - [Customer Retention  LY]",
            "formatString": "0",
            "lineageTag": "4af1777e-5040-4075-a62d-88b7dcaeb287",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "Customer Retention Growth %",
            "expression": [
              "DIVIDE (",
              "    [Customer Retention Growth],",
              "    [Customer Retention  LY]",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "2d3e6bf1-76ba-4a1f-9035-702c887caf0c",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "FTB Trendline CY",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'FTB Filter'[ID] ),",
              "    1, [Total Number of FTBs YTD],",
              "    2, [Revenue Per FTB CY],",
              "    3, [FTB Number of Shipments YTD],",
              "    4, [FTB Revenue CY],",
              "    5, [FTB Billed Weight KG YTD],",
              "    6, \"\",",
              "    7, \"\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "e1a5dcb6-50a1-4931-9a60-ce5e609e2bed"
          },
          {
            "name": "Total Revenue of FTBs YTD LCY",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Base Revenue LCY] ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        YEAR ( VW_DIM_CUSTOMER[FTB Month] ) = [YTD]",
              "    )",
              ")"
            ],
            "lineageTag": "7d00d7d5-bc47-47b0-880d-d8085fb7f930",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue of FTBs YTD USD",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Base Revenue USD@BER] ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        YEAR ( VW_DIM_CUSTOMER[FTB Month] ) = [YTD]",
              "    )",
              ")"
            ],
            "lineageTag": "e9e26140-c254-4e0f-886a-b903fd6e8b42",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue of FTBs LYTD LCY",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Base Revenue LCY] ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        YEAR ( VW_DIM_CUSTOMER[FTB Month] ) = [LYTD]",
              "    ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        MONTH ( VW_DIM_CUSTOMER[FTB Month] ) <= [LM]",
              "    )",
              ")"
            ],
            "lineageTag": "56cbb8fc-f831-4e66-85f7-5608a9e6ae3a",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue of FTBs LYTD USD",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Base Revenue USD@BER] ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        YEAR ( VW_DIM_CUSTOMER[FTB Month] ) = [LYTD]",
              "    ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        MONTH ( VW_DIM_CUSTOMER[FTB Month] ) <= [LM]",
              "    )",
              ")"
            ],
            "lineageTag": "f1f0c54a-cd59-41bb-b750-bd52025255c0",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "FTB Revenue CY",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Currency Filter'[value] ),",
              "    1, [Total Revenue of FTBs YTD LCY],",
              "    2, [Total Revenue of FTBs YTD USD],",
              "    3, [Total Revenue of FTBs YTD EUR]",
              ")"
            ],
            "formatString": "#,0.0",
            "lineageTag": "a18c97ae-1d8a-4f50-939d-0b29b62e85f6",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "FTB Revenue LY",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Currency Filter'[value] ),",
              "    1, [Total Revenue of FTBs LYTD LCY],",
              "    2, [Total Revenue of FTBs LYTD USD],",
              "    3, [Total Revenue of FTBs LYTD EUR]",
              ")"
            ],
            "formatString": "#,0.0",
            "lineageTag": "24bf1fe5-1e7e-405a-89c2-047424966b31",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "FTB Number of Shipments YTD",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Number of Shipments] ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        VW_DIM_CUSTOMER[FTB Month] = [YTD]",
              "    )",
              ")"
            ],
            "lineageTag": "8f6a8625-52dd-432a-a368-52423fc8ba34",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "FTB Number of Shipments LYTD",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Number of Shipments] ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        VW_DIM_CUSTOMER[FTB Month] = [LYTD]",
              "    ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        MONTH ( VW_DIM_CUSTOMER[FTB Month] ) <= [LM]",
              "    )",
              ")"
            ],
            "lineageTag": "94855ba6-486f-4193-a5e6-18deb2f2b505",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "FTB Billed Weight KG YTD",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Billed Weight KG] ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        VW_DIM_CUSTOMER[FTB Month] = [YTD]",
              "    )",
              ")"
            ],
            "lineageTag": "48106a9d-38fd-4952-a254-cdbe3daaf11b",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "FTB Billed Weight KG LYTD",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Billed Weight KG] ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        VW_DIM_CUSTOMER[FTB Month] = [LYTD]",
              "    ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        MONTH ( VW_DIM_CUSTOMER[FTB Month] ) <= [LM]",
              "    )",
              ")"
            ],
            "lineageTag": "b5d57d69-ae74-450a-937b-e5512eb714a8",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Revenue Per FTB CY",
            "expression": [
              "DIVIDE (",
              "    [FTB Revenue CY],",
              "    [Total Number of FTBs YTD]",
              ")"
            ],
            "lineageTag": "0c43cabd-cd61-4cdb-8eba-7a3feb78a85e",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Revenue Per FTB LY",
            "expression": [
              "DIVIDE (",
              "    [FTB Revenue LY],",
              "    [Total Number of FTBs LYTD]",
              ")"
            ],
            "lineageTag": "8532b3a1-4747-4745-9640-140e88a4a64c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "FTB Trendline LY",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'FTB Filter'[ID] ),",
              "    1, [Total Number of FTBs LYTD],",
              "    2, [Revenue Per FTB LY],",
              "    3, [FTB Number of Shipments LYTD],",
              "    4, [FTB Revenue LY],",
              "    5, [FTB Billed Weight KG LYTD],",
              "    6, \"\",",
              "    7, \"\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "cf387335-4c04-49c3-99f0-2f9ead061e23"
          },
          {
            "name": "FTB Card YOY%",
            "expression": [
              "DIVIDE (",
              "    ( [FTB Trendline CY] - [FTB Trendline LY] ),",
              "    [FTB Trendline LY]",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "f3ea5bb4-b8e4-4535-89b3-3090ea975ceb",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "L13 FTBs",
            "expression": [
              "VAR _FTBs =",
              "    CALCULATE (",
              "        DISTINCTCOUNT ( VW_DIM_CUSTOMER[Customer GSFA ID] ),",
              "        FILTER (",
              "            VW_DIM_CUSTOMER,",
              "            VW_DIM_CUSTOMER[FTB Month]",
              "                > EOMONTH (",
              "                    TODAY (),",
              "                    - 14",
              "                )",
              "                && VW_DIM_CUSTOMER[FTB Month]",
              "                    <= EOMONTH (",
              "                        TODAY (),",
              "                        0",
              "                    )",
              "        )",
              "    )",
              "RETURN",
              "    _FTBs"
            ],
            "formatString": "0",
            "lineageTag": "b025c5a0-a7bf-4924-830a-a8af75cdca13"
          },
          {
            "name": "L13 Revenue",
            "expression": [
              "VAR _Revenue =",
              "    CALCULATE (",
              "        [_Base Revenue],",
              "        FILTER (",
              "            VW_DIM_CUSTOMER,",
              "            VW_DIM_CUSTOMER[FTB Month]",
              "                > EOMONTH (",
              "                    TODAY (),",
              "                    - 14",
              "                )",
              "                && VW_DIM_CUSTOMER[FTB Month]",
              "                    <= EOMONTH (",
              "                        TODAY (),",
              "                        0",
              "                    )",
              "        )",
              "    )",
              "RETURN",
              "    _Revenue"
            ],
            "formatString": "0.0",
            "lineageTag": "7d601a90-a9bc-47b2-a5c1-8b6164decb13",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "L13 Shipments",
            "expression": [
              "VAR _Shipments =",
              "    CALCULATE (",
              "        [Number of Shipments],",
              "        FILTER (",
              "            VW_DIM_CUSTOMER,",
              "            VW_DIM_CUSTOMER[FTB Month]",
              "                > EOMONTH (",
              "                    TODAY (),",
              "                    - 14",
              "                )",
              "                && VW_DIM_CUSTOMER[FTB Month]",
              "                    <= EOMONTH (",
              "                        TODAY (),",
              "                        0",
              "                    )",
              "        )",
              "    )",
              "RETURN",
              "    _Shipments"
            ],
            "formatString": "0",
            "lineageTag": "0788603d-b5bc-4097-979a-a2b5db02a24d",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "L13 Weight",
            "expression": [
              "VAR _Weight =",
              "    CALCULATE (",
              "        [Billed Weight KG],",
              "        FILTER (",
              "            VW_DIM_CUSTOMER,",
              "            VW_DIM_CUSTOMER[FTB Month]",
              "                > EOMONTH (",
              "                    TODAY (),",
              "                    - 14",
              "                )",
              "                && VW_DIM_CUSTOMER[FTB Month]",
              "                    <= EOMONTH (",
              "                        TODAY (),",
              "                        0",
              "                    )",
              "        )",
              "    )",
              "RETURN",
              "    _Weight"
            ],
            "formatString": "0.0",
            "lineageTag": "4a594ebc-d958-42c1-95e8-655dfb26743a",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "L13 Revenue per FTB",
            "expression": [
              "DIVIDE (",
              "    [L13 Revenue],",
              "    [L13 FTBs]",
              ")"
            ],
            "formatString": "0.0",
            "lineageTag": "28506835-92d6-44ea-8ec9-3c50d4a7948c",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "FTB Revenue YOY%",
            "expression": [
              "IF (",
              "    ISBLANK ( [FTB Revenue LY] ),",
              "    1,",
              "    DIVIDE (",
              "        ( [FTB Revenue CY] - [FTB Revenue LY] ),",
              "        [FTB Revenue LY]",
              "    )",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "fc63ad15-4ea6-4621-9dbf-84520176c6a5",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "FTB Base Revenue EUR LM",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Base Revenue EUR@BER] ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        YEAR ( VW_DIM_CUSTOMER[FTB Month] ) = [YTD]",
              "    ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        MONTH ( VW_DIM_CUSTOMER[FTB Month] ) = [LM]",
              "    )",
              ")"
            ],
            "lineageTag": "8bb88524-c1a8-4e8c-8ab0-e7eeaef61403",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "FTB Base Revenue USD LM",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Base Revenue USD@BER] ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        YEAR ( VW_DIM_CUSTOMER[FTB Month] ) = [YTD]",
              "    ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        MONTH ( VW_DIM_CUSTOMER[FTB Month] ) = [LM]",
              "    )",
              ")"
            ],
            "lineageTag": "6bf18a02-b5ac-4636-8920-b9eeb0251585",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "FTB Base Revenue LCY LM",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Base Revenue LCY] ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        YEAR ( VW_DIM_CUSTOMER[FTB Month] ) = [YTD]",
              "    ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        MONTH ( VW_DIM_CUSTOMER[FTB Month] ) = [LM]",
              "    )",
              ")"
            ],
            "lineageTag": "93c8078a-9534-46c5-954f-f0e29230e4d7",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "FTB Base Revenue EUR LM-1",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Base Revenue EUR@BER] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Dat]",
              "            = EOMONTH (",
              "                [Today],",
              "                - 2",
              "            )",
              "    )",
              ")"
            ],
            "lineageTag": "4119864a-e64c-4343-ace2-0845db69e9b0"
          },
          {
            "name": "FTB Base Revenue USD LM-1",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Base Revenue USD@BER] ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        YEAR ( VW_DIM_CUSTOMER[FTB Month] ) = [YTD]",
              "    ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        MONTH ( VW_DIM_CUSTOMER[FTB Month] ) = [LM] - 2",
              "    )",
              ")"
            ],
            "lineageTag": "edcfc3de-9ac7-41cb-8dae-f8fc71ec65f6",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "FTB Base Revenue LCY LM-1",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Base Revenue LCY] ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        YEAR ( VW_DIM_CUSTOMER[FTB Month] ) = [YTD]",
              "    ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        MONTH ( VW_DIM_CUSTOMER[FTB Month] ) = [LM] - 2",
              "    )",
              ")"
            ],
            "lineageTag": "132244bf-e17f-4b3d-b58e-0fded0702417",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "FTB Base Revenue LCY LM-2",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Base Revenue LCY] ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        YEAR ( VW_DIM_CUSTOMER[FTB Month] ) = [YTD]",
              "    ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        MONTH ( VW_DIM_CUSTOMER[FTB Month] ) = [LM] - 3",
              "    )",
              ")"
            ],
            "lineageTag": "a4a4aa7d-5cb5-49c5-8c4d-6b83673a802e",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "FTB Base Revenue USD LM-2",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Base Revenue USD@BER] ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        YEAR ( VW_DIM_CUSTOMER[FTB Month] ) = [YTD]",
              "    ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        MONTH ( VW_DIM_CUSTOMER[FTB Month] ) = [LM] - 3",
              "    )",
              ")"
            ],
            "lineageTag": "7895c4d6-b0e2-404a-8ed3-e5450ad6db5e",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "FTB Base Revenue EUR LM-2",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Base Revenue EUR@BER] ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        YEAR ( VW_DIM_CUSTOMER[FTB Month] ) = [YTD]",
              "    ),",
              "    FILTER (",
              "        VW_DIM_CUSTOMER,",
              "        MONTH ( VW_DIM_CUSTOMER[FTB Month] ) = [LM] - 3",
              "    )",
              ")"
            ],
            "lineageTag": "bcdd8419-9547-4e6d-89c1-ef9a08d78292",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "FTB Base Revenue LM",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "    \"BER - Euro\", [FTB Base Revenue EUR LM],",
              "    \"BER - USD\", [FTB Base Revenue USD LM],",
              "    \"Local Currency\", [FTB Base Revenue LCY LM]",
              ")"
            ],
            "lineageTag": "2af74335-a01a-4023-9076-992db3c0bd09",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "FTB Base Revenue LM-1",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "    \"BER - Euro\", [FTB Base Revenue EUR LM-1],",
              "    \"BER - USD\", [FTB Base Revenue USD LM-1],",
              "    \"Local Currency\", [FTB Base Revenue LCY LM-1]",
              ")"
            ],
            "lineageTag": "3b97ed0f-4ad2-48c2-9edb-48aba8785857",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "FTB Base Revenue LM-2",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "    \"BER - Euro\", [FTB Base Revenue EUR LM-2],",
              "    \"BER - USD\", [FTB Base Revenue USD LM-2],",
              "    \"Local Currency\", [FTB Base Revenue LCY LM-2]",
              ")"
            ],
            "lineageTag": "bebc109c-6e10-4158-868b-c8dac24b4c6e",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "FTB Revenue Varience",
            "expression": "[FTB Revenue CY] - [FTB Revenue LY]",
            "formatString": "#,0.0",
            "lineageTag": "311732c6-0340-4774-b1b5-aa60e3044c00",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "FTB Customer Varience",
            "expression": "[Total Number of FTBs YTD] - [Total Number of FTBs LYTD]",
            "formatString": "#,0",
            "lineageTag": "f443cf12-c6a9-44ad-bbf2-a85f56998939",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "FTB Customer YOY %",
            "expression": [
              "DIVIDE (",
              "    ( [Total Number of FTBs YTD] - [Total Number of FTBs LYTD] ),",
              "    [Total Number of FTBs LYTD]",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "41ff3a7e-2f7d-4122-ba14-9724fcfae723",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "TopCustomerFilter",
        "lineageTag": "bba356e7-9510-448f-9c6e-312e5d866bb1",
        "columns": [
          {
            "name": "TopFilter",
            "dataType": "string",
            "sourceColumn": "TopFilter",
            "sortByColumn": "Value",
            "lineageTag": "e933ee5e-bf4c-46ba-84ee-dacfe1be25e8",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "SortByColumn"
              },
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Value",
            "dataType": "int64",
            "sourceColumn": "Value",
            "formatString": "0",
            "lineageTag": "e6d80d43-4055-4bff-b384-5d3da691fdbb",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "FromValue",
            "dataType": "int64",
            "sourceColumn": "FromValue",
            "formatString": "0",
            "lineageTag": "34cdfd6e-74b0-44de-879b-3fd357aa99c3",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ToValue",
            "dataType": "int64",
            "sourceColumn": "ToValue",
            "formatString": "0",
            "lineageTag": "c1f3d8a6-a2b7-4dc2-b210-7f45284a7da6",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "TopCustomerFilter-cdd1ee87-4dd5-42a0-a5fc-35b9f809c4ba",
            "mode": "import",
            "queryGroup": "Static Filter Table",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WcszJUXAuLS7Jz00tKlbSUTIEYgMQbQAGSrE60Uoh+QUKRgYoyoygyowgKoJSi0sU8tNQlBiDpA2RjYoFAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [TopFilter = _t, Value = _t, FromValue = _t, ToValue = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"TopFilter\", type text}, {\"Value\", Int64.Type}, {\"FromValue\", Int64.Type}, {\"ToValue\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ]
      },
      {
        "name": "Dynamic Year",
        "lineageTag": "bc34c500-9cc1-4c32-bfe1-d00bcf53173b",
        "columns": [
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year",
            "formatString": "0",
            "lineageTag": "e5c4209b-727f-4af9-9c26-9322bf8ded58",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Value",
            "dataType": "int64",
            "sourceColumn": "Value",
            "formatString": "0",
            "lineageTag": "3e3b420f-cd84-4451-b82d-afe0fd632147",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Dynamic Value",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "IF(or('Dynamic Year'[Year]=[YTD],'Dynamic Year'[Year]=[LY]),1,0)",
            "formatString": "0",
            "lineageTag": "0c64cc3a-d1a6-4bd6-a6b1-34c8a5695c78",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Dynamic Year-c184c015-9f06-4313-acfc-ef385e670cb7",
            "mode": "import",
            "queryGroup": "Static Filter Table",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMjIwMlTSUTJUitUBc4yAHCMYxxjIMYZxTIAcE6XYWAA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Year = _t, Value = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Year\", Int64.Type}, {\"Value\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Main KPI Measures",
        "lineageTag": "95f3ec59-5397-46e6-ba4b-db758db03570",
        "partitions": [
          {
            "name": "Main KPI Measures-658cfebc-7634-44e6-aeec-15a621562b30",
            "mode": "import",
            "queryGroup": "Static Filter Table",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "L13 RPD",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "    \"Total Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Total Revenue EUR L13],",
              "                    [_Working Days LM13]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Total Revenue USD L13],",
              "                    [_Working Days LM13]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Total Revenue LCY L13],",
              "                    [_Working Days LM13]",
              "                )",
              "        ),",
              "    \"Base Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Base Revenue EUR L13],",
              "                    [_Working Days LM13]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Base Revenue USD L13],",
              "                    [_Working Days LM13]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Base Revenue LCY L13],",
              "                    [_Working Days LM13]",
              "                )",
              "        ),",
              "    \"Shipment\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Base Revenue EUR L13],",
              "                    [_Working Days LM13]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Base Revenue USD L13],",
              "                    [_Working Days LM13]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Base Revenue LCY L13],",
              "                    [_Working Days LM13]",
              "                )",
              "        ),",
              "    \"Weight\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Base Revenue EUR L13],",
              "                    [_Working Days LM13]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Base Revenue USD L13],",
              "                    [_Working Days LM13]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Base Revenue LCY L13],",
              "                    [_Working Days LM13]",
              "                )",
              "        )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "L13",
            "lineageTag": "3d1e7be2-5424-4e64-982e-f4561005f1b0",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "L13 RPK",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "    \"Total Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Total Revenue EUR L13],",
              "                    [Billed Weight KG L13]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Total Revenue USD L13],",
              "                    [Billed Weight KG L13]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Total Revenue LCY L13],",
              "                    [Billed Weight KG L13]",
              "                )",
              "        ),",
              "    \"Base Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Base Revenue EUR L13],",
              "                    [Billed Weight KG L13]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Base Revenue USD L13],",
              "                    [Billed Weight KG L13]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Base Revenue LCY L13],",
              "                    [Billed Weight KG L13]",
              "                )",
              "        ),",
              "    \"Shipment\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Base Revenue EUR L13],",
              "                    [Billed Weight KG L13]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Base Revenue USD L13],",
              "                    [Billed Weight KG L13]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Base Revenue LCY L13],",
              "                    [Billed Weight KG L13]",
              "                )",
              "        ),",
              "    \"Weight\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Base Revenue EUR L13],",
              "                    [Billed Weight KG L13]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Base Revenue USD L13],",
              "                    [Billed Weight KG L13]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Base Revenue LCY L13],",
              "                    [Billed Weight KG L13]",
              "                )",
              "        )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "L13",
            "lineageTag": "a2165ac7-4c0a-4de5-85ff-bb66ea398aac",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "L13 RPS",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "    \"Total Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Total Revenue EUR L13],",
              "                    [Number of Shipments L13]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Total Revenue USD L13],",
              "                    [Number of Shipments L13]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Total Revenue LCY L13],",
              "                    [Number of Shipments L13]",
              "                )",
              "        ),",
              "    \"Base Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Base Revenue EUR L13],",
              "                    [Number of Shipments L13]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Base Revenue USD L13],",
              "                    [Number of Shipments L13]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Base Revenue LCY L13],",
              "                    [Number of Shipments L13]",
              "                )",
              "        ),",
              "    \"Shipment\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Base Revenue EUR L13],",
              "                    [Number of Shipments L13]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Base Revenue USD L13],",
              "                    [Number of Shipments L13]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Base Revenue LCY L13],",
              "                    [Number of Shipments L13]",
              "                )",
              "        ),",
              "    \"Weight\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\",",
              "                DIVIDE (",
              "                    [Base Revenue EUR L13],",
              "                    [Number of Shipments L13]",
              "                ),",
              "            \"BER - USD\",",
              "                DIVIDE (",
              "                    [Base Revenue USD L13],",
              "                    [Number of Shipments L13]",
              "                ),",
              "            \"Local Currency\",",
              "                DIVIDE (",
              "                    [Base Revenue LCY L13],",
              "                    [Number of Shipments L13]",
              "                )",
              "        )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "L13",
            "lineageTag": "15b36a1d-1310-4b02-8e29-e3abf8c28f09",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "L13 WPS",
            "expression": [
              "VAR _Shipment =",
              "    CALCULATE (",
              "        SUM ( FCT_COMMERCIAL_SUMMARY[Number of Shipments] ),",
              "        FILTER (",
              "            DIM_PERIOD,",
              "            DIM_PERIOD[Billing Period Date]",
              "                > EOMONTH (",
              "                    [Today],",
              "                    - 14",
              "                )",
              "                && DIM_PERIOD[Billing Period Date]",
              "                    <= EOMONTH (",
              "                        [Today],",
              "                        -1",
              "                    )",
              "        )",
              "    )",
              "VAR _Weight =",
              "    CALCULATE (",
              "        SUM ( FCT_COMMERCIAL_SUMMARY[Billed Weight KG] ),",
              "        FILTER (",
              "            DIM_PERIOD,",
              "            DIM_PERIOD[Billing Period Date]",
              "                > EOMONTH (",
              "                    [Today],",
              "                    - 14",
              "                )",
              "                && DIM_PERIOD[Billing Period Date]",
              "                    <= EOMONTH (",
              "                        [Today],",
              "                        -1",
              "                    )",
              "        )",
              "    )",
              "VAR _Result =",
              "    DIVIDE (",
              "        _Weight,",
              "        _Shipment",
              "    )",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,0.0",
            "displayFolder": "L13",
            "lineageTag": "a2215251-f1e7-4b38-ad3e-c469aa059af1",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "L13 WPD",
            "expression": [
              "VAR _BilledWeight =",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Billed Weight KG] )",
              "VAR _Weight =",
              "    CALCULATE (",
              "        _BilledWeight,",
              "        FILTER (",
              "            DIM_PERIOD,",
              "            DIM_PERIOD[Billing Period Date]",
              "                > EOMONTH (",
              "                    [Today],",
              "                    - 14",
              "                )",
              "                && DIM_PERIOD[Billing Period Date]",
              "                    <= EOMONTH (",
              "                        [Today],",
              "                        -1",
              "                    )",
              "        )",
              "    )",
              "VAR _Result =",
              "    DIVIDE (",
              "        _Weight,",
              "        'Working Days'[_Working Days LM13]",
              "    )",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,0.0",
            "displayFolder": "L13",
            "lineageTag": "72d6fa06-44ee-4737-a411-c5d34f95c76d",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "L13 SPD",
            "expression": [
              "DIVIDE (",
              "    [Number of Shipments L13],",
              "    [_Working Days LM13]",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "L13",
            "lineageTag": "91411d9e-9713-48cc-97f2-4e89d9da00c3",
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "Avg L13 RPD",
            "expression": [
              "VAR _Result =",
              "    AVERAGEX (",
              "        VALUES ( DIM_PERIOD[Billing MON-YY] ),",
              "        [L13 RPD]",
              "    )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( _Result ),",
              "        0,",
              "        _Result",
              "    )"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Avg L13",
            "lineageTag": "49beb245-fba5-4921-abff-ceb2b2525346",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Avg L13 SPD",
            "expression": [
              "VAR _Result =",
              "    AVERAGEX (",
              "        VALUES ( DIM_PERIOD[Billing MON-YY] ),",
              "        [L13 SPD]",
              "    )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( _Result ),",
              "        0,",
              "        _Result",
              "    )"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Avg L13",
            "lineageTag": "c30c866d-2db2-4b81-accd-9e3adce84376",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Avg L13 WPD",
            "expression": [
              "VAR _Result =",
              "    AVERAGEX (",
              "        VALUES ( DIM_PERIOD[Billing MON-YY] ),",
              "        [L13 WPD]",
              "    )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( _Result ),",
              "        0,",
              "        _Result",
              "    )"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Avg L13",
            "lineageTag": "f89a9dcb-4a37-42d2-aff7-436d14673d47",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Avg L13 RPk",
            "expression": [
              "VAR _Result =",
              "    AVERAGEX (",
              "        VALUES ( DIM_PERIOD[Billing MON-YY] ),",
              "        [L13 RPK]",
              "    )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( _Result ),",
              "        0,",
              "        _Result",
              "    )"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Avg L13",
            "lineageTag": "4abbe6d7-1221-4c34-ac17-b717717865df",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Avg L13 RPS",
            "expression": [
              "VAR _Result =",
              "    AVERAGEX (",
              "        VALUES ( DIM_PERIOD[Billing MON-YY] ),",
              "        [L13 RPS]",
              "    )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( _Result ),",
              "        0,",
              "        _Result",
              "    )"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Avg L13",
            "lineageTag": "25a00963-743e-40cc-9c94-40da323ee0e4",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Avg L13 WPS",
            "expression": [
              "VAR _Result =",
              "    AVERAGEX (",
              "        VALUES ( DIM_PERIOD[Billing MON-YY] ),",
              "        [L13 WPS]",
              "    )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( _Result ),",
              "        0,",
              "        _Result",
              "    )"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Avg L13",
            "lineageTag": "75f18683-86fb-4482-9e77-ab61d73bce51",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Cus/Rev/Ship/Weight",
        "lineageTag": "fa4873a0-21f3-4b23-a417-73b7dc8011a2",
        "columns": [
          {
            "name": "Filter",
            "dataType": "string",
            "sourceColumn": "Filter",
            "sortByColumn": "Sort",
            "lineageTag": "d30e4ec5-0f73-485d-bf61-880153aa3600",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Sort",
            "dataType": "int64",
            "sourceColumn": "Sort",
            "formatString": "0",
            "lineageTag": "0bcb1c28-d34a-4494-8e56-8c3d16256f35",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Cus/Rev/Ship/Weight-e6d9628a-f687-47e9-8e74-8351d1e41038",
            "mode": "import",
            "queryGroup": "Static Filter Table",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45Wci4tLsnPTS0qVtJRMlSK1YlWckosTlUISi1LzStNBQoagQVD8ksSc5BEjcGiwRmZBbmpeSVAAROwQHhqZnoGiGuqFBsLAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Filter = _t, Sort = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Filter\", type text}, {\"Sort\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ]
      },
      {
        "name": "B2C/B2B",
        "lineageTag": "c8112e42-6ed3-43fb-8693-98ea3a90b9aa",
        "columns": [
          {
            "name": "Column1",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Column1",
            "lineageTag": "65c9bff7-51be-4449-8f6f-60b1ce2003df",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "B2C/B2B-50f808ff-5774-45ce-9c4b-119f6fdbc725",
            "mode": "import",
            "queryGroup": "B2B/B2C",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "B2B RSW YTD % New",
            "expression": [
              "VAR _B2B =",
              "    CALCULATE (",
              "        [RSW YTD],",
              "        FILTER (",
              "            FCT_COMMERCIAL_SUMMARY,",
              "            FCT_COMMERCIAL_SUMMARY[B2C Flag] = \"B2B\"",
              "        )",
              "    )",
              "VAR _B2BRSWYTD =",
              "    CALCULATE (",
              "        [RSW YTD],",
              "        ALL ( 'FCT_COMMERCIAL_SUMMARY'[B2C Flag] )",
              "    )",
              "RETURN",
              "    DIVIDE (",
              "        _B2B,",
              "        _B2BRSWYTD",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "Trendline",
            "lineageTag": "5b296610-1763-46ee-a456-7ac9bb34191f",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "YoY B2B/B2C Share YOY % New",
            "expression": "[RSW YTD] - [RSW LYTD]",
            "formatString": "0%;-0%;0%",
            "displayFolder": "Card",
            "lineageTag": "38baed93-6e1c-463c-a5c1-4f63c99168f8",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Total Customers L13",
            "expression": [
              "CALCULATE (",
              "    DISTINCTCOUNT ( VW_DIM_CUSTOMER[Customer GSFA ID] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 14",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                <= EOMONTH (",
              "                    [Today],",
              "                    -1",
              "                )",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "B2B/B2C L13",
            "lineageTag": "eaa1c5b8-ce30-427a-9160-eb63bd376e7c",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "B2B/B2C Shipment L13 %",
            "expression": [
              "VAR TotalShipment =",
              "    CALCULATE (",
              "        [Number of Shipments L13],",
              "        ALL ( FCT_COMMERCIAL_SUMMARY[B2C Flag] )",
              "    )",
              "RETURN",
              "    DIVIDE (",
              "        [Number of Shipments L13],",
              "        TotalShipment",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "B2B/B2C L13",
            "lineageTag": "b0593c61-c407-4490-8375-298dd5305db4",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "B2B/B2C Weight L13 %",
            "expression": [
              "VAR Totalweight =",
              "    CALCULATE (",
              "        [Billed Weight KG L13],",
              "        ALL ( FCT_COMMERCIAL_SUMMARY[B2C Flag] )",
              "    )",
              "RETURN",
              "    DIVIDE (",
              "        [Billed Weight KG L13],",
              "        Totalweight",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "B2B/B2C L13",
            "lineageTag": "a37304f2-e12a-4313-8aa9-bcb30353a0a4",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "B2B/B2C Customer L13 %",
            "expression": [
              "VAR Totalcutomers =",
              "    CALCULATE (",
              "        [Total Customers L13],",
              "        ALL ( FCT_COMMERCIAL_SUMMARY[B2C Flag] )",
              "    )",
              "RETURN",
              "    DIVIDE (",
              "        [Total Customers L13],",
              "        Totalcutomers",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "B2B/B2C L13",
            "lineageTag": "4948fe08-013b-4ce8-a326-0f31cc3c38d6",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "B2B/B2C Revenue L13 %",
            "expression": [
              "VAR TotalBaseRev =",
              "    CALCULATE (",
              "        [B2B/B2C Total Base Revenue L13 New],",
              "        ALL ( FCT_COMMERCIAL_SUMMARY[B2C Flag] )",
              "    )",
              "RETURN",
              "    DIVIDE (",
              "        [B2B/B2C Total Base Revenue L13 New],",
              "        TotalBaseRev",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "B2B/B2C L13",
            "lineageTag": "712ec595-58f9-431e-b3de-2a1c68c123a7",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "B2B/B2C Total Base Revenue L13 New",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Rev/Ship/Weight Filter'[Filter] ),",
              "    \"Total Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\", [Total Revenue EUR L13],",
              "            \"BER - USD\", [Total Revenue USD L13],",
              "            \"Local Currency\", [Total Revenue LCY L13]",
              "        ),",
              "    \"Base Revenue\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\", [Base Revenue EUR L13],",
              "            \"BER - USD\", [Base Revenue USD L13],",
              "            \"Local Currency\", [Base Revenue LCY L13]",
              "        ),",
              "    \"Shipment\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\", [Base Revenue EUR L13],",
              "            \"BER - USD\", [Base Revenue USD L13],",
              "            \"Local Currency\", [Base Revenue LCY L13]",
              "        ),",
              "    \"Weight\",",
              "        SWITCH (",
              "            SELECTEDVALUE ( 'Currency Filter'[LCY/BER] ),",
              "            \"BER - Euro\", [Base Revenue EUR L13],",
              "            \"BER - USD\", [Base Revenue USD L13],",
              "            \"Local Currency\", [Base Revenue LCY L13]",
              "        )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "B2B/B2C L13",
            "lineageTag": "8765c824-aff9-49dd-9457-05277008e749",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "B2B RSW LY % New",
            "expression": [
              "VAR _B2B =",
              "    CALCULATE (",
              "        [RSW LY],",
              "        FILTER (",
              "            FCT_COMMERCIAL_SUMMARY,",
              "            FCT_COMMERCIAL_SUMMARY[B2C Flag] = \"B2B\"",
              "        )",
              "    )",
              "VAR _B2BRSWLY =",
              "    CALCULATE (",
              "        [RSW LY],",
              "        ALL ( 'FCT_COMMERCIAL_SUMMARY'[B2C Flag] )",
              "    )",
              "RETURN",
              "    DIVIDE (",
              "        _B2B,",
              "        _B2BRSWLY",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "Trendline",
            "lineageTag": "eb0be2d4-749d-4ac1-9770-9c463c74c1e3",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "B2C RSW YTD % New",
            "expression": [
              "VAR _B2C =",
              "    CALCULATE (",
              "        [RSW YTD],",
              "        FILTER (",
              "            FCT_COMMERCIAL_SUMMARY,",
              "            FCT_COMMERCIAL_SUMMARY[B2C Flag] = \"B2C\"",
              "        )",
              "    )",
              "VAR _B2CRSWYTD =",
              "    CALCULATE (",
              "        [RSW YTD],",
              "        ALL ( 'FCT_COMMERCIAL_SUMMARY'[B2C Flag] )",
              "    )",
              "RETURN",
              "    DIVIDE (",
              "        _B2C,",
              "        _B2CRSWYTD",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "Trendline",
            "lineageTag": "a0cc11aa-73af-4747-9563-7b7da9933e55",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "B2C RSW LY % New",
            "expression": [
              "VAR _B2C =",
              "    CALCULATE (",
              "        [RSW LY],",
              "        FILTER (",
              "            FCT_COMMERCIAL_SUMMARY,",
              "            FCT_COMMERCIAL_SUMMARY[B2C Flag] = \"B2C\"",
              "        )",
              "    )",
              "VAR _B2CRSWLY =",
              "    CALCULATE (",
              "        [RSW LY],",
              "        ALL ( 'FCT_COMMERCIAL_SUMMARY'[B2C Flag] )",
              "    )",
              "RETURN",
              "    DIVIDE (",
              "        _B2C,",
              "        _B2CRSWLY",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "Trendline",
            "lineageTag": "1dd0779c-a7ad-4a51-b024-59abbc9a5a28",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "B2B/B2C Share YTD New",
            "expression": [
              "VAR _RSWYTD =",
              "    CALCULATE (",
              "        [RSW YTD],",
              "        ALL ( FCT_COMMERCIAL_SUMMARY[B2C Flag] )",
              "    )",
              "RETURN",
              "    DIVIDE (",
              "        [RSW YTD],",
              "        _RSWYTD",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "Card",
            "lineageTag": "8bfc689a-56cf-4afb-b451-a2b60d730221",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "B2B/B2C Share LYTD New",
            "expression": [
              "VAR _RSWYTD =",
              "    CALCULATE (",
              "        [RSW LYTD],",
              "        ALL ( FCT_COMMERCIAL_SUMMARY[B2C Flag] )",
              "    )",
              "RETURN",
              "    DIVIDE (",
              "        [RSW LYTD],",
              "        _RSWYTD",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "Card",
            "lineageTag": "8294e4dc-b916-42fd-9942-3e034f3e5510",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "YoY B2B/B2C Share Growth New",
            "expression": "[RSW YTD] - [RSW LYTD]",
            "formatString": "#,0.0",
            "displayFolder": "Card",
            "lineageTag": "d79fd9de-bf58-43fc-82fb-097b0d92078f",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "B2B/B2C Share YTD/LM New",
            "expression": [
              "VAR _RSWYTD =",
              "    CALCULATE (",
              "        [RSW YTD/LM],",
              "        ALL ( FCT_COMMERCIAL_SUMMARY[B2C Flag] )",
              "    )",
              "VAR _Result =",
              "    DIVIDE (",
              "        [RSW YTD/LM],",
              "        _RSWYTD",
              "    )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( _Result ),",
              "        0,",
              "        _Result",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "Card",
            "lineageTag": "91743151-6b63-40b1-b1ab-3019745df3da",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Customer Filters",
        "lineageTag": "19cf8b23-dc45-4cba-8157-7fc13b163743",
        "columns": [
          {
            "name": "Cust Filters",
            "dataType": "string",
            "sourceColumn": "Cust Filters",
            "sortByColumn": "Column2",
            "lineageTag": "60c67c69-846d-4448-981c-1d870c80dff1",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Column2",
            "dataType": "int64",
            "sourceColumn": "Column2",
            "formatString": "0",
            "lineageTag": "a8a35121-a6aa-4658-8931-26dc4c22db1d",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Customer Filters-fbfbdbad-0c20-45d8-a2f0-228f89ec100b",
            "mode": "import",
            "queryGroup": "Static Filter Table",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WckwuySxLVXAuLS7Jz00tKlbSUTJUitUBSpSlFiWmpyoEF6TmpYCEjcDCqgr5aQohRYkpmXnpAflFJWn5OZn5QFljpdhYAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t, Column2 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Column2\", Int64.Type}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Column1\", \"Cust Filters\"}})",
                "in",
                "    #\"Renamed Columns\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Portfolia Measure",
        "lineageTag": "be4431da-c86a-41c3-846c-32184574b7a0",
        "partitions": [
          {
            "name": "Portfolia Measure-34f95363-b1b5-4f56-8223-695012c30112",
            "mode": "import",
            "queryGroup": "Static Filter Table",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Rankx RSW YTD/LM New",
            "expression": [
              "IF (",
              "    [RSW YTD/LM] > 0,",
              "    RANKX (",
              "        ALLSELECTED ( VW_DIM_CUSTOMER[Customer Name] ),",
              "        [RSW YTD/LM],",
              "        ,",
              "        DESC",
              "    ),",
              "    BLANK ()",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "RSW Portfolio",
            "lineageTag": "365c634f-5da8-485c-bb8b-fbd2270bfe8d"
          },
          {
            "name": "RSW YTD/LM TopFilter New",
            "expression": [
              "IF (",
              "    AND (",
              "        [Rankx RSW YTD/LM New]",
              "            >= SELECTEDVALUE ( TopCustomerFilter[FromValue] ),",
              "        [Rankx RSW YTD/LM New]",
              "            <= SELECTEDVALUE ( TopCustomerFilter[ToValue] )",
              "    ),",
              "    [RSW YTD/LM],",
              "    BLANK ()",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "RSW Portfolio",
            "lineageTag": "14df4d05-cd5c-4deb-9ccc-3aac1fcee97d"
          },
          {
            "name": "RSW YTD/LM TopFilterc New",
            "expression": [
              "VAR _Result =",
              "    CALCULATE (",
              "        [RSW YTD/LM],",
              "        FILTER (",
              "            ALLSELECTED ( VW_DIM_CUSTOMER[Customer Name] ),",
              "            [Rankx RSW YTD/LM New]",
              "                >= SELECTEDVALUE ( TopCustomerFilter[FromValue] )",
              "                && [Rankx RSW YTD/LM New]",
              "                    <= SELECTEDVALUE ( TopCustomerFilter[ToValue] )",
              "        )",
              "    )",
              "RETURN",
              "    // IF(ISBLANK(_Result),0,_Result)",
              "    _Result"
            ],
            "formatString": "#,0.0",
            "displayFolder": "RSW Portfolio",
            "lineageTag": "5e8497ea-cf4a-4cf8-a3cd-4ff73a95e0fb",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Rankx RSW YTD New",
            "expression": [
              "IF (",
              "    [RSW YTD] > 0,",
              "    RANKX (",
              "        ALLSELECTED ( VW_DIM_CUSTOMER[Customer Name] ),",
              "        [RSW YTD],",
              "        ,",
              "        DESC",
              "    ),",
              "    BLANK ()",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "RSW Portfolio",
            "lineageTag": "8ad73c9b-bbf0-4963-be26-bf683b73b3b3"
          },
          {
            "name": "RSW YTD TopFilterc New",
            "expression": [
              "CALCULATE (",
              "    [RSW YTD],",
              "    FILTER (",
              "        ALLSELECTED ( VW_DIM_CUSTOMER[Customer Name] ),",
              "        [Rankx RSW YTD New]",
              "            >= SELECTEDVALUE ( TopCustomerFilter[FromValue] )",
              "            && [Rankx RSW YTD New]",
              "                <= SELECTEDVALUE ( TopCustomerFilter[ToValue] )",
              "    )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "RSW Portfolio",
            "lineageTag": "65f15953-22c5-4f98-a0b0-bed399d52018",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Rankx RSW LY New",
            "expression": [
              "IF (",
              "    [RSW LY] > 0,",
              "    RANKX (",
              "        ALLSELECTED ( VW_DIM_CUSTOMER[Customer Name] ),",
              "        [RSW LY],",
              "        ,",
              "        DESC",
              "    ),",
              "    BLANK ()",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "RSW Portfolio",
            "lineageTag": "1a40464b-ed80-4066-81c8-832d59d4c48b"
          },
          {
            "name": "RSW LY TopFilterc New",
            "expression": [
              "CALCULATE (",
              "    [RSW LY],",
              "    FILTER (",
              "        ALLSELECTED ( VW_DIM_CUSTOMER[Customer Name] ),",
              "        [Rankx RSW LY New]",
              "            >= SELECTEDVALUE ( TopCustomerFilter[FromValue] )",
              "            && [Rankx RSW LY New]",
              "                <= SELECTEDVALUE ( TopCustomerFilter[ToValue] )",
              "    )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "RSW Portfolio",
            "lineageTag": "3f681353-36a1-4e12-bf9a-3cdda9e8f144",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Rankx RSW LYTD/LYLM New",
            "expression": [
              "IF (",
              "    [RSW LYTD/LYLM] > 0,",
              "    RANKX (",
              "        ALLSELECTED ( VW_DIM_CUSTOMER[Customer Name] ),",
              "        [RSW LYTD/LYLM],",
              "        ,",
              "        DESC",
              "    ),",
              "    BLANK ()",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "RSW Portfolio",
            "lineageTag": "022fa0d8-1bef-427c-ae9b-00c21b0b65f2"
          },
          {
            "name": "RSW LYTD/LYLM TopFilterc New",
            "expression": [
              "CALCULATE (",
              "    [RSW LYTD/LYLM],",
              "    FILTER (",
              "        ALLSELECTED ( VW_DIM_CUSTOMER[Customer Name] ),",
              "        [Rankx RSW LYTD/LYLM New]",
              "            >= SELECTEDVALUE ( TopCustomerFilter[FromValue] )",
              "            && [Rankx RSW LYTD/LYLM New]",
              "                <= SELECTEDVALUE ( TopCustomerFilter[ToValue] )",
              "    )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "RSW Portfolio",
            "lineageTag": "829aab7f-adcb-4b16-a094-dd827be31afb",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RSW YTD/LM/LYTD/LYLM TopFilterc Growth New",
            "expression": "[RSW YTD/LM TopFilterc New] - [RSW LYTD/LYLM TopFilterc New]",
            "formatString": "#,0.0",
            "displayFolder": "RSW Portfolio",
            "lineageTag": "0d0b4d3b-b89c-4622-b0e2-1df7159ab268",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RSW YTD/LM/LYTD/LYLM TopFilterc YOY % New",
            "expression": [
              "VAR _Growth = [RSW YTD/LM TopFilterc New] - [RSW LYTD/LYLM TopFilterc New]",
              "VAR _Result =",
              "    DIVIDE (",
              "        _Growth,",
              "        [RSW LYTD/LYLM TopFilterc New]",
              "    )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( _Result ),",
              "        0,",
              "        _Result",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "RSW Portfolio",
            "lineageTag": "0e30cd46-3530-4e9f-a6d0-fa15cfc74177",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RSW YTD/LY YOY %",
            "expression": [
              "VAR _Varince = [RSW YTD TopFilterc New] - [RSW LY TopFilterc New]",
              "RETURN",
              "    IF (",
              "        ISBLANK ( [RSW LY TopFilterc New] ),",
              "        1,",
              "        DIVIDE (",
              "            _Varince,",
              "            [RSW LY TopFilterc New]",
              "        )",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "RSW Portfolio",
            "lineageTag": "204ac71c-9fdf-4064-ac04-8515557c4028",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RSW YTD/LY Growth",
            "expression": [
              "VAR _Varince = [RSW YTD TopFilterc New] - [RSW LY TopFilterc New]",
              "RETURN",
              "    _Varince"
            ],
            "formatString": "#,0.0",
            "displayFolder": "RSW Portfolio",
            "lineageTag": "5c0fc1e1-fd81-4c68-9cee-9e93e5b28bd1",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RSW YTD/LM/LYTD/LYLM YOY % ZP",
            "expression": [
              "VAR _Growth = [RSW YTD/LM] - [RSW LYTD/LYLM]",
              "RETURN",
              "    SWITCH (",
              "        TRUE (),",
              "        //ISBLANK ( [RSW YTD/LM] ) && ISBLANK ( [RSW LYTD/LYLM] ), 0,",
              "        [RSW YTD/LM] < 0, -1,",
              "        NOT (",
              "            ISBLANK ( [RSW YTD/LM] )",
              "        )",
              "            && ISBLANK ( [RSW LYTD/LYLM] ), 1,",
              "        ISBLANK ( [RSW YTD/LM] )",
              "            && NOT (",
              "                ISBLANK ( [RSW LYTD/LYLM] )",
              "            ), -1,",
              "        DIVIDE (",
              "            _Growth,",
              "            [RSW LYTD/LYLM]",
              "        )",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "RSW Portfolio",
            "lineageTag": "30c1723a-190d-46bb-98d7-66d6481d8d22",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RSW YTD/LM/LYTD/LYLM YOY % ZP1",
            "expression": [
              "VAR _Growth = [RSW YTD/LM] - [RSW LYTD/LYLM]",
              "RETURN",
              "    SWITCH (",
              "        TRUE (),",
              "        //ISBLANK ( [RSW YTD/LM] ) && ISBLANK ( [RSW LYTD/LYLM] ), 0,",
              "        NOT (",
              "            ISBLANK ( [RSW YTD/LM] )",
              "        )",
              "            && ISBLANK ( [RSW LYTD/LYLM] ), 1,",
              "        ISBLANK ( [RSW YTD/LM] )",
              "            && NOT (",
              "                ISBLANK ( [RSW LYTD/LYLM] )",
              "            ), -1,",
              "        DIVIDE (",
              "            _Growth,",
              "            [RSW LYTD/LYLM]",
              "        )",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "RSW Portfolio",
            "lineageTag": "e338cd22-73e0-4e14-909c-635ce005d4fc",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Rankx RSW YTD/LM IBOB",
            "expression": [
              "CALCULATE (",
              "    RANKX (",
              "        ALLSELECTED ( VW_DIM_CUSTOMER[Customer Name] ),",
              "        [RSW YTD/LM],",
              "        ,",
              "        DESC",
              "    ),",
              "    ALL ( FCT_COMMERCIAL_SUMMARY[IBOB] )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "RSW Portfolio",
            "lineageTag": "6293a124-9132-479d-8cb1-f175aba36078"
          },
          {
            "name": "RSW YTD/LM TopFilterc New IBOB",
            "expression": [
              "VAR _Result =",
              "    CALCULATE (",
              "        [RSW YTD/LM],",
              "        FILTER (",
              "            ALLSELECTED ( VW_DIM_CUSTOMER[Customer Name] ),",
              "            [Rankx RSW YTD/LM IBOB]",
              "                >= SELECTEDVALUE ( TopCustomerFilter[FromValue] )",
              "                && [Rankx RSW YTD/LM IBOB]",
              "                    <= SELECTEDVALUE ( TopCustomerFilter[ToValue] )",
              "        )",
              "    )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( _Result ),",
              "        0,",
              "        _Result",
              "    )"
            ],
            "formatString": "#,0.0",
            "displayFolder": "RSW Portfolio",
            "lineageTag": "b0ed50a9-fd4f-4ad2-9536-17fb183eeb40",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Rankx RSW YTD/LM Product",
            "expression": [
              "CALCULATE (",
              "    RANKX (",
              "        ALLSELECTED ( VW_DIM_CUSTOMER[Customer Name] ),",
              "        [RSW YTD/LM],",
              "        ,",
              "        DESC",
              "    ),",
              "    ALL ( DIM_PRODUCT[Product Code] )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "RSW Portfolio",
            "lineageTag": "1b0341bf-d66e-4730-a3a0-73948396fdab"
          },
          {
            "name": "RSW YTD/LM TopFilterc New Product",
            "expression": [
              "CALCULATE (",
              "    [RSW YTD/LM],",
              "    FILTER (",
              "        ALLSELECTED ( VW_DIM_CUSTOMER[Customer Name] ),",
              "        [Rankx RSW YTD/LM Product]",
              "            >= SELECTEDVALUE ( TopCustomerFilter[FromValue] )",
              "            && [Rankx RSW YTD/LM Product]",
              "                <= SELECTEDVALUE ( TopCustomerFilter[ToValue] )",
              "    )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "RSW Portfolio",
            "lineageTag": "c08be076-e36c-4815-ae9c-b9e51821b8af",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Rankx RSW LYTD/LYLM Product",
            "expression": [
              "CALCULATE (",
              "    RANKX (",
              "        ALLSELECTED ( VW_DIM_CUSTOMER[Customer Name] ),",
              "        [RSW LYTD/LYLM],",
              "        ,",
              "        DESC",
              "    ),",
              "    ALL ( DIM_PRODUCT[Product Code] )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "RSW Portfolio",
            "lineageTag": "8158707c-6614-4dbe-9637-ade0102efcb6"
          },
          {
            "name": "RSW LYTD/LYLM TopFilterc New Product",
            "expression": [
              "CALCULATE (",
              "    [RSW LYTD/LYLM],",
              "    FILTER (",
              "        ALLSELECTED ( VW_DIM_CUSTOMER[Customer Name] ),",
              "        [Rankx RSW LYTD/LYLM Product]",
              "            >= SELECTEDVALUE ( TopCustomerFilter[FromValue] )",
              "            && [Rankx RSW LYTD/LYLM Product]",
              "                <= SELECTEDVALUE ( TopCustomerFilter[ToValue] )",
              "    )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "RSW Portfolio",
            "lineageTag": "69640a2f-0cbf-4910-a513-2b021ba36805",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RSW YTD/LM/LYTD/LYLM Product Growth",
            "expression": "[RSW YTD/LM TopFilterc New Product] - [RSW LYTD/LYLM TopFilterc New Product]",
            "formatString": "#,0.0",
            "displayFolder": "RSW Portfolio",
            "lineageTag": "326a6db9-7d52-4a53-8c56-bdb4c6357b7e",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RSW YTD/LM/LYTD/LYLM Product YOY %",
            "expression": [
              "VAR _Growth = [RSW YTD/LM TopFilterc New Product] - [RSW LYTD/LYLM TopFilterc New Product]",
              "RETURN",
              "    DIVIDE (",
              "        _Growth,",
              "        [RSW LYTD/LYLM TopFilterc New Product]",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "RSW Portfolio",
            "lineageTag": "8ec37f0d-48d9-4123-b1b4-bb5f48b04ab5",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Rankx RSW LYTD/LYLM IBOB",
            "expression": [
              "CALCULATE (",
              "    RANKX (",
              "        ALLSELECTED ( VW_DIM_CUSTOMER[Customer Name] ),",
              "        [RSW LYTD/LYLM],",
              "        ,",
              "        DESC",
              "    ),",
              "    ALL ( FCT_COMMERCIAL_SUMMARY[IBOB] )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "RSW Portfolio",
            "lineageTag": "4ab5e35b-1235-4b46-8563-85b90485b63d"
          },
          {
            "name": "RSW LYTD/LYLM TopFilterc New IBOB",
            "expression": [
              "CALCULATE (",
              "    [RSW LYTD/LYLM],",
              "    FILTER (",
              "        ALLSELECTED ( VW_DIM_CUSTOMER[Customer Name] ),",
              "        [Rankx RSW LYTD/LYLM IBOB]",
              "            >= SELECTEDVALUE ( TopCustomerFilter[FromValue] )",
              "            && [Rankx RSW LYTD/LYLM IBOB]",
              "                <= SELECTEDVALUE ( TopCustomerFilter[ToValue] )",
              "    )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "RSW Portfolio",
            "lineageTag": "06939425-f583-4b55-aeaf-2714ed656b1b",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "RSW YTD/LM/LYTD/LYLM IBOB YOY %",
            "expression": [
              "VAR _Growth = [RSW YTD/LM TopFilterc New IBOB] - [RSW LYTD/LYLM TopFilterc New IBOB]",
              "VAR _Result =",
              "    DIVIDE (",
              "        _Growth,",
              "        [RSW LYTD/LYLM TopFilterc New IBOB]",
              "    )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( _Result ),",
              "        0,",
              "        _Result",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "RSW Portfolio",
            "lineageTag": "06544c72-6d0f-4b06-a339-f24386832a46",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Shipment Band",
        "lineageTag": "d2dbd247-fd58-4701-b228-388645191452",
        "columns": [
          {
            "name": "Shipment Band ",
            "dataType": "string",
            "sourceColumn": "Shipment Band ",
            "sortByColumn": "Values",
            "lineageTag": "4fd49479-7c99-450f-a334-7340aa21a989",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Values",
            "dataType": "int64",
            "sourceColumn": "Values",
            "formatString": "0",
            "lineageTag": "5f98d21f-2e28-498b-b55f-96fed30c7bc7",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Shipment Band-a4e6e07e-b93d-478a-b993-e7770b0ef710",
            "mode": "import",
            "queryGroup": "Static Filter Table",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"HcfBDQAgCASwXe6rJIDCMoT91xDv11ZBJbBh6F1I8R9nPMVUp4c1NQn+8uM1CXQ/\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Shipment Band \" = _t, Values = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Shipment Band \", type text}, {\"Values\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Shipment Band Filter",
        "lineageTag": "0e8b11af-ed33-4606-8afc-9884b55c3628",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Value",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value1]",
            "formatString": "0",
            "lineageTag": "77e6d94d-2e16-4c9f-a8d3-7251279d8b23",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Filter",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value2]",
            "sortByColumn": "Value",
            "lineageTag": "bef157aa-235a-4384-b152-92bd492020bc",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Value3",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value3]",
            "lineageTag": "0c05507b-347b-4dd6-a810-81c08f14a05b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Shipment Band Filter-360be6ca-68cc-413e-afed-081e6824085e",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "{",
                "    (0,\"Shipments\",\"Shipment\"),",
                "    (1,\"SPD\",\"Shipment Per Day\"),",
                "    (2,\"RPD\",\"Revenue Per Day\"),",
                "    (3,\"RPK\",\"Revenue Per Kilo\"),",
                "    (4,\"RPS\",\"Revenue Per Shipment\"),",
                "    (5,\"WPS\",\"Weight Per Shipment\")",
                "    }"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "385f40e4ba314979aa9c8abfa802cf61"
          }
        ]
      },
      {
        "name": "Shipment Band Measure",
        "lineageTag": "8be1b7dc-a031-456d-8a48-aa8bd7df0834",
        "partitions": [
          {
            "name": "Shipment Band Measure-da038f20-d2ee-4869-915b-addd77c7e5f6",
            "mode": "import",
            "queryGroup": "Shipment Band",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Number of Shipments YTD2",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Number of Shipments] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        YEAR ( DIM_PERIOD[Billing Period Date] ) = [YTD]",
              "    )",
              ")"
            ],
            "lineageTag": "0a5ef5ba-b0a5-4ac6-a32f-2e797e3763d7",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Number of Shipments LYTD2",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Number of Shipments] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        YEAR ( DIM_PERIOD[Billing Period Date] ) = [LYTD]",
              "            && MONTH ( DIM_PERIOD[Billing Period Date] ) < [LM]",
              "    )",
              ")"
            ],
            "lineageTag": "14145517-7d92-4335-8bfe-31aa6b6cef60",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Number of Shipments LM1",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Number of Shipments] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        YEAR ( DIM_PERIOD[Billing Period Date] ) = [YTD]",
              "            && MONTH ( DIM_PERIOD[Billing Period Date] ) = [LM]",
              "    )",
              ")"
            ],
            "lineageTag": "16ec79f4-d597-4e39-914a-7b22c86b416a",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Number of Shipments LYLM1",
            "expression": [
              "CALCULATE (",
              "    SUM ( FCT_COMMERCIAL_SUMMARY[Number of Shipments] ),",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        YEAR ( DIM_PERIOD[Billing Period Date] ) = [LY]",
              "            && MONTH ( DIM_PERIOD[Billing Period Date] ) = [LM]",
              "    )",
              ")"
            ],
            "lineageTag": "0fec17be-a5d4-437e-b82a-ed5b4cd02544",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Shipment YoY %",
            "expression": "( [Number of Shipments YTD2] - [Number of Shipments LYTD2] ) / [Number of Shipments LYTD2]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "c7f0da0d-c4a7-498b-b5cd-10f866b58d54",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Shipment MoM %",
            "expression": "( [Number of Shipments LM1] - [Number of Shipments LYLM1] ) / [Number of Shipments LYLM1]",
            "lineageTag": "33a7a715-1797-43a8-b0e9-9813bdcd6f6c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Shipment Growth %",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Period Filter'[Period] ),",
              "    \"YTD\", [Shipment YoY %],",
              "    \"LM\", [Shipment MoM %]",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "52d9ec14-0ad5-4f04-8400-26bf4ec83cdd",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Shipment Band L13 Months",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Shipment Band Filter'[Filter] ),",
              "    \"Shipments\", [Shipment L131],",
              "    \"SpD\", [L13 SPD],",
              "    \"RpD\", [L13 RPD],",
              "    \"RpK\", [L13 RPK],",
              "    \"RpS\", [L13 RPS],",
              "    \"WpS\", [L13 WPS]",
              ")"
            ],
            "formatString": "#,0.0",
            "lineageTag": "a58dafcb-08d2-4f5e-968a-98df1590e487",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Shipment L131",
            "expression": [
              "CALCULATE (",
              "    [Number of Shipments],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 14",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                <= EOMONTH (",
              "                    [Today],",
              "                    -1",
              "                )",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "db1ceeac-abfb-48bc-83cf-bb0f8f26c4ca",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Base Revenue for Shipment YTD/LM",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Period Filter'[Period] ),",
              "    \"YTD\", [Base Revenue YTD],",
              "    \"LM\", [Base Revenue LM]",
              ")"
            ],
            "formatString": "0.0",
            "lineageTag": "4c251781-8991-42cd-af26-9769807a4395",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Shipment  YTD/LM",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Period Filter'[Period] ),",
              "    \"YTD\", [Number of Shipments YTD2],",
              "    \"LM\", [Number of Shipments LM1]",
              ")"
            ],
            "formatString": "0.0",
            "lineageTag": "d18539e8-40a2-4b3b-86e5-bb0654ea7b07",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Shipment Band YTD",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Shipment Band Filter'[Filter] ),",
              "    \"Shipments\", [Number of Shipments YTD],",
              "    \"SpD\", [SpD YTD],",
              "    \"RpD\", [RpD YTD CUR],",
              "    \"RpK\", [RpK YTD],",
              "    \"RpS\", [RpS YTD],",
              "    \"WpS\", [WpS YTD]",
              ")"
            ],
            "formatString": "0.0",
            "lineageTag": "22d94baf-5ffa-4e6d-96ef-5c9059e5fd5f",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Shipment Band LM",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Shipment Band Filter'[Filter] ),",
              "    \"Shipments\", [Number of Shipments LM],",
              "    \"SpD\", [SpD LM],",
              "    \"RpD\", [RpD LM CUR],",
              "    \"RpK\", [RpK LM],",
              "    \"RpS\", [RpS LM],",
              "    \"WpS\", [WpS LM]",
              ")"
            ],
            "lineageTag": "0ab4f8e5-3846-44a6-ad43-df8ac39cfa23",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Shipment band  YTD/LM",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Period Filter'[Period] ),",
              "    \"YTD\", [Shipment Band YTD],",
              "    \"LM\", [Shipment Band LM]",
              ")"
            ],
            "formatString": "0.0",
            "lineageTag": "b31bf3f7-717a-433f-a371-81952f8b8bf5",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Shipment Band LYTD",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Shipment Band Filter'[Filter] ),",
              "    \"Shipments\", [Number of Shipments LYTD],",
              "    \"SpD\", [SpD LYTD],",
              "    \"RpD\", [RpD LYTD CUR],",
              "    \"RpK\", [RpK LYTD],",
              "    \"RpS\", [RpS LYTD],",
              "    \"WpS\", [WpS LYTD]",
              ")"
            ],
            "formatString": "0.0",
            "lineageTag": "bd1120be-dbd8-4e31-92f6-ac18033d8994",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Shipment Band YoY",
            "expression": "[Shipment Band YTD] - [Shipment Band LYTD]",
            "formatString": "0.0",
            "lineageTag": "60ac615f-bd86-471d-9032-09e05bcb3eea",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Shipment Band YoY%",
            "expression": [
              "VAR YoY = [Shipment Band YTD] - [Shipment Band LYTD]",
              "RETURN",
              "    DIVIDE (",
              "        YoY,",
              "        [Shipment Band YTD]",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "cce015dd-255d-46b8-bbc8-1e8d35ec0708",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Shipment Band LYLM",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Shipment Band Filter'[Filter] ),",
              "    \"Shipments\", [Number of Shipments LYLM],",
              "    \"SpD\", [SpD LYLM],",
              "    \"RpD\", [RpD LYLM CUR],",
              "    \"RpK\", [RpK LYLM],",
              "    \"RpS\", [RpS LYLM],",
              "    \"WpS\", [WpS LYLM]",
              ")"
            ],
            "lineageTag": "c01d6aa7-5bee-4e9f-b1df-b4044ea72af4",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Shipment Band Growth YOY%",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Shipment Band Filter'[Filter] ),",
              "    \"Shipments\",",
              "        ( [Number of Shipments YTD2] - [Number of Shipments LYTD2] ) / [Number of Shipments LYTD2],",
              "    \"SpD\",",
              "        ( [SpD YTD] - [SpD LYTD] ) / [SpD LYTD],",
              "    \"RpD\",",
              "        ( [RpD YTD CUR] - [RpD LYTD CUR] ) / [RpD LYTD CUR],",
              "    \"RpK\",",
              "        ( [RpK YTD] - [RpK LYTD] ) / [RpK LYTD],",
              "    \"RpS\",",
              "        ( [RpS YTD] - [RpS LYTD] ) / [RpS LYTD],",
              "    \"WpS\",",
              "        ( [WpS YTD] - [WpS LYTD] ) / [WpS LYTD]",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "35227a16-dac6-4687-aefe-f1be3056cd6b",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Shipment Band Growth LM %",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Shipment Band Filter'[Filter] ),",
              "    \"Shipments\",",
              "        ( [Number of Shipments LM1] - [Number of Shipments LYLM1] ) / [Number of Shipments LYLM1],",
              "    \"SpD\",",
              "        ( [SpD LM] - [SpD LYLM] ) / [SpD LYLM],",
              "    \"RpD\",",
              "        ( [RpD LM EUR] - [RpD LYLM CUR] ) / [RpD LYLM CUR],",
              "    \"RpK\",",
              "        ( [RpK LM] - [RpK LYLM] ) / [RpK LYLM],",
              "    \"RpS\",",
              "        ( [RpS LM] - [RpS LYLM] ) / [RpS LYLM],",
              "    \"WpS\",",
              "        ( [WpS LM] - [WpS LYLM] ) / [WpS LYLM]",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "b9fcda09-3eca-434b-b92d-b5d6525e1001",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Shipment Growth YoY  Variance %",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Period Filter'[Period] ),",
              "    \"YTD\", [Shipment Band Variance YoY%],",
              "    \"LM\", [Shipment Band Growth LM %]",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "676f6835-e21b-4c05-92c1-8c924e3e8a1d",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Shipment Band Variance YoY%",
            "expression": [
              "VAR YoY = ( [Shipment Band YTD] - [Shipment Band LYTD] ) / [Shipment Band LYTD]",
              "RETURN",
              "    YoY"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "416359f0-9b1a-45e9-9563-3111a867cddb",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Weight Band Measure",
        "lineageTag": "04a9b000-5f12-4f91-bbd0-1c57e188e732",
        "columns": [
          {
            "name": "Column1",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Column1",
            "lineageTag": "0c67a56c-d358-4035-accd-59822158210d",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Weight Band Measure-af7e8b4d-4b6d-467e-9560-48a842e21325",
            "mode": "import",
            "queryGroup": "Weight Band",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Weight L13",
            "expression": [
              "CALCULATE (",
              "    [Billed Weight KG],",
              "    FILTER (",
              "        DIM_PERIOD,",
              "        DIM_PERIOD[Billing Period Date]",
              "            > EOMONTH (",
              "                [Today],",
              "                - 14",
              "            )",
              "            && DIM_PERIOD[Billing Period Date]",
              "                <= EOMONTH (",
              "                    [Today],",
              "                    -1",
              "                )",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "0a260673-2c18-411c-9783-80236846ede0",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Weight Band L13 Months",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Weight Band Filter'[Filter] ),",
              "    \"Weight\", [Weight L13],",
              "    \"SpD\", [L13 SPD],",
              "    \"RpD\", [L13 RPD],",
              "    \"RpK\", [L13 RPK],",
              "    \"RpS\", [L13 RPS],",
              "    \"WpS\", [L13 WPS]",
              ")"
            ],
            "formatString": "#,0.0",
            "lineageTag": "5cbe8a00-f538-4b1d-800f-7b2361659f0b",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Weight YoY%",
            "expression": [
              "VAR YoY = [Billed Weight KG YTD] - [Billed Weight KG LYTD]",
              "RETURN",
              "    DIVIDE (",
              "        YoY,",
              "        [Billed Weight KG LYTD]",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "29027122-c0b4-446a-8f8a-ab73123b9336",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Weight MoM%",
            "expression": [
              "VAR YoY = [Billed Weight KG LM] - [Billed Weight KG LYLM]",
              "RETURN",
              "    DIVIDE (",
              "        YoY,",
              "        [Billed Weight KG LYLM]",
              "    )"
            ],
            "lineageTag": "28e47733-e222-4b8c-8d79-53bffe7c7f51",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Weight Growth %",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Period Filter'[Period] ),",
              "    \"YTD\", [Weight YoY%],",
              "    \"LM\", [Weight MoM%]",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "8360ee3a-574e-4ef5-82a9-e439c77fd7ab",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Base Revenue YTD/LM",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Period Filter'[Period] ),",
              "    \"YTD\", [Base Revenue YTD],",
              "    \"LM\", [Base Revenue LM]",
              ")"
            ],
            "formatString": "#,0.0",
            "lineageTag": "4697d4b8-6fc3-4969-a1b1-4a9e9b629922",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Weight YTD/LM",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Period Filter'[Period] ),",
              "    \"YTD\", [Billed Weight KG YTD],",
              "    \"LM\", [Billed Weight KG LM]",
              ")"
            ],
            "formatString": "0.0",
            "lineageTag": "8bf90b8b-eb69-47d6-b39e-02ac1c1240e4",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Weight Band YTD",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Weight Band Filter'[Filter] ),",
              "    \"Weight\", [Billed Weight KG YTD],",
              "    \"SpD\", [SpD YTD],",
              "    \"RpD\", [RpD YTD CUR],",
              "    \"RpK\", [RpK YTD],",
              "    \"RpS\", [RpS YTD],",
              "    \"WpS\", [WpS YTD]",
              ")"
            ],
            "formatString": "#,0.0",
            "lineageTag": "4bca8c6c-9e00-468f-bdc1-a2a15f15ab17",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Weight Band LYTD",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Weight Band Filter'[Filter] ),",
              "    \"Weight\", [Billed Weight KG LYTD],",
              "    \"SpD\", [SpD LYTD],",
              "    \"RpD\", [RpD LYTD CUR],",
              "    \"RpK\", [RpK LYTD],",
              "    \"RpS\", [RpS LYTD],",
              "    \"WpS\", [WpS LYTD]",
              ")"
            ],
            "formatString": "#,0.0",
            "lineageTag": "744aa7c5-3fdc-4c0d-84c6-7f94f1da003b",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Weight Band YoY%",
            "expression": [
              "VAR YoY = ( [Weight Band YTD] - [Weight Band LYTD] ) / [Weight Band LYTD]",
              "RETURN",
              "    YoY"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "9f140b02-ea8e-42b2-b3ab-2ca131f2b57d",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Weight Band YoY",
            "expression": "[Weight Band YTD] - [Weight Band LYTD]",
            "formatString": "#,0.0",
            "lineageTag": "1b5fcd85-969a-4944-a805-058d7e4f3a37",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Weight Band LM",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Weight Band Filter'[Filter] ),",
              "    \"Weight\", [Billed Weight KG LM],",
              "    \"SpD\", [SpD LM],",
              "    \"RpD\", [RpD LM CUR],",
              "    \"RpK\", [RpK LM],",
              "    \"RpS\", [RpS LM],",
              "    \"WpS\", [WpS LM]",
              ")"
            ],
            "lineageTag": "09a04b71-9e2e-4c88-a72f-75e55dbc095e",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Weight Band LYLM",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Weight Band Filter'[Filter] ),",
              "    \"Weight\", [_Billed Weight KG LYLM],",
              "    \"SpD\", [SpD LYLM],",
              "    \"RpD\", [RpD LYLM],",
              "    \"RpK\", [RpK LYLM],",
              "    \"RpS\", [RpS LYLM],",
              "    \"WpS\", [WpS LYLM]",
              ")"
            ],
            "lineageTag": "6e57f674-7121-451c-a721-e6a876762a55",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Weight Band Growth YOY%",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Weight Band Filter'[Filter] ),",
              "    \"Weight\",",
              "        ( [Billed Weight KG YTD] - [Billed Weight KG LYTD] ) / [Billed Weight KG LYTD],",
              "    \"SpD\",",
              "        ( [SpD YTD] - [SpD LYTD] ) / [SpD LYTD],",
              "    \"RpD\",",
              "        ( [RpD YTD CUR] - [RpD LYTD CUR] ) / [RpD LYTD CUR],",
              "    \"RpK\",",
              "        ( [RpK YTD] - [RpK LYTD] ) / [RpK LYTD],",
              "    \"RpS\",",
              "        ( [RpS YTD] - [RpS LYTD] ) / [RpS LYTD],",
              "    \"WpS\",",
              "        ( [WpS YTD] - [WpS LYTD] ) / [WpS LYTD]",
              ")"
            ],
            "lineageTag": "9c025a03-a8b3-4f97-b8d9-d13fe330639c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Weight Band Growth LM YOY%",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Weight Band Filter'[Filter] ),",
              "    \"Weight\",",
              "        ( [Billed Weight KG LM] - [_Billed Weight KG LYLM] ) / [_Billed Weight KG LYLM],",
              "    \"SpD\",",
              "        ( [SpD LM] - [SpD LYLM] ) / [SpD LYLM],",
              "    \"RpD\",",
              "        ( [RpD LM EUR] - [RpD LYLM] ) / [RpD LYLM],",
              "    \"RpK\",",
              "        ( [RpK LM] - [RpK LYLM] ) / [RpK LYLM],",
              "    \"RpS\",",
              "        ( [RpS LM] - [RpS LYLM] ) / [RpS LYLM],",
              "    \"WpS\",",
              "        ( [WpS LM] - [WpS LYLM] ) / [WpS LYLM]",
              ")"
            ],
            "lineageTag": "29ab1b65-a349-4aa3-8884-ea4643fc61d3",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Weight Growth LM/YOY%",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Period Filter'[Period] ),",
              "    \"YTD\", [Weight Band Growth YOY%],",
              "    \"LM\", [Weight Band Growth LM YOY%]",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "c6a701d5-4469-4aee-9cd0-6cb576e5e907",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          },
          {
            "name": "Weight Growth LM/YOY",
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'Period Filter'[Period] ),",
              "    \"YTD\", [Weight Band YTD],",
              "    \"LM\", [Weight Band LM]",
              ")"
            ],
            "formatString": "0.0",
            "lineageTag": "269f232f-dd24-4ec0-a9e0-8358a289d949",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Weight Band Filter",
        "lineageTag": "d3f1134b-1b89-4c56-bb54-02b2d35ca071",
        "columns": [
          {
            "name": "Filter",
            "dataType": "string",
            "sourceColumn": "Filter",
            "sortByColumn": "Value",
            "lineageTag": "926926be-f81d-4abb-8642-f46c6fa96d92",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Value",
            "dataType": "int64",
            "sourceColumn": "Value",
            "formatString": "0",
            "lineageTag": "a9c0c5cc-d03f-4426-ac04-b6a921c737d0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "FilterFullName",
            "dataType": "string",
            "sourceColumn": "FilterFullName",
            "lineageTag": "1bc0de1d-bbf9-40c6-a538-c60bd327be91",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Weight Band Filter-2df55b9d-1d06-408f-99a7-6053de8bf9f5",
            "mode": "import",
            "queryGroup": "Static Filter Table",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WCk/NTM8oUdJRMgRiKCdWJ1opuMAFKGAExMEZmQW5qXklCgGpRQouiZVg6SCwtDEQB6WWpeaVpqLJegNlTNBkvTNz8qHSwUApUzRpmD1gJeFgJWZwN6GpiAUA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Filter = _t, Value = _t, FilterFullName = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Filter\", type text}, {\"Value\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Weight Break Group",
        "lineageTag": "46efff9b-f82c-490c-997e-50f7cb15d4af",
        "columns": [
          {
            "name": "Weight Break Group Desc",
            "dataType": "string",
            "sourceColumn": "Weight Break Group Desc",
            "sortByColumn": "Value",
            "lineageTag": "5b49c02d-5fbc-4cfa-be98-a0a6b3271ade",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Value",
            "dataType": "int64",
            "sourceColumn": "Value",
            "formatString": "0",
            "lineageTag": "f1eb7035-363d-4f02-b026-6b0880eb1a2f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Weight Band",
            "dataType": "string",
            "sourceColumn": "Weight Band",
            "sortByColumn": "Value",
            "lineageTag": "3dbf4f65-08f0-46e4-bbc1-855223b812e2",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Weight Break Group-f4112932-acf2-4148-95bf-f7d54afab721",
            "mode": "import",
            "queryGroup": "Static Filter Table",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"ZY87EoMwDESvwqgGZ40gDmUuwAWMq0xqGrh/JJlPwC40u0+rnXGM1AzHczqqZa4aOACeappWgD8Q5SnVkaDr1vUC/mRrO9FypJT14GbZMpyblQajN99ZKpyUobgA/dZ2cg/kwgI9LWs/+e7s6oIlxsdbdJ4vSukH\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Weight Break Group Desc\" = _t, #\"Weight Band\" = _t, Value = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Weight Break Group Desc\", type text}, {\"Value\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Shipment Range",
        "lineageTag": "8b00a137-25b0-4960-91d7-12ba8f047c78",
        "columns": [
          {
            "name": "Shipments",
            "dataType": "string",
            "sourceColumn": "Shipments",
            "sortByColumn": "Values",
            "lineageTag": "d6900f81-411c-4a63-afd0-3dc12be396e4",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Values",
            "dataType": "int64",
            "sourceColumn": "Values",
            "formatString": "0",
            "lineageTag": "f25f36e6-1085-4058-9a86-908d2e087c03",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Shipment Range-fe942e8d-4305-4043-8c76-7b71e7ac41c3",
            "mode": "import",
            "queryGroup": "Static Filter Table",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"HcqxDcBACATBXi71Ix28oRlM5Brcv3myHWkz8XzkfokFRa0ExbttOsQO9sBClOe7h0oVH/u4+2oEqn4=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Shipments = _t, Values = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Shipments\", type text}, {\"Values\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Loyalty_Sort",
        "lineageTag": "2f3824c5-ef59-4850-97bc-1c94c8de712f",
        "columns": [
          {
            "name": "Strategic Loyalty RM",
            "dataType": "string",
            "sourceColumn": "Strategic Loyalty RM",
            "lineageTag": "3799695c-f87a-4cc6-bfea-1338e0b455e2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Value",
            "dataType": "int64",
            "sourceColumn": "Value",
            "formatString": "0",
            "lineageTag": "326c48ee-8d6d-4d46-ac16-bdfeb81f9604",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Loyalty_Sort-0b92d244-f500-4f7a-be08-4b09587f69b0",
            "mode": "import",
            "queryGroup": "Loyalty",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WcskvzyspSkxJLVLSUTJUitWJVvLJLy4BcozAHL/UciDbGMwOSk1PzMxLTQEKmIAFgksSk3JSgVxTMDe0AG6SmVJsLAA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Strategic Loyalty RM\" = _t, Value = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Strategic Loyalty RM\", type text}, {\"Value\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "New/Regained",
        "lineageTag": "ccec6fff-66d6-47d0-b72b-58de28aeaf80",
        "columns": [
          {
            "name": "Column1",
            "dataType": "string",
            "sourceColumn": "Column1",
            "lineageTag": "fe441a04-5b04-4512-8129-f43496ede779",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "New/Regained-29338a3d-6609-4391-a973-dbeac15059b9",
            "mode": "import",
            "queryGroup": "Static Filter Table",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45W8kstj8lTitWJVgpKTU/MzEtNAXFjAQ==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "FTB Filter",
        "lineageTag": "badce284-f217-44dc-99bb-4d5533ca2a91",
        "columns": [
          {
            "name": "Selected Value",
            "dataType": "string",
            "sourceColumn": "Selected Value",
            "lineageTag": "e335f181-4d6e-4700-9a7e-b1bd00f727df",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Selected Trend Lines",
            "dataType": "string",
            "sourceColumn": "Selected Trend Lines",
            "lineageTag": "b465f58c-b09f-4926-a49d-0368ed9c9a66",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Selected Growth",
            "dataType": "string",
            "sourceColumn": "Selected Growth",
            "lineageTag": "622a5d97-6183-42d5-b468-4fc315c8914c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Selected Loyalty Status",
            "dataType": "string",
            "sourceColumn": "Selected Loyalty Status",
            "lineageTag": "952ed9ed-474e-4b49-8385-711cac41982e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ID",
            "dataType": "int64",
            "sourceColumn": "ID",
            "formatString": "0",
            "lineageTag": "28f4b487-00f9-4587-95f8-c11c2eb5f744",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "FTB Filter-59189d8a-6831-4d27-9968-9365a6a5d3ab",
            "mode": "import",
            "queryGroup": "Static Filter Table",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"dZC9DoMwDIRfxcrM0v+9ldqFCZA6IAakWiVSSRAxrXj7eqAJBHeKc2fdZ7ss1UYl6lqc3fRA0aN5QKoNeunW2w81v19qx/pFI+RU0+BUlZRqy16GbzQDQoc9cN9aiZJj10NiQ+DtuC1vdNeiITevI0bQfXqQhNx9wM8GkedezSvkHdi+o342BKFaxk2iT5v+QtiR3cvgyLZ8mAyJl9DWgKwuIUKDBwqeAD/NFvWNkvbnWgJ4bcXc6gs=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ID = _t, #\"Selected Value\" = _t, #\"Selected Trend Lines\" = _t, #\"Selected Growth\" = _t, #\"Selected Loyalty Status\" = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Selected Value\", type text}, {\"ID\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "FTB Customer Summary Filter",
        "lineageTag": "7fb0c11c-a950-461d-b511-7e5810384584",
        "columns": [
          {
            "name": "Column1",
            "dataType": "string",
            "sourceColumn": "Column1",
            "lineageTag": "a61f723c-6eda-40fb-8900-e4baaf8b070f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "FTB Customer Summary Filter-a0043e6b-8e49-4aea-ab1e-93dcb97c593f",
            "mode": "import",
            "queryGroup": "Static Filter Table",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WcgtxKlYILs3NTSyqVIrViVZyLi0uyc9NLUIIxgIA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "FTB Customer Summary Selection",
            "expression": [
              "IF (",
              "    SELECTEDVALUE ( 'FTB Customer Summary Filter'[Column1] ) = \"FTBs Summary\",",
              "    1,",
              "    0",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "f02e88dc-c6bb-434a-89fc-1ac60762ea96"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Period Filter",
        "lineageTag": "6d4b2428-6a31-4d8f-9b47-0f51afb3ea4a",
        "columns": [
          {
            "name": "Period",
            "dataType": "string",
            "sourceColumn": "Period",
            "lineageTag": "57420d23-b899-4b0a-9dac-73879b6dec7c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Value",
            "dataType": "int64",
            "sourceColumn": "Value",
            "formatString": "0",
            "lineageTag": "2ea50c87-06d9-4c0f-8c0a-7d5067c938d2",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Period Filter-de54b01a-724f-4766-a280-e9decd1d5480",
            "mode": "import",
            "queryGroup": "Static Filter",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WigxxUdJRMlSK1YlW8vEFMo2UYmMB\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t, Value = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Value\", Int64.Type}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Column1\", \"Period\"}})",
                "in",
                "    #\"Renamed Columns\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "ShortMonthMapping",
        "lineageTag": "51a8148e-2ced-4199-b1a6-f781b857374c",
        "columns": [
          {
            "name": "Month",
            "dataType": "string",
            "sourceColumn": "Month",
            "sortByColumn": "S.No",
            "lineageTag": "2ef73dcb-8eb4-4c4a-931d-e7b7c2e17388",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "S.No",
            "dataType": "int64",
            "sourceColumn": "S.No",
            "formatString": "0",
            "lineageTag": "33dcc81f-2239-44d8-91c6-8d52a9f1140b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "ShortMonthMapping-ac10e760-ac16-4c71-b0a8-469157a33b5a",
            "mode": "import",
            "queryGroup": "Static Filter",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45W8krMU9JRMlSK1YlWcktNArKNwGzfxCIg2xjMdiwAsU2g4pVAtimY7VUK0msGZecA2eYQ9aXpQLYFmB2cWgBkW4LZ/sklILsMwBy//DIQB2KzS2oyiAO0OhYA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Month = _t, S.No = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Month\", type text}, {\"S.No\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Rev/Ship/Weight Filter",
        "lineageTag": "89d35ec8-5d35-4480-91e7-13df6dffa28f",
        "columns": [
          {
            "name": "Filter",
            "dataType": "string",
            "sourceColumn": "Filter",
            "sortByColumn": "Value",
            "lineageTag": "1d84aad6-e1b7-4e7f-8d6b-cae557dd9f73",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Value",
            "dataType": "int64",
            "sourceColumn": "Value",
            "formatString": "0",
            "lineageTag": "00f552e7-d01d-4d88-903f-d41429594b89",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Title",
            "dataType": "string",
            "sourceColumn": "Title",
            "lineageTag": "91482bc2-ab0a-4ce5-b2a7-15747d142722",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Rev/Ship/Weight Filter-0e0934ae-570a-40df-95ad-523c98948980",
            "mode": "import",
            "queryGroup": "Static Filter",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WckosTlUISi1LzStNVdJRMgRiFKFYnWilkPySxBwkRUZAjCoGUhWckVmQm5pXApQ0hiuAC4JUhKdmpmeA5E3g8lAhkKxzaXFJfm5qUTFQ0hSuACEaGwsA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Filter = _t, Value = _t, Title = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Filter\", type text}, {\"Value\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ]
      },
      {
        "name": "Currency Filter",
        "lineageTag": "b4375e46-7994-4339-a9d1-b4bdfc7e8b2f",
        "columns": [
          {
            "name": "LCY/BER",
            "dataType": "string",
            "sourceColumn": "LCY/BER",
            "lineageTag": "2515f4bd-7d94-4bd7-a1df-043994cd534f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "value",
            "dataType": "int64",
            "sourceColumn": "value",
            "formatString": "0",
            "lineageTag": "94a70537-83c9-468d-972b-e29532e64392",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Currency Filter-66b4183b-eb8a-43fb-b32c-8a83276b2882",
            "mode": "import",
            "queryGroup": "Static Filter",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45W8slPTsxRcC4tKkrNS65U0lEyVIrViVZycg1S0FUIDXYBihghibiWFuUDhYyVYmMB\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"LCY/BER\" = _t, value = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"LCY/BER\", type text}, {\"value\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "VW_DIM_CUSTOMER",
        "lineageTag": "6828c042-8bce-406d-a2a8-f5e7d3eea2fa",
        "columns": [
          {
            "name": "Customer GSFA ID",
            "dataType": "string",
            "sourceColumn": "Customer GSFA ID",
            "lineageTag": "66edb24e-8576-4122-8f24-c06c18707eae",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Customer Name",
            "dataType": "string",
            "sourceColumn": "Customer Name",
            "lineageTag": "27c81e3c-5db5-4873-ab13-649990cf6274",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "FTB Month",
            "dataType": "dateTime",
            "sourceColumn": "FTB Month",
            "formatString": "dd-mm-yyyy",
            "lineageTag": "ea00b49f-9ed4-4a48-a058-65c42595e2cc",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "62e3c613-ad42-43cb-b656-471512d81c70",
                "defaultHierarchy": {
                  "table": "LocalDateTable_ffde379d-04ff-4188-80bf-e4a99402391c",
                  "hierarchy": "Date Hierarchy"
                },
                "isDefault": true
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ]
          },
          {
            "name": "Tactical Loyalty RM",
            "dataType": "string",
            "sourceColumn": "Tactical Loyalty RM",
            "lineageTag": "2838370c-c481-4d44-b139-5845af83dbe0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Strategic Loyalty RM",
            "dataType": "string",
            "sourceColumn": "Strategic Loyalty RM",
            "lineageTag": "4c2cad19-b566-4e88-87c3-a9842fca36ea",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "FTB Reason",
            "dataType": "string",
            "sourceColumn": "FTB Reason",
            "lineageTag": "1d5d58e8-cb06-4a25-ab82-c6a58817c64e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Days since Last Shipment",
            "dataType": "int64",
            "sourceColumn": "Days since Last Shipment",
            "formatString": "0",
            "lineageTag": "58bb85c3-6a27-4244-99a3-4fa95978bb02",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Sales Channel",
            "dataType": "string",
            "sourceColumn": "Sales Channel",
            "lineageTag": "481cd066-5caf-4b0b-8136-d171a327ac1e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "INDUSTRY_SECTOR_NAME",
            "dataType": "string",
            "sourceColumn": "INDUSTRY_SECTOR_NAME",
            "lineageTag": "7330b682-c56e-4810-a3af-6625fb718221",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "FTB Mon-YY",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "FORMAT(VW_DIM_CUSTOMER[FTB Month],\"MMM\")&\"-\"&FORMAT(VW_DIM_CUSTOMER[FTB Month],\"YY\")",
            "lineageTag": "43825f59-f93a-40ba-915f-ff87b6280f37",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "FTB Year",
            "dataType": "string",
            "expression": "FORMAT(VW_DIM_CUSTOMER[FTB Month],\"YYYY\")",
            "lineageTag": "4e130b6d-b1ae-4ff8-8a2f-bf8ffc1ef93a",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "FTB_Month",
            "dataType": "string",
            "expression": "FORMAT(VW_DIM_CUSTOMER[FTB Month],\"MM\")",
            "lineageTag": "698503c2-2097-4f9d-a78b-f04b8f25a767",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "FTB Date",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "expression": "IF(VW_DIM_CUSTOMER[FTB Month]=DATE(1900,01,01),BLANK(),VW_DIM_CUSTOMER[FTB Month])",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "e8066a07-8dea-463e-af63-b3fec0a6fa5a",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "a52e7797-9f0f-4e4b-bb89-f90356dca4f6",
                "defaultHierarchy": {
                  "table": "LocalDateTable_64307048-556d-43e0-a74e-929e596a5189",
                  "hierarchy": "Date Hierarchy"
                },
                "isDefault": true
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Active_Inactive",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "IF ( [Base Revenue EUR YTD] > 0, \"Active\", \"Inactive\" )",
              ""
            ],
            "lineageTag": "c28924b6-6109-49e2-b723-8b625431b8d4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "VW_DIM_CUSTOMER-0c8c39c7-0f2b-41fe-8686-9d7f91729f11",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "// Check the Country Parameter",
                "    Country = ",
                "  if P_Country = \"All\" then \" \"",
                "      else",
                "    if ",
                "    //check to see if the parameter is a list",
                "      Type.Is(",
                "        Value.Type(#\"P_Country\"), ",
                "        List.Type",
                "      ) then ",
                "        //if it is a list",
                "         if List.Contains(P_Country, \"All\") then \" \"",
                "      else",
                "        let",
                "          //add single quotes around each value in the list",
                "          AddSingleQuotes = List.Transform(",
                "              #\"P_Country\", ",
                "              each \"'\" & _ & \"'\"",
                "            ),",
                "          //then turn it into a comma-delimited list",
                "          DelimitedList = Text.Combine(",
                "              AddSingleQuotes, ",
                "              \",\"",
                "            )",
                "        in",
                "          \"\"\"Sales Function - Country Code\"\" in (\" & DelimitedList & \")\" ",
                "    else ",
                "      //if the parameter isn't a list",
                "      //just add single quotes around the parameter value",
                "      \"\"\"Sales Function - Country Code\"\" in (\" & \"'\" & #\"P_Country\" & \"'\" & \")\",",
                "",
                "        ",
                "    Source = Value.NativeQuery(Snowflake.Databases(\"el02508.west-europe.azure.snowflakecomputing.com\",\"OUT_ANALYTICS\"){[Name=\"PROD_T5_PRESENTATION\"]}[Data], \"SELECT Distinct #(lf)  C.\"\"Customer GSFA ID\"\", #(lf)  C.\"\"Customer Name\"\", #(lf)  C.\"\"FTB Month\"\", #(lf)  C.\"\"Tactical Loyalty RM\"\", #(lf)  C.\"\"Strategic Loyalty RM\"\", #(lf)  C.\"\"FTB Reason\"\", #(lf)  C.\"\"Days since Last Shipment\"\", #(lf)  C.\"\"Sales Channel\"\"#(lf),C.\"\"Industry Code\"\" as Industry_Sector_Name",
                "     FROM #(lf)  \"\"PROD_T5_PRESENTATION\"\".\"\"START_FINANCE\"\".\"\"VW_FCT_COMMERCIAL_SUMMARY\"\" F #(lf)  JOIN \"\"PROD_T5_PRESENTATION\"\".\"\"START_FINANCE\"\".\"\"VW_DIM_PERIOD\"\" P ON F.\"\"Billing Period Date\"\" = P.\"\"Billing Period Date\"\" #(lf)  JOIN \"\"PROD_T5_PRESENTATION\"\".\"\"START_FINANCE\"\".\"\"VW_DIM_PRODUCT\"\" PR on F.\"\"Product SK\"\" = PR.\"\"Product SK\"\" #(lf)  JOIN \"\"PROD_T5_PRESENTATION\"\".\"\"START_FINANCE\"\".\"\"VW_DIM_ACCOUNT\"\" A on F.\"\"Account SK\"\" = A.\"\"Account SK\"\" #(lf)  JOIN \"\"PROD_T5_PRESENTATION\"\".\"\"CUSTOMER360\"\".\"\"VW_DIM_CUSTOMER\"\" C ON A.\"\"Customer GSFA ID\"\" = C.\"\"Customer GSFA ID\"\" #(lf)  JOIN \"\"PROD_T5_PRESENTATION\"\".\"\"START_FINANCE\"\".\"\"VW_DIM_SALES_FUNCTION\"\" S ON F.\"\"Sales Territory SK\"\" = S.\"\"Sales Territory SK\"\" #(lf)",
                "    WHERE #(lf) \"& Country &\" #(lf) \", null, [EnableFolding=true]),",
                "    #\"Capitalized Each Word\" = Table.TransformColumns(Source,{{\"Customer Name\", Text.Proper, type text}})",
                "in",
                "    #\"Capitalized Each Word\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Total Customer",
            "expression": [
              "VAR _Result =",
              "    DISTINCTCOUNT ( VW_DIM_CUSTOMER[Customer GSFA ID] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( _Result ),",
              "        0,",
              "        _Result",
              "    )"
            ],
            "formatString": "#,0",
            "lineageTag": "6d4a276a-4b8f-4b87-9a3e-703ce14e810e",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ]
      },
      {
        "name": "LocalDateTable_ffde379d-04ff-4188-80bf-e4a99402391c",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "2aab3d39-b47c-4dff-a149-7b71916e1cb1",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "fecf199d-dd2e-43eb-9d46-ab771e604415",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "aafe99b1-f21f-47a1-8289-e91a1663b756",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "8f68af62-5590-45c1-b3f4-01d0c63963af",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "dc4acc7b-bdea-4329-b40f-9da9290dbcb1",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "lineageTag": "6341ece1-d343-4412-ae81-9e80899c5cb2",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "8b36fb6c-08d9-4939-a2cb-8f4a6d3dd0e5",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "8fbf8b1d-d3ad-4555-98b0-319de2cb68e4",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_ffde379d-04ff-4188-80bf-e4a99402391c-2b9f7f1f-27fc-4793-bd19-2ae2d1df32c2",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('VW_DIM_CUSTOMER'[FTB Month])), 1, 1), Date(Year(MAX('VW_DIM_CUSTOMER'[FTB Month])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "d8663969-6b32-49d2-841b-c3fcda8d2150",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "52f86532-89af-43f3-af5f-7d9debd05b5e"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "a58ee2ec-6462-47ef-a26c-3228eee04a0d"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "63a888c6-6c43-4e2f-8430-623a6bd6f506"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "56904413-c4b0-4268-8807-17cf75056588"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "DIM_SALES_FUNCTION",
        "lineageTag": "bcc3e009-0fb4-4920-b2a9-89c05787022c",
        "columns": [
          {
            "name": "Sales Function - Country Code",
            "dataType": "string",
            "sourceColumn": "Sales Function - Country Code",
            "lineageTag": "ee6b0e00-ca61-4687-a32d-f046bda2a6c7",
            "isDefaultLabel": true,
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Sales Function - Region Code",
            "dataType": "string",
            "sourceColumn": "Sales Function - Region Code",
            "lineageTag": "6db2ec1c-430f-415e-8dfc-6e1bb4579a37",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Sales Territory SK",
            "dataType": "string",
            "sourceColumn": "Sales Territory SK",
            "lineageTag": "765ba862-f075-4a50-b7b9-3ee6bfdc9d20",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Sales Manager Name",
            "dataType": "string",
            "sourceColumn": "Sales Manager Name",
            "lineageTag": "153742d8-c505-4bbc-bef9-9b47dd619cd7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Sales Person Name",
            "dataType": "string",
            "sourceColumn": "Sales Person Name",
            "lineageTag": "2477bf6f-2fbb-473a-80a5-e6ebd871bd2e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Owner Region Code",
            "dataType": "string",
            "sourceColumn": "Owner Region Code",
            "lineageTag": "11836a72-6ad6-42d5-8726-c1fd20df9adb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Owner Region Name",
            "dataType": "string",
            "sourceColumn": "Owner Region Name",
            "lineageTag": "679949ff-8141-498f-8ea8-b7db2e355357",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Owner Country Code",
            "dataType": "string",
            "sourceColumn": "Owner Country Code",
            "lineageTag": "65fb6c35-9bb1-4171-8c14-35bb485d6794",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Owner Country Name",
            "dataType": "string",
            "sourceColumn": "Owner Country Name",
            "lineageTag": "d5ef0c42-59a1-4741-83e1-7753c2b19439",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "CT_SK",
            "dataType": "string",
            "sourceColumn": "CT_SK",
            "lineageTag": "a5bfc339-0949-4d80-8672-4a5c0f43a363",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DIM_SALES_FUNCTION-838be8f7-c7c9-46ad-ba09-46999d6bd7d8",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "// Check the Country Parameter",
                "    Country = ",
                "  if P_Country = \"All\" then \" \"",
                "      else",
                "    if ",
                "    //check to see if the parameter is a list",
                "      Type.Is(",
                "        Value.Type(#\"P_Country\"), ",
                "        List.Type",
                "      ) then ",
                "        //if it is a list",
                "         if List.Contains(P_Country, \"All\") then \" \"",
                "      else",
                "        let",
                "          //add single quotes around each value in the list",
                "          AddSingleQuotes = List.Transform(",
                "              #\"P_Country\", ",
                "              each \"'\" & _ & \"'\"",
                "            ),",
                "          //then turn it into a comma-delimited list",
                "          DelimitedList = Text.Combine(",
                "              AddSingleQuotes, ",
                "              \",\"",
                "            )",
                "        in",
                "          \"\"\"Sales Function - Country Code\"\" in (\" & DelimitedList & \")\" ",
                "    else ",
                "      //if the parameter isn't a list",
                "      //just add single quotes around the parameter value",
                "      \"\"\"Sales Function - Country Code\"\" in (\" & \"'\" & #\"P_Country\" & \"'\" & \")\",",
                "",
                "    Source = Value.NativeQuery(Snowflake.Databases(\"el02508.west-europe.azure.snowflakecomputing.com\",\"OUT_ANALYTICS\"){[Name=\"PROD_T5_PRESENTATION\"]}[Data], \"Select #(lf)  A.\"\"Sales Function - Country Code\"\", #(lf)  A.\"\"Sales Function - Region Code\"\", #(lf)  A.\"\"Sales Territory SK\"\", #(lf)  A.\"\"Sales Manager Name\"\", #(lf)  A.\"\"Sales Person Name\"\",#(lf)  (A.\"\"Sales Function - Country Code\"\"||A.\"\"Sales Function - Sales Territory Code\"\") AS CT_sk, B.\"\"Owner Region Code\"\",#(lf)B.\"\"Owner Region Name\"\",#(lf)B.\"\"Owner Country Code\"\",#(lf)B.\"\"Owner Country Name\"\"#(lf)From #(lf)  \"\"PROD_T5_PRESENTATION\"\".\"\"START_FINANCE\"\".\"\"VW_DIM_SALES_FUNCTION\"\" A#(lf)  inner join \"\"PROD_T5_PRESENTATION\"\".\"\"START_FINANCE\"\".\"\"VW_DIM_GEOGRAPHY_OWNER\"\" B#(lf)  on A.\"\"Sales Function - Country Code\"\" = B.\"\"Owner Country Code\"\"",
                "    where \"& Country &\"\", null, [EnableFolding=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Sales Manager Name\", type text}, {\"Sales Person Name\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "DIM_WEIGHT_BREAK",
        "lineageTag": "8545f9ca-11d1-4c06-8569-a103c9731e21",
        "columns": [
          {
            "name": "Weight Break ID",
            "dataType": "double",
            "sourceColumn": "Weight Break ID",
            "lineageTag": "c61763e3-2e27-4fac-b3df-0993c3975a79",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Weight Break Code",
            "dataType": "string",
            "sourceColumn": "Weight Break Code",
            "lineageTag": "728bbb70-7f4e-4697-8024-4c5cba9a7d6f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Weight Break Desc",
            "dataType": "string",
            "sourceColumn": "Weight Break Desc",
            "lineageTag": "e9a160eb-6698-4583-be7a-d80b0f85bd51",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Weight Break Group Desc",
            "dataType": "string",
            "sourceColumn": "Weight Break Group Desc",
            "lineageTag": "ff8caaa7-23ee-4a95-a549-0c4567362ae2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DIM_WEIGHT_BREAK-67381be1-9323-4787-a4cb-8de32196b15f",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Value.NativeQuery(Snowflake.Databases(\"el02508.west-europe.azure.snowflakecomputing.com\",\"OUT_ANALYTICS\"){[Name=\"PROD_T5_PRESENTATION\"]}[Data], \"Select #(lf)\"\"Weight Break ID\"\",#(lf)\"\"Weight Break Code\"\",#(lf)\"\"Weight Break Desc\"\",#(lf)\"\"Weight Break Group Desc\"\"#(lf)From \"\"PROD_T5_PRESENTATION\"\".\"\"START_FINANCE\"\".\"\"VW_DIM_WEIGHT_BREAK\"\"\", null, [EnableFolding=true])",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "DIM_WORK_DAYS_GEO",
        "lineageTag": "de2350ee-c4d5-4ce7-ba77-e2c5c01d1d0e",
        "columns": [
          {
            "name": "GEO CODE",
            "dataType": "string",
            "sourceColumn": "GEO CODE",
            "lineageTag": "bdf63691-7ca3-4b5f-9335-b9b9bdfdd97d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "GEO TYPE",
            "dataType": "string",
            "sourceColumn": "GEO TYPE",
            "lineageTag": "0765f940-ffcb-4ab0-bc88-fae653863208",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "GEO TYPE DESCRIPTION",
            "dataType": "string",
            "sourceColumn": "GEO TYPE DESCRIPTION",
            "lineageTag": "a55866a2-57a0-4198-b778-5e3e30b8419d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Billing Period Date",
            "dataType": "dateTime",
            "sourceColumn": "Billing Period Date",
            "formatString": "Long Date",
            "lineageTag": "6289d5cf-4367-4d42-9b35-20996f7c6ce1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Number of Working Days",
            "dataType": "double",
            "sourceColumn": "Number of Working Days",
            "lineageTag": "3534f182-82eb-4f98-879b-ab23bd1757ff",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DIM_WORK_DAYS_GEO-fd15e530-8f3f-4f1b-b338-afe3877d57e0",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Value.NativeQuery(Snowflake.Databases(\"el02508.west-europe.azure.snowflakecomputing.com\",\"OUT_ANALYTICS\"){[Name=\"PROD_T5_PRESENTATION\"]}[Data], \"Select  #(lf)\"\"GEO CODE\"\",#(lf)\"\"GEO TYPE\"\",#(lf)\"\"GEO TYPE DESCRIPTION\"\",#(lf)\"\"Billing Period Date\"\",#(lf)\"\"Number of Working Days\"\"#(lf)From \"\"PROD_T5_PRESENTATION\"\".\"\"START_FINANCE\"\".\"\"VW_DIM_WORK_DAYS_GEO\"\"\", null, [EnableFolding=true])",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "DIM_GEOGRAPHY_OWNER",
        "lineageTag": "fbd9e890-784a-4d22-8f7a-426f99ffc937",
        "columns": [
          {
            "name": "Owner Region Code",
            "dataType": "string",
            "sourceColumn": "Owner Region Code",
            "lineageTag": "8905a4e9-614f-4263-b73a-801658d6dd68",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Owner Region Name",
            "dataType": "string",
            "sourceColumn": "Owner Region Name",
            "lineageTag": "d973ccf2-612f-4d90-a625-819053a6e2d2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Owner Country Code",
            "dataType": "string",
            "sourceColumn": "Owner Country Code",
            "lineageTag": "e960ced8-90da-41ed-8c07-eee25b0a2ea3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Owner Country Name",
            "dataType": "string",
            "sourceColumn": "Owner Country Name",
            "lineageTag": "e2b4263b-f0fc-47f2-99c8-0dbb9c82a5bc",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DIM_GEOGRAPHY_OWNER-f749cd97-9a2c-4598-9fcf-ad558087ff33",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Value.NativeQuery(Snowflake.Databases(\"el02508.west-europe.azure.snowflakecomputing.com\",\"OUT_ANALYTICS\"){[Name=\"PROD_T5_PRESENTATION\"]}[Data], \"Select  #(lf)\"\"Owner Region Code\"\",#(lf)\"\"Owner Region Name\"\",#(lf)\"\"Owner Country Code\"\",#(lf)\"\"Owner Country Name\"\"#(lf)From \"\"PROD_T5_PRESENTATION\"\".\"\"START_FINANCE\"\".\"\"VW_DIM_GEOGRAPHY_OWNER\"\"\", null, [EnableFolding=true])",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "DIM_PRODUCT",
        "lineageTag": "8a9e1781-b0e1-49fd-9037-cfdcc38c2f44",
        "columns": [
          {
            "name": "Product SK",
            "dataType": "string",
            "sourceColumn": "Product SK",
            "lineageTag": "2b09ee2a-04f7-492a-abcd-34ad766aa6dd",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Main Product Category Code",
            "dataType": "string",
            "sourceColumn": "Main Product Category Code",
            "lineageTag": "bca1b82a-34d3-47f0-a727-5197afc7b138",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Product Code",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "SWITCH(DIM_PRODUCT[Main Product Category Code],",
              "\"TDI\",\"TDI\",",
              "\"TDD\",\"TDD\",",
              "\"DDI\",\"DDI\",",
              "\"DDD\",\"DDD\",",
              "\"SDI\",\"SDI\",",
              "\"SDD\",\"SDD\",\"OTHERS\")"
            ],
            "lineageTag": "52e9a39a-a421-4c22-9481-18d87a260930",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DIM_PRODUCT-4f27244e-cdda-4b70-9226-59e33b4afa23",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Value.NativeQuery(Snowflake.Databases(\"el02508.west-europe.azure.snowflakecomputing.com\",\"OUT_ANALYTICS\"){[Name=\"PROD_T5_PRESENTATION\"]}[Data], \"Select  #(lf)\"\"Product SK\"\",#(lf)\"\"Main Product Category Code\"\"#(lf)From \"\"PROD_T5_PRESENTATION\"\".\"\"START_FINANCE\"\".\"\"VW_DIM_PRODUCT\"\"\", null, [EnableFolding=true])",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "DIM_PERIOD",
        "lineageTag": "9c471a7f-6d79-4dcf-8024-b5b6d6131f71",
        "columns": [
          {
            "name": "Billing Cycle",
            "dataType": "string",
            "sourceColumn": "Billing Cycle",
            "lineageTag": "636c276e-490b-4d93-ac91-edeb673eab18",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Billing Year",
            "dataType": "double",
            "sourceColumn": "Billing Year",
            "lineageTag": "fb0b4246-5b97-4a3a-8933-f1f2e86741b9",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Billing Quarter",
            "dataType": "double",
            "sourceColumn": "Billing Quarter",
            "lineageTag": "63ad1436-3146-46d9-86b4-10045235a1da",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Billing Month",
            "dataType": "double",
            "sourceColumn": "Billing Month",
            "lineageTag": "90b6865d-6d00-41eb-956c-58b08b2e31d7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Billing Month Code",
            "dataType": "string",
            "sourceColumn": "Billing Month Code",
            "lineageTag": "991c2405-087d-4b67-ad82-869afab29a48",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Billing Month Name",
            "dataType": "string",
            "sourceColumn": "Billing Month Name",
            "lineageTag": "d188e217-03c8-4da2-ac18-50d1b32db3cb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Billing Period Date",
            "dataType": "dateTime",
            "sourceColumn": "Billing Period Date",
            "formatString": "Long Date",
            "lineageTag": "59581dc3-037c-49c4-8b93-8122121bcc12",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "f5b0fbd9-88d9-4c0f-8679-fdcc340eb99d",
                "defaultHierarchy": {
                  "table": "LocalDateTable_ddc0fcbc-9037-43a1-8c8e-f9bd1183ac90",
                  "hierarchy": "Date Hierarchy"
                },
                "isDefault": true
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Billing Day",
            "dataType": "double",
            "sourceColumn": "Billing Day",
            "lineageTag": "8d756fa8-929d-4ebd-91d1-9aa6f4a4a452",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Billing Days in Month",
            "dataType": "double",
            "sourceColumn": "Billing Days in Month",
            "lineageTag": "507fd21a-e974-400a-8f71-268f87a0708c",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Billing MMDDYYYY",
            "dataType": "string",
            "sourceColumn": "Billing MMDDYYYY",
            "lineageTag": "98c31b09-634d-4d3e-9667-67ee888046fd",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Billing MON-YY",
            "dataType": "string",
            "sourceColumn": "Billing MON-YY",
            "sortByColumn": "SortHelper",
            "lineageTag": "1ea7bcb6-9b2b-41f3-92e4-957f4ea56599",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Billing YYYYMMDD",
            "dataType": "string",
            "sourceColumn": "Billing YYYYMMDD",
            "lineageTag": "3aa4ce0f-fba2-41d2-922f-af666d213a5c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Billing Relative Year",
            "dataType": "double",
            "sourceColumn": "Billing Relative Year",
            "lineageTag": "d1e94898-b76b-4462-9102-156be34cfa74",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Billing YTD",
            "dataType": "string",
            "sourceColumn": "Billing YTD",
            "lineageTag": "ede8d39c-0af4-4412-a329-948f52f9a89d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Billing LYTD",
            "dataType": "string",
            "sourceColumn": "Billing LYTD",
            "lineageTag": "590dd1ae-6eff-49bb-b702-11cf7d10e30f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Billing LY",
            "dataType": "string",
            "sourceColumn": "Billing LY",
            "lineageTag": "eda98899-ae6b-410d-8b0f-93e8ec9468cd",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Billing PY",
            "dataType": "string",
            "sourceColumn": "Billing PY",
            "lineageTag": "7297c0c6-f11c-42b5-b565-d396e90aacbb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Billing PYTD",
            "dataType": "string",
            "sourceColumn": "Billing PYTD",
            "lineageTag": "d32040e3-07cf-4b29-a47a-61f98d0a7ebc",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Billing SMPY",
            "dataType": "string",
            "sourceColumn": "Billing SMPY",
            "lineageTag": "bb9a94f8-2f0e-4b7b-8fff-48c3654cd6b0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Relative Period",
            "dataType": "string",
            "sourceColumn": "Relative Period",
            "lineageTag": "cc5e9a2a-8a46-4792-b0b4-742aa7861bb0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Billing Day of Week Name",
            "dataType": "string",
            "sourceColumn": "Billing Day of Week Name",
            "lineageTag": "bdca7df6-cd7b-4ff4-a98b-aabc994a3755",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Billing Day of Week Short Name",
            "dataType": "string",
            "sourceColumn": "Billing Day of Week Short Name",
            "lineageTag": "24ccea17-8a55-4d19-9385-cd79f35dcc9d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "SortHelper",
            "dataType": "double",
            "isDataTypeInferred": true,
            "expression": "DIM_PERIOD[Billing Year]*1000 + DIM_PERIOD[Billing Month]",
            "lineageTag": "ec22bffb-1bf1-4a20-a0f2-1ea8c74fef96",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DIM_PERIOD-49b7347d-6c99-4bde-8a96-6e08579756de",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Value.NativeQuery(Snowflake.Databases(\"el02508.west-europe.azure.snowflakecomputing.com\",\"OUT_ANALYTICS\"){[Name=\"PROD_T5_PRESENTATION\"]}[Data], \"Select  #(lf)\"\"Billing Cycle\"\",#(lf)\"\"Billing Year\"\",#(lf)\"\"Billing Quarter\"\",#(lf)\"\"Billing Month\"\",#(lf)\"\"Billing Month Code\"\",#(lf)\"\"Billing Month Name\"\",#(lf)\"\"Billing Period Date\"\",#(lf)\"\"Billing Day\"\",#(lf)\"\"Billing Days in Month\"\",#(lf)\"\"Billing MMDDYYYY\"\",#(lf)\"\"Billing MON-YY\"\",#(lf)\"\"Billing YYYYMMDD\"\",#(lf)\"\"Billing Relative Year\"\",#(lf)\"\"Billing YTD\"\",#(lf)\"\"Billing LYTD\"\",#(lf)\"\"Billing LY\"\",#(lf)\"\"Billing PY\"\",#(lf)\"\"Billing PYTD\"\",#(lf)\"\"Billing SMPY\"\",#(lf)\"\"Relative Period\"\",#(lf)\"\"Billing Day of Week Name\"\",#(lf)\"\"Billing Day of Week Short Name\"\"#(lf)From \"\"PROD_T5_PRESENTATION\"\".\"\"START_FINANCE\"\".\"\"VW_DIM_PERIOD\"\"#(lf)where Year(\"\"Billing Period Date\"\") >= Year(Current_date)-3\", null, [EnableFolding=true])",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "LocalDateTable_ddc0fcbc-9037-43a1-8c8e-f9bd1183ac90",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "72eea951-e707-49e0-99a9-48c52a243347",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "c5cb5f88-5cc8-45ec-9978-da74281f9e98",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "b824cd3e-9e2f-4162-864f-b9fc9f5030cb",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "659c05b4-3e0a-4868-a7e5-324f1fb2c79e",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "74e2cb5d-f4d8-41fa-99ac-0486378dd1b4",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "lineageTag": "4cd3a525-abff-4c3b-a24b-919836b57144",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "25751699-05cf-45ac-b071-cb353be28f4b",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "49070761-cf4d-4800-994c-095179a06505",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_ddc0fcbc-9037-43a1-8c8e-f9bd1183ac90-63c65e41-99d7-4f6e-8d3b-d93abc3184be",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('DIM_PERIOD'[Billing Period Date])), 1, 1), Date(Year(MAX('DIM_PERIOD'[Billing Period Date])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "f830a73f-6e15-4b30-a6c2-0871ff21030a",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "0a0fb10d-0558-407b-ac0d-dd3ef16c272d"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "606922fb-71a9-460f-840b-2068fc36eee5"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "7727736a-c770-4bf0-bc2e-c8ff0523dab7"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "faa15780-6a93-4c8b-991e-bd20dfdd8bff"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "Cockpit Measure New",
        "lineageTag": "dcf4dfaf-aea7-4150-a409-96678a21f859",
        "columns": [
          {
            "name": "Column1",
            "dataType": "string",
            "sourceColumn": "Column1",
            "lineageTag": "d32a4a1a-6d24-4411-a038-e66bf5dcdbf8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Cockpit Measure New-83b13214-e8fd-4978-82dd-e4639578745d",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "_Base Revenue Eur1",
            "expression": "SUM ( FCT_COMMERCIAL_SUMMARY[Base Revenue EUR@BER] )",
            "displayFolder": "Total/Base Rev_Sum",
            "lineageTag": "3758d603-48af-4dbd-9935-17010709de4f",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "_Base Revenue Eur YTD2",
            "expression": [
              "VAR _Currentdate =",
              "    IF (",
              "        MONTH (",
              "            TODAY ()",
              "        ) = 1,",
              "        YEAR (",
              "            TODAY ()",
              "        ) - 1,",
              "        YEAR (",
              "            TODAY ()",
              "        )",
              "    )",
              "RETURN",
              "    CALCULATE (",
              "        [_Base Revenue Eur1],",
              "        FILTER (",
              "            DIM_PERIOD,",
              "            YEAR ( DIM_PERIOD[Billing Period Date] ) = _Currentdate",
              "        )",
              "    )"
            ],
            "lineageTag": "27ab8d20-224f-4be6-9014-d9896339aa65",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "_Base Revenue Eur LM1",
            "expression": [
              "CALCULATE (",
              "    [_Base Revenue Eur1],",
              "    DATEADD (",
              "        FCT_COMMERCIAL_SUMMARY[Billing Period Date],",
              "        -1,",
              "        MONTH",
              "    )",
              ")"
            ],
            "lineageTag": "01bcde51-1eff-4bac-aaf2-e78674e71c51",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "YTD",
            "expression": [
              "IF (",
              "    MONTH (",
              "        MAX ( 'Date'[CYDate] )",
              "    ) = 1,",
              "    YEAR (",
              "        MAX ( 'Date'[CYDate] )",
              "    ) - 1,",
              "    YEAR (",
              "        MAX ( 'Date'[CYDate] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "5dcac2df-9013-40ee-ac75-3fadd2903dab"
          },
          {
            "name": "_Base Revenue USD1",
            "expression": "SUM ( FCT_COMMERCIAL_SUMMARY[Base Revenue USD@BER] )",
            "displayFolder": "Total/Base Rev_Sum",
            "lineageTag": "5e668780-2e4e-4480-8af6-96e880319d1c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "_Base Revenue LCY1",
            "expression": "SUM ( FCT_COMMERCIAL_SUMMARY[Base Revenue LCY] )",
            "displayFolder": "Total/Base Rev_Sum",
            "lineageTag": "13a1574d-10db-42c9-9058-0e99939e3696",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "_Total Revenue Eur1",
            "expression": "SUM ( FCT_COMMERCIAL_SUMMARY[Total Revenue EUR@BER] )",
            "displayFolder": "Total/Base Rev_Sum",
            "lineageTag": "11fbdfed-0cba-431d-87dd-effe827a992a",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "_Total Revenue LCY1",
            "expression": "SUM ( FCT_COMMERCIAL_SUMMARY[Total Revenue LCY] )",
            "displayFolder": "Total/Base Rev_Sum",
            "lineageTag": "8e03e59e-9e00-4015-a678-c276120f2cb0",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "_Total Revenue USD1",
            "expression": "SUM ( FCT_COMMERCIAL_SUMMARY[Total Revenue USD@BER] )",
            "displayFolder": "Total/Base Rev_Sum",
            "lineageTag": "947aacb9-2719-4328-bc84-6ea8d9302b6c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "_Base Revenue Eur YTD1",
            "expression": [
              "VAR _Currentdate =",
              "    IF (",
              "        MONTH (",
              "            TODAY ()",
              "        ) = 1,",
              "        YEAR (",
              "            TODAY ()",
              "        ) - 1,",
              "        YEAR (",
              "            TODAY ()",
              "        )",
              "    )",
              "RETURN",
              "    CALCULATE (",
              "        [_Base Revenue Eur1],",
              "        FILTER (",
              "            DIM_PERIOD,",
              "            YEAR ( DIM_PERIOD[Billing Period Date] ) = _Currentdate",
              "        )",
              "    )"
            ],
            "displayFolder": "Total/Base Rev_YTD",
            "lineageTag": "c6027e7e-3571-4543-a82e-9ea86db3169c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "_Base Revenue USD YTD1",
            "expression": [
              "VAR _Currentdate =",
              "    IF (",
              "        MONTH (",
              "            TODAY ()",
              "        ) = 1,",
              "        YEAR (",
              "            TODAY ()",
              "        ) - 1,",
              "        YEAR (",
              "            TODAY ()",
              "        )",
              "    )",
              "RETURN",
              "    CALCULATE (",
              "        [_Base Revenue USD1],",
              "        FILTER (",
              "            DIM_PERIOD,",
              "            YEAR ( DIM_PERIOD[Billing Period Date] ) = _Currentdate",
              "        )",
              "    )"
            ],
            "displayFolder": "Total/Base Rev_YTD",
            "lineageTag": "e155775a-5475-43bf-96a2-c36f54616a46",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "_Base Revenue LCY YTD1",
            "expression": [
              "VAR _Currentdate =",
              "    IF (",
              "        MONTH (",
              "            TODAY ()",
              "        ) = 1,",
              "        YEAR (",
              "            TODAY ()",
              "        ) - 1,",
              "        YEAR (",
              "            TODAY ()",
              "        )",
              "    )",
              "RETURN",
              "    CALCULATE (",
              "        [_Base Revenue LCY1],",
              "        FILTER (",
              "            DIM_PERIOD,",
              "            YEAR ( DIM_PERIOD[Billing Period Date] ) = _Currentdate",
              "        )",
              "    )"
            ],
            "displayFolder": "Total/Base Rev_YTD",
            "lineageTag": "fc2b5f35-ae00-43fb-b9ef-8d696f3f368f",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "_Total Revenue LCY YTD1",
            "expression": [
              "VAR _Currentdate =",
              "    IF (",
              "        MONTH (",
              "            TODAY ()",
              "        ) = 1,",
              "        YEAR (",
              "            TODAY ()",
              "        ) - 1,",
              "        YEAR (",
              "            TODAY ()",
              "        )",
              "    )",
              "RETURN",
              "    CALCULATE (",
              "        [_Total Revenue LCY1],",
              "        FILTER (",
              "            DIM_PERIOD,",
              "            YEAR ( DIM_PERIOD[Billing Period Date] ) = _Currentdate",
              "        )",
              "    )"
            ],
            "displayFolder": "Total/Base Rev_YTD",
            "lineageTag": "cc862c1f-0eee-4023-9396-952020ad31ea",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "_Total Revenue USD YTD1",
            "expression": [
              "VAR _Currentdate =",
              "    IF (",
              "        MONTH (",
              "            TODAY ()",
              "        ) = 1,",
              "        YEAR (",
              "            TODAY ()",
              "        ) - 1,",
              "        YEAR (",
              "            TODAY ()",
              "        )",
              "    )",
              "RETURN",
              "    CALCULATE (",
              "        [_Total Revenue USD1],",
              "        FILTER (",
              "            DIM_PERIOD,",
              "            YEAR ( DIM_PERIOD[Billing Period Date] ) = _Currentdate",
              "        )",
              "    )"
            ],
            "displayFolder": "Total/Base Rev_YTD",
            "lineageTag": "ea1f64f7-3c9f-4cdd-8e4b-3cda1c2dc507",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "_Total Revenue EUR YTD1",
            "expression": [
              "VAR _Currentdate =",
              "    IF (",
              "        MONTH (",
              "            TODAY ()",
              "        ) = 1,",
              "        YEAR (",
              "            TODAY ()",
              "        ) - 1,",
              "        YEAR (",
              "            TODAY ()",
              "        )",
              "    )",
              "RETURN",
              "    CALCULATE (",
              "        [_Total Revenue Eur1],",
              "        FILTER (",
              "            DIM_PERIOD,",
              "            YEAR ( DIM_PERIOD[Billing Period Date] ) = _Currentdate",
              "        )",
              "    )"
            ],
            "displayFolder": "Total/Base Rev_YTD",
            "lineageTag": "a350edd5-34aa-4baf-a548-78605c35b130",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "LY",
            "expression": [
              "IF (",
              "    MONTH (",
              "        MAX ( 'Date'[CYDate] )",
              "    ) = 1,",
              "    YEAR (",
              "        MAX ( 'Date'[CYDate] )",
              "    ) - 2,",
              "    YEAR (",
              "        MAX ( 'Date'[CYDate] )",
              "    ) - 1",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "d4b080b7-0270-4d1c-b76c-e29080eba89b"
          },
          {
            "name": "LM",
            "expression": [
              "IF (",
              "    MONTH (",
              "        MAX ( 'Date'[CYDate] )",
              "    ) = 1,",
              "    MONTH (",
              "        DATE ( YEAR (",
              "            MAX ( 'Date'[CYDate] )",
              "        ) - 1, 12, 31 )",
              "    ),",
              "    MONTH (",
              "        MAX ( 'Date'[CYDate] )",
              "    ) - 1",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "1fa0b904-c720-44b9-9ec5-0d34c3f98ca8"
          },
          {
            "name": "LYTD",
            "expression": [
              "IF (",
              "    MONTH (",
              "        MAX ( 'Date'[CYDate] )",
              "    ) = 1,",
              "    YEAR (",
              "        MAX ( 'Date'[CYDate] )",
              "    ) - 2,",
              "    YEAR (",
              "        MAX ( 'Date'[CYDate] )",
              "    ) - 1",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "b2edaa71-1cfc-4e88-8ca9-df2776c4f0e7"
          },
          {
            "name": "LYLM",
            "expression": [
              "IF (",
              "    MONTH (",
              "        MAX ( 'Date'[CYDate] )",
              "    ) = 1,",
              "    MONTH (",
              "        DATE ( YEAR (",
              "            MAX ( 'Date'[CYDate] )",
              "        ) - 2, 12, 31 )",
              "    ),",
              "    MONTH (",
              "        MAX ( 'Date'[CYDate] )",
              "    ) - 1",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "902e5279-330d-4ac0-bfdf-5bb1d1e9f5e2"
          },
          {
            "name": "Today",
            "expression": "MAX ( 'Date'[CYDate] )",
            "lineageTag": "a7d317f9-4651-42ee-92b0-08f6408d6b7a"
          },
          {
            "name": "PLY",
            "expression": "2021",
            "formatString": "0",
            "lineageTag": "5d1d9d38-8bc8-4fa3-b212-c1ac36613176"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Country_P",
        "lineageTag": "2c8a1fe1-42e9-4c60-b9f3-3c749fdb705c",
        "columns": [
          {
            "name": "Sales Function - Country Code",
            "dataType": "string",
            "sourceColumn": "Sales Function - Country Code",
            "lineageTag": "d858d53f-9473-48ba-85c9-9cab409db537",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Country_P-71e351e3-b293-4f2c-a7a0-3be29a139d03",
            "mode": "import",
            "queryGroup": "Parameter",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Value.NativeQuery(Snowflake.Databases(\"el02508.west-europe.azure.snowflakecomputing.com\",\"OUT_ANALYTICS\"){[Name=\"PROD_T5_PRESENTATION\"]}[Data], \"Select distinct \"\"Sales Function - Country Code\"\"#(lf)--, \"\"Sales Function - Region Code\"\"#(lf)from \"\"PROD_T5_PRESENTATION\"\".\"\"START_FINANCE\"\".\"\"VW_DIM_SALES_FUNCTION\"\"#(lf)--Where \"\"Sales Function - Region Code\"\" in ('AC')\", null, [EnableFolding=true])",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "LocalDateTable_64307048-556d-43e0-a74e-929e596a5189",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "5152686b-6ade-40e7-906b-7e3d94165373",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "9b57fee3-a871-414e-8e80-0881ff0491b8",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "0076627c-963f-421e-9741-6b2560dee2de",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "6227e153-8190-4bc4-b56b-8c88748d3335",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "871173d8-df45-47b9-80bb-3f4a3231751d",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "lineageTag": "3047a96b-17e2-4e15-8ae8-b6539db527b9",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "6d796e6c-667a-45df-a68a-fb9e56fd42e5",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "e0bfdc56-a269-4662-895d-26f5cc72df93",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_64307048-556d-43e0-a74e-929e596a5189-cd75c393-6f91-4ba0-959b-3be8111999f0",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('VW_DIM_CUSTOMER'[FTB Date])), 1, 1), Date(Year(MAX('VW_DIM_CUSTOMER'[FTB Date])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "a8b9ff03-6477-44d2-acd7-3c11246de76a",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "8aefdb8b-4095-47a1-b857-277c8b6cd11b"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "c4b1b200-9252-40f5-b8f3-969663da85f3"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "34339613-2bd8-4af3-a731-6b1dcdd15889"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "a737e243-76d0-4c19-9a4f-e51bd5eab0cd"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "MainKpi L13 RM",
        "lineageTag": "67c2a2ff-f1be-4ada-b4e4-789ac47d3a97",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "MainKpi L13 RM",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value1]",
            "sortByColumn": "MainKpi L13 RM Order",
            "lineageTag": "85deca9a-a541-4cfa-acee-a001e3986101",
            "summarizeBy": "none",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "MainKpi L13 RM Fields"
                }
              ]
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "MainKpi L13 RM Fields",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value2]",
            "sortByColumn": "MainKpi L13 RM Order",
            "lineageTag": "f53fa946-4bd2-4bbb-90a9-fd9de9f13a82",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "ParameterMetadata",
                "value": {
                  "version": 3,
                  "kind": 2
                }
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "MainKpi L13 RM Order",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value3]",
            "formatString": "0",
            "lineageTag": "0406af9d-b284-487a-bfe1-5d90ca416f26",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "MainKpi L13 RM-ebbb8405-34c9-453d-a1e8-4d5452ba987e",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "{",
                "    (\"RPD\", NAMEOF('Main KPI Measures'[L13 RPD]), 0),",
                "    (\"SPD\", NAMEOF('Main KPI Measures'[L13 SPD]), 1),",
                "    (\"WPD\", NAMEOF('Main KPI Measures'[L13 WPD]), 2),",
                "    (\"RPK\", NAMEOF('Main KPI Measures'[L13 RPK]), 3),",
                "    (\"RPS\", NAMEOF('Main KPI Measures'[L13 RPS]), 4),",
                "    (\"WPS\", NAMEOF('Main KPI Measures'[L13 WPS]), 5)",
                "}"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "fd1283c4696648cca38f55765375b18b"
          }
        ]
      },
      {
        "name": "FCT_COMMERCIAL_SUMMARY",
        "lineageTag": "eb438f90-bf94-43f1-92cc-99f96c3eefe5",
        "columns": [
          {
            "name": "Billing Period Date",
            "dataType": "dateTime",
            "sourceColumn": "Billing Period Date",
            "formatString": "Long Date",
            "lineageTag": "172213c9-03f9-4e62-8e99-6e9604a79708",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Origin Country Code",
            "dataType": "string",
            "sourceColumn": "Origin Country Code",
            "lineageTag": "f039b817-0ad0-45e5-b7b1-69cad131f450",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Owner Country Code",
            "dataType": "string",
            "sourceColumn": "Owner Country Code",
            "lineageTag": "597e1a90-61db-4eb5-94fd-b9df33585df6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Sales Channel",
            "dataType": "string",
            "sourceColumn": "Sales Channel",
            "lineageTag": "b6ab7a03-368f-4990-94c5-dd818a9ff16c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Product SK",
            "dataType": "string",
            "sourceColumn": "Product SK",
            "lineageTag": "a2cd7f80-496b-43f8-83dd-36d54271afdb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Account SK",
            "dataType": "string",
            "sourceColumn": "Account SK",
            "lineageTag": "38c9480e-1196-43a0-939a-67745ef97a03",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Customer SK",
            "dataType": "string",
            "sourceColumn": "Customer SK",
            "lineageTag": "81c09584-accc-4e30-af11-1a4e7ee287b1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Sales Territory SK",
            "dataType": "string",
            "sourceColumn": "Sales Territory SK",
            "lineageTag": "ee01b0d1-3e4f-45c8-a75b-fbcf666fed6d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Customer Sales Channel",
            "dataType": "string",
            "sourceColumn": "Customer Sales Channel",
            "lineageTag": "0bf8f06a-bcbf-4f00-893b-52b82b8679d7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Weight Break ID",
            "dataType": "double",
            "sourceColumn": "Weight Break ID",
            "lineageTag": "6a0d90c0-c856-47db-81b6-95feb227104d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Weight Break Per Piece ID",
            "dataType": "double",
            "sourceColumn": "Weight Break Per Piece ID",
            "lineageTag": "eb11d751-b6e3-4f92-878a-079e6a4337b1",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Weight Type",
            "dataType": "string",
            "sourceColumn": "Weight Type",
            "lineageTag": "b399d23b-c0d7-4153-a2da-3903c5667073",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Spot Rate GSRT",
            "dataType": "string",
            "sourceColumn": "Spot Rate GSRT",
            "lineageTag": "78518558-9602-4668-a325-5d96cdcacf15",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "B2C Flag",
            "dataType": "string",
            "sourceColumn": "B2C Flag",
            "lineageTag": "ef0925fa-636b-4401-8c85-fdbab729a6ac",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Customer GSFA ID",
            "dataType": "string",
            "sourceColumn": "Customer GSFA ID",
            "lineageTag": "8e45aaab-de59-4fb1-ae1e-0b3d5cbff102",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "IBOB",
            "dataType": "string",
            "sourceColumn": "IBOB",
            "lineageTag": "b572fe8a-7890-4894-a8de-ba863624df75",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "TRADELANE",
            "dataType": "string",
            "sourceColumn": "TRADELANE",
            "lineageTag": "68c393b5-90e8-4a68-9484-e10e1da1b3b2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Industry Sector Name",
            "dataType": "string",
            "sourceColumn": "Industry Sector Name",
            "lineageTag": "b4b92485-e182-4e54-96c1-2ee0cd1d5d72",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Number of Shipments",
            "dataType": "double",
            "sourceColumn": "Number of Shipments",
            "lineageTag": "3c8cc11a-afff-4f86-99e7-bb95d4e96dd6",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Billed Weight KG",
            "dataType": "double",
            "sourceColumn": "Billed Weight KG",
            "lineageTag": "0ca671ff-81ae-437f-b7ae-2732cc6833b9",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue LCY",
            "dataType": "double",
            "sourceColumn": "Total Revenue LCY",
            "lineageTag": "397f943b-d312-4ce0-ab48-fb32fbc85945",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue EUR@BER",
            "dataType": "double",
            "sourceColumn": "Total Revenue EUR@BER",
            "lineageTag": "70c85ed6-919e-46c7-a218-166e6a4ae930",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Revenue USD@BER",
            "dataType": "double",
            "sourceColumn": "Total Revenue USD@BER",
            "lineageTag": "bb9b283f-7698-488f-8922-e4a1cc196152",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Base Revenue LCY",
            "dataType": "double",
            "sourceColumn": "Base Revenue LCY",
            "lineageTag": "28496b24-2a37-4c55-bec5-9e3efb86f0ae",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Base Revenue EUR@BER",
            "dataType": "double",
            "sourceColumn": "Base Revenue EUR@BER",
            "lineageTag": "954c1921-9520-4b4f-bb5d-0cf43efd9eac",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Base Revenue USD@BER",
            "dataType": "double",
            "sourceColumn": "Base Revenue USD@BER",
            "lineageTag": "b2665e8b-3024-4775-907c-12c479d6d9ce",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Shipment Band Range",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "SWITCH (",
              "    TRUE (),",
              "    FCT_COMMERCIAL_SUMMARY[Number of Shipments] < 0,\"<0\",",
              "    FCT_COMMERCIAL_SUMMARY[Number of Shipments] >= 0",
              "        && FCT_COMMERCIAL_SUMMARY[Number of Shipments] <= 5, \"0-5\",",
              "    FCT_COMMERCIAL_SUMMARY[Number of Shipments] >= 6",
              "        && FCT_COMMERCIAL_SUMMARY[Number of Shipments] <= 25, \"6-25\",",
              "    FCT_COMMERCIAL_SUMMARY[Number of Shipments] >= 26",
              "        && FCT_COMMERCIAL_SUMMARY[Number of Shipments] <= 100, \"26-100\",",
              "    FCT_COMMERCIAL_SUMMARY[Number of Shipments] >= 101",
              "        && FCT_COMMERCIAL_SUMMARY[Number of Shipments] <= 500, \"101-500\",",
              "    FCT_COMMERCIAL_SUMMARY[Number of Shipments] >= 500, \"500+\"",
              ")",
              ""
            ],
            "lineageTag": "254ff389-a561-4313-9326-45146e087fbe",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "FCT_COMMERCIAL_SUMMARY-d1563296-37a2-4bf7-8162-c8fed69e325b",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "// Check the Country Parameter",
                "    Country = ",
                "  if P_Country = \"All\" then \" \"",
                "      else",
                "    if ",
                "    //check to see if the parameter is a list",
                "      Type.Is(",
                "        Value.Type(#\"P_Country\"), ",
                "        List.Type",
                "      ) then ",
                "        //if it is a list",
                "         if List.Contains(P_Country, \"All\") then \" \"",
                "      else",
                "        let",
                "          //add single quotes around each value in the list",
                "          AddSingleQuotes = List.Transform(",
                "              #\"P_Country\", ",
                "              each \"'\" & _ & \"'\"",
                "            ),",
                "          //then turn it into a comma-delimited list",
                "          DelimitedList = Text.Combine(",
                "              AddSingleQuotes, ",
                "              \",\"",
                "            )",
                "        in",
                "          \"and S.\"&\"\"\"Sales Function - Country Code\"\" in (\" & DelimitedList & \")\" ",
                "    else ",
                "      //if the parameter isn't a list",
                "      //just add single quotes around the parameter value",
                "      \"and S.\"&\"\"\"Sales Function - Country Code\"\" in (\" & \"'\" & #\"P_Country\" & \"'\" & \")\",",
                "",
                "    Source = Value.NativeQuery(Snowflake.Databases(\"el02508.west-europe.azure.snowflakecomputing.com\",\"OUT_ANALYTICS\"){[Name=\"PROD_T5_PRESENTATION\"]}[Data], \"Select #(lf)  \"\"Billing Period Date\"\", #(lf)  \"\"Origin Country Code\"\", #(lf)  \"\"Owner Country Code\"\", #(lf)  F.\"\"Sales Channel\"\", #(lf)  F.\"\"Product SK\"\", #(lf)  F.\"\"Account SK\"\", #(lf)  F.\"\"Customer SK\"\", #(lf)  F.\"\"Sales Territory SK\"\", #(lf)  F.\"\"Customer Sales Channel\"\", #(lf)  \"\"Weight Break ID\"\", #(lf)  \"\"Weight Break Per Piece ID\"\", #(lf)  \"\"Weight Type\"\", #(lf)  \"\"Spot Rate GSRT\"\", #(lf)  \"\"B2C Flag\"\", #(lf)   C.\"\"Customer GSFA ID\"\",#(lf) ",
                "     case when F.\"\"Billing Country Code\"\" = F.\"\"Origin Country Code\"\" then 'OB' else 'IB' end as IBOB,#(lf) CONCAT(\"\"Origin Country Code\"\",' - ', \"\"Destination Country Code\"\") as TradeLane,",
                "    F.\"\"Industry Sector Name\"\", sum(\"\"Number of Shipments\"\") as \"\"Number of Shipments\"\", #(lf)  sum(\"\"Billed Weight KG\"\") as \"\"Billed Weight KG\"\", #(lf)  sum(\"\"Total Revenue LCY\"\") as \"\"Total Revenue LCY\"\", #(lf)  sum(\"\"Total Revenue EUR@BER\"\") as \"\"Total Revenue EUR@BER\"\", #(lf)  sum(\"\"Total Revenue USD@BER\"\") as \"\"Total Revenue USD@BER\"\", #(lf)  sum(\"\"Base Revenue LCY\"\") as \"\"Base Revenue LCY\"\", #(lf)  sum(\"\"Base Revenue EUR@BER\"\") as \"\"Base Revenue EUR@BER\"\", #(lf)  sum(\"\"Base Revenue USD@BER\"\") as \"\"Base Revenue USD@BER\"\" #(lf)from #(lf)   \"\"PROD_T5_PRESENTATION\"\".\"\"START_FINANCE\"\".\"\"VW_FCT_COMMERCIAL_SUMMARY\"\" F #(lf)  JOIN \"\"PROD_T5_PRESENTATION\"\".\"\"START_FINANCE\"\".\"\"VW_DIM_PRODUCT\"\" PR on F.\"\"Product SK\"\" = PR.\"\"Product SK\"\" #(lf)  JOIN \"\"PROD_T5_PRESENTATION\"\".\"\"START_FINANCE\"\".\"\"VW_DIM_ACCOUNT\"\" A on F.\"\"Account SK\"\" = A.\"\"Account SK\"\" #(lf)  JOIN \"\"PROD_T5_PRESENTATION\"\".\"\"CUSTOMER360\"\".\"\"VW_DIM_CUSTOMER\"\" C ON A.\"\"Customer GSFA ID\"\" = C.\"\"Customer GSFA ID\"\" #(lf)  JOIN \"\"PROD_T5_PRESENTATION\"\".\"\"START_FINANCE\"\".\"\"VW_DIM_SALES_FUNCTION\"\" S ON F.\"\"Sales Territory SK\"\" = S.\"\"Sales Territory SK\"\" #(lf)where #(lf)  Year(F.\"\"Billing Period Date\"\") >= year(current_date)-2 #(lf) ",
                "    \"& Country &\" and F.\"\"Transaction Type\"\" <> 'F' #(lf)Group By #(lf)  \"\"Billing Period Date\"\", #(lf)  \"\"Origin Country Code\"\", #(lf)  \"\"Owner Country Code\"\", #(lf)  F.\"\"Sales Channel\"\", #(lf)  F.\"\"Product SK\"\", #(lf)  F.\"\"Account SK\"\", #(lf)  F.\"\"Customer SK\"\", #(lf)  F.\"\"Sales Territory SK\"\", #(lf)  F.\"\"Customer Sales Channel\"\", #(lf)  \"\"Weight Break ID\"\", #(lf)  \"\"Weight Break Per Piece ID\"\", #(lf)  \"\"Weight Type\"\", #(lf)  \"\"Spot Rate GSRT\"\", #(lf)  \"\"B2C Flag\"\", C.\"\"Customer GSFA ID\"\", #(lf)   IBOB,#(lf)TradeLane, F.\"\"Industry Sector Name\"\" \", null, [EnableFolding=true])",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Active/Inactive",
            "expression": [
              "IF (",
              "    [Customer RSW YTD] > 0,",
              "    \"Active\",",
              "    \"Inactive\"",
              ")"
            ],
            "lineageTag": "c8fba149-285e-49d5-ba87-a1406bd4035c"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ]
      },
      {
        "name": "Date",
        "lineageTag": "6031d705-e67e-465e-899c-0e471521faeb",
        "columns": [
          {
            "name": "CYDate",
            "dataType": "string",
            "sourceColumn": "CYDate",
            "lineageTag": "7664814c-7cea-4659-a543-24477b233345",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Date-ea06ca0d-ed52-4eff-8803-f3725fe5e832",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #table({\"CYDate\"},{{#\"P_Date\"}})",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Loyality Status",
        "lineageTag": "8ec160eb-5113-4b80-9918-f2b5e8aa08fd",
        "columns": [
          {
            "name": "ID",
            "dataType": "int64",
            "sourceColumn": "ID",
            "formatString": "0",
            "lineageTag": "11904c4d-29a0-4b66-8b5d-8365a9a4667c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Status",
            "dataType": "string",
            "sourceColumn": "Status",
            "sortByColumn": "ID",
            "lineageTag": "a52d1431-4146-47c3-9972-0e55673a86d6",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Loyality Status-ca3991d6-ef09-4dc7-8e93-03ddc4bc64b3",
            "mode": "import",
            "queryGroup": "Static Filter",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlTSUfJLLVeK1YlWMgKyg1LTEzPzUlPAAsZAgdCCkqLElNQisIAJUCC4JDEpJxXMNQVyXfLL85BUmAGFfPKLS8AccyDHMy8xuSSzDKghFgA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ID = _t, Status = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"ID\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Sorting Product",
        "lineageTag": "fa4b357e-5d37-4ee6-93e3-a8dfd5c58f8e",
        "columns": [
          {
            "name": "Product Code",
            "dataType": "string",
            "sourceColumn": "Product Code",
            "sortByColumn": "Id",
            "lineageTag": "ba0a6221-4a1a-4000-bf34-d16107c55c9a",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Id",
            "dataType": "int64",
            "sourceColumn": "Id",
            "formatString": "0",
            "lineageTag": "dcc4d5ba-70ee-47f3-a8d6-4c70e689b0fc",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Sorting Product-de44df2a-0009-4af7-9140-d0d2612af541",
            "mode": "import",
            "queryGroup": "Static Filter",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WCnHxVNJRMlSK1QGxXYBsIzDbBSxuDGWDxE3A7GCwuCmUDRI3A7P9Qzxcg4KBXHOl2FgA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Product Code\" = _t, Id = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Product Code\", type text}, {\"Id\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Sales Function Import",
        "lineageTag": "89aef18e-0282-4cda-a058-8a1d15ac2378",
        "columns": [
          {
            "name": "Sales Function.BU Manager Code",
            "dataType": "string",
            "sourceColumn": "Sales Function.BU Manager Code",
            "lineageTag": "b9a69254-14dd-44a1-bfa3-afc143d5b8de",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Sales Function.BU Manager Email",
            "dataType": "string",
            "sourceColumn": "Sales Function.BU Manager Email",
            "lineageTag": "1ef6c8c4-1a2a-48b7-8bd6-df7a04740c48",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Sales Function.BU Manager Name",
            "dataType": "string",
            "sourceColumn": "Sales Function.BU Manager Name",
            "lineageTag": "2003f6a6-5122-4740-8f7b-929b14d5ef57",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Sales Function.CT_SK",
            "dataType": "string",
            "sourceColumn": "Sales Function.CT_SK",
            "lineageTag": "61969e57-422b-4e92-98aa-6f30697c8c53",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Sales Function.Sales Function - Country Code",
            "dataType": "string",
            "sourceColumn": "Sales Function.Sales Function - Country Code",
            "lineageTag": "c4c92e0d-b6fb-45b6-92df-dcf24e80c41c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Sales Function.Sales Function - Sales Channel Description",
            "dataType": "string",
            "sourceColumn": "Sales Function.Sales Function - Sales Channel Description",
            "lineageTag": "2f9747fd-dcea-41ed-b03d-a4f95668c65e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Sales Function.Sales Function - STC",
            "dataType": "string",
            "sourceColumn": "Sales Function.Sales Function - STC",
            "lineageTag": "897d2b99-b7fb-436d-865e-a906ce76a273",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Sales Function.Sales Function Sales - Channel Code",
            "dataType": "string",
            "sourceColumn": "Sales Function.Sales Function Sales - Channel Code",
            "lineageTag": "56577472-f94d-4dd1-9728-e6123d22c0fb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Sales Function.Sales Manager Code",
            "dataType": "string",
            "sourceColumn": "Sales Function.Sales Manager Code",
            "lineageTag": "8e51a8d1-34f7-4629-b453-1cb485fa9669",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Sales Function.Sales Manager Email",
            "dataType": "string",
            "sourceColumn": "Sales Function.Sales Manager Email",
            "lineageTag": "186236c2-f7e9-4b86-a1c6-a8a07bdf5949",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Sales Function.Sales Manager Name",
            "dataType": "string",
            "sourceColumn": "Sales Function.Sales Manager Name",
            "lineageTag": "aa52498c-8454-4f6e-b5ad-0f917ab69693",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Sales Function.Sales Person Code",
            "dataType": "string",
            "sourceColumn": "Sales Function.Sales Person Code",
            "lineageTag": "2273066f-8ab0-4d99-997f-770c5803155d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Sales Function.Sales Person Email",
            "dataType": "string",
            "sourceColumn": "Sales Function.Sales Person Email",
            "lineageTag": "bf50525b-b4fe-4417-bb59-431d2d464095",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Sales Function.Sales Person Name",
            "dataType": "string",
            "sourceColumn": "Sales Function.Sales Person Name",
            "lineageTag": "5bfe2251-6698-451e-810c-a76a2f6c7c83",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Sales Function Import-3df9049a-b49d-40ca-b5d1-163e96d1d493",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = AnalysisServices.Databases(\"powerbi://api.powerbi.com/v1.0/myorg/DF_Global_GS_DEV\", [TypedMeasureColumns=true, Implementation=\"2.0\"]),",
                "    #\"Sales FunctionV1.0\" = Source{[Name=\"Sales FunctionV1.0\"]}[Data],",
                "    Model1 = #\"Sales FunctionV1.0\"{[Id=\"Model\"]}[Data],",
                "    Model2 = Model1{[Id=\"Model\"]}[Data],",
                "    #\"Added Items\" = Cube.Transform(Model2,",
                "        {",
                "            {Cube.AddAndExpandDimensionColumn, \"[Sales Function]\", {\"[Sales Function].[BU Manager Code].[BU Manager Code]\", \"[Sales Function].[BU Manager Email].[BU Manager Email]\", \"[Sales Function].[BU Manager Name].[BU Manager Name]\", \"[Sales Function].[CT_SK].[CT_SK]\", \"[Sales Function].[Sales Function - Country Code].[Sales Function - Country Code]\", \"[Sales Function].[Sales Function - Sales Channel Description].[Sales Function - Sales Channel Description]\", \"[Sales Function].[Sales Function - STC].[Sales Function - STC]\", \"[Sales Function].[Sales Function Sales - Channel Code].[Sales Function Sales - Channel Code]\", \"[Sales Function].[Sales Manager Code].[Sales Manager Code]\", \"[Sales Function].[Sales Manager Email].[Sales Manager Email]\", \"[Sales Function].[Sales Manager Name].[Sales Manager Name]\", \"[Sales Function].[Sales Person Code].[Sales Person Code]\", \"[Sales Function].[Sales Person Email].[Sales Person Email]\", \"[Sales Function].[Sales Person Name].[Sales Person Name]\"}, {\"Sales Function.BU Manager Code\", \"Sales Function.BU Manager Email\", \"Sales Function.BU Manager Name\", \"Sales Function.CT_SK\", \"Sales Function.Sales Function - Country Code\", \"Sales Function.Sales Function - Sales Channel Description\", \"Sales Function.Sales Function - STC\", \"Sales Function.Sales Function Sales - Channel Code\", \"Sales Function.Sales Manager Code\", \"Sales Function.Sales Manager Email\", \"Sales Function.Sales Manager Name\", \"Sales Function.Sales Person Code\", \"Sales Function.Sales Person Email\", \"Sales Function.Sales Person Name\"}}",
                "        }),",
                "    #\"Capitalized Each Word\" = Table.TransformColumns(#\"Added Items\",{{\"Sales Function.BU Manager Name\", Text.Proper, type text}, {\"Sales Function.Sales Function - Sales Channel Description\", Text.Proper, type text}, {\"Sales Function.Sales Manager Name\", Text.Proper, type text}, {\"Sales Function.Sales Person Name\", Text.Proper, type text}})",
                "in",
                "    #\"Capitalized Each Word\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "User List",
        "lineageTag": "41e8fd04-335c-4b72-93d7-44f1668aa67c",
        "columns": [
          {
            "name": "S.No",
            "dataType": "string",
            "sourceColumn": "S.No",
            "lineageTag": "5575fe7a-4ff6-466b-805a-557db1514dbc",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "First Name",
            "dataType": "string",
            "sourceColumn": "First Name",
            "lineageTag": "53ccda9b-eb3c-4ae0-932a-35514f87b8b3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Last Name",
            "dataType": "string",
            "sourceColumn": "Last Name",
            "lineageTag": "2ac4efe5-12b7-410d-a442-67332a307926",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Name",
            "dataType": "string",
            "sourceColumn": "Name",
            "lineageTag": "56f19bee-9049-4a9f-8d31-a6f081740202",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Email ID",
            "dataType": "string",
            "sourceColumn": "Email ID",
            "lineageTag": "52a15443-029a-4785-acc1-1f22fa27026c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Country",
            "dataType": "string",
            "sourceColumn": "Country",
            "lineageTag": "76239de9-5b1a-4c38-b6d0-03a328859904",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "User List-6ce80e48-8265-46be-8b2f-d0521bfa4b4e",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.Combine({#\"User List1\", #\"User List2\", #\"User List3\", #\"User List4\", #\"User List5\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(Source,{\"Regional\", \"Region\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "62e3c613-ad42-43cb-b656-471512d81c70",
        "fromTable": "VW_DIM_CUSTOMER",
        "fromColumn": "FTB Month",
        "toTable": "LocalDateTable_ffde379d-04ff-4188-80bf-e4a99402391c",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "f5b0fbd9-88d9-4c0f-8679-fdcc340eb99d",
        "fromTable": "DIM_PERIOD",
        "fromColumn": "Billing Period Date",
        "toTable": "LocalDateTable_ddc0fcbc-9037-43a1-8c8e-f9bd1183ac90",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "56014142-90ea-4df5-9f38-628a0c4f01e7",
        "fromTable": "DIM_WORK_DAYS_GEO",
        "fromColumn": "Billing Period Date",
        "toTable": "DIM_PERIOD",
        "toColumn": "Billing Period Date"
      },
      {
        "name": "8d24c4b0-d6b5-497b-8629-095c197d765c",
        "fromTable": "DIM_PERIOD",
        "fromColumn": "Billing Month",
        "toTable": "ShortMonthMapping",
        "toColumn": "S.No"
      },
      {
        "name": "2ac05ccd-13a1-4d6b-96c8-ae040c83a967",
        "fromTable": "DIM_PERIOD",
        "fromColumn": "Billing Year",
        "toTable": "Dynamic Year",
        "toColumn": "Year"
      },
      {
        "name": "60491529-72b9-437b-8934-9f9bb2906a6e",
        "fromTable": "DIM_WEIGHT_BREAK",
        "fromColumn": "Weight Break Group Desc",
        "toTable": "Weight Break Group",
        "toColumn": "Weight Break Group Desc"
      },
      {
        "name": "a52e7797-9f0f-4e4b-bb89-f90356dca4f6",
        "fromTable": "VW_DIM_CUSTOMER",
        "fromColumn": "FTB Date",
        "toTable": "LocalDateTable_64307048-556d-43e0-a74e-929e596a5189",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "687d5e5e-1bf8-470e-87f9-c531bd388ff6",
        "fromTable": "FCT_COMMERCIAL_SUMMARY",
        "fromColumn": "Sales Territory SK",
        "toTable": "DIM_SALES_FUNCTION",
        "toColumn": "Sales Territory SK"
      },
      {
        "name": "7502d4ae-04bc-4e02-9648-cc4ef257197c",
        "fromTable": "FCT_COMMERCIAL_SUMMARY",
        "fromColumn": "Weight Break ID",
        "toTable": "DIM_WEIGHT_BREAK",
        "toColumn": "Weight Break ID"
      },
      {
        "name": "6ca14988-f7f0-435c-bb2c-ed316f9ae75c",
        "fromTable": "FCT_COMMERCIAL_SUMMARY",
        "fromColumn": "Product SK",
        "toTable": "DIM_PRODUCT",
        "toColumn": "Product SK"
      },
      {
        "name": "bf12e9a3-447b-45ec-971c-cbf11e65a42e",
        "fromTable": "FCT_COMMERCIAL_SUMMARY",
        "fromColumn": "Shipment Band Range",
        "toTable": "Shipment Range",
        "toColumn": "Shipments"
      },
      {
        "name": "b0dc950c-a36b-4476-bd4d-ce6c21dbb3fa",
        "fromTable": "FCT_COMMERCIAL_SUMMARY",
        "fromColumn": "Billing Period Date",
        "toTable": "DIM_PERIOD",
        "toColumn": "Billing Period Date"
      },
      {
        "name": "e06febe1-2b14-463b-bc2f-c2838bd94da5",
        "fromTable": "FCT_COMMERCIAL_SUMMARY",
        "fromColumn": "Customer GSFA ID",
        "toTable": "VW_DIM_CUSTOMER",
        "toColumn": "Customer GSFA ID",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "d3a13130-20ee-43fd-b3ff-dc758ce40103",
        "fromTable": "DIM_PRODUCT",
        "fromColumn": "Product Code",
        "toTable": "Sorting Product",
        "toColumn": "Product Code"
      },
      {
        "name": "d77f42c0-4c60-4f72-90e3-5391a43d7050",
        "fromTable": "VW_DIM_CUSTOMER",
        "fromColumn": "Strategic Loyalty RM",
        "toTable": "Loyality Status",
        "toColumn": "Status"
      },
      {
        "name": "ad4c64c0-5f34-4918-9951-bd2d5824108f",
        "fromTable": "DIM_SALES_FUNCTION",
        "fromColumn": "Sales Function - Country Code",
        "toTable": "Country_P",
        "toColumn": "Sales Function - Country Code"
      },
      {
        "name": "f1fdbe96-76c6-494d-a47a-236d9c296415",
        "fromCardinality": "one",
        "fromTable": "DIM_SALES_FUNCTION",
        "fromColumn": "CT_SK",
        "toTable": "Sales Function Import",
        "toColumn": "Sales Function.CT_SK",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "e67fa421-4497-4625-95c1-782fa0831d90",
        "toCardinality": "many",
        "fromTable": "Sales Function Import",
        "fromColumn": "Sales Function.Sales Function - Country Code",
        "toTable": "User List",
        "toColumn": "Country",
        "crossFilteringBehavior": "bothDirections"
      }
    ],
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "roles": [
      {
        "name": "Manager",
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Sales Function Import",
            "filterExpression": "[Sales Function.Sales Manager Email]= USERPRINCIPALNAME ()"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "477778bef87d4991bdc96433f445bee0"
          }
        ]
      },
      {
        "name": "SalesPerson",
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Sales Function Import",
            "filterExpression": "[Sales Function.Sales Person Email]= USERPRINCIPALNAME ()"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "d1f938ece3a347fd98852e753c8500b0"
          }
        ]
      },
      {
        "name": "UserName",
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "User List",
            "filterExpression": "[Email ID] = USERPRINCIPALNAME()"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "5ca7155ddec54e559d9c2781a59cdf0b"
          }
        ]
      }
    ],
    "expressions": [
      {
        "name": "P_Country",
        "kind": "m",
        "expression": "\"MO','BN\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=false]",
        "queryGroup": "Parameter",
        "lineageTag": "8d9b151f-2e96-4234-8d7e-bb7a877cae77",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ]
      },
      {
        "name": "DIM_ACCOUNT",
        "kind": "m",
        "expression": [
          "let",
          "    Source = Value.NativeQuery(Snowflake.Databases(\"el02508.west-europe.azure.snowflakecomputing.com\",\"OUT_ANALYTICS\"){[Name=\"PROD_T5_PRESENTATION\"]}[Data], \"Select Distinct#(lf)A.\"\"Account SK\"\",#(lf)A.\"\"Customer GSFA ID\"\"#(lf) From  \"\"PROD_T5_PRESENTATION\"\".\"\"START_FINANCE\"\".\"\"VW_FCT_COMMERCIAL_SUMMARY\"\" F #(lf)  JOIN \"\"PROD_T5_PRESENTATION\"\".\"\"START_FINANCE\"\".\"\"VW_DIM_PERIOD\"\" P ON F.\"\"Billing Period Date\"\" = P.\"\"Billing Period Date\"\" #(lf)  JOIN \"\"PROD_T5_PRESENTATION\"\".\"\"START_FINANCE\"\".\"\"VW_DIM_PRODUCT\"\" PR on F.\"\"Product SK\"\" = PR.\"\"Product SK\"\" #(lf)  JOIN \"\"PROD_T5_PRESENTATION\"\".\"\"START_FINANCE\"\".\"\"VW_DIM_ACCOUNT\"\" A on F.\"\"Account SK\"\" = A.\"\"Account SK\"\" #(lf)  JOIN \"\"PROD_T5_PRESENTATION\"\".\"\"CUSTOMER360\"\".\"\"VW_DIM_CUSTOMER\"\" C ON A.\"\"Customer GSFA ID\"\" = C.\"\"Customer GSFA ID\"\" #(lf)  JOIN \"\"PROD_T5_PRESENTATION\"\".\"\"START_FINANCE\"\".\"\"VW_DIM_SALES_FUNCTION\"\" S ON F.\"\"Sales Territory SK\"\" = S.\"\"Sales Territory SK\"\" #(lf)WHERE #(lf)  S.\"\"Sales Function - Region Code\"\" = 'AC' #(lf)  and PR.\"\"Main Product Category Code\"\" IN (#(lf)    'TDI', 'TDD', 'DDI', 'DDD', 'SDI', 'SDD'#(lf)  )\", null, [EnableFolding=true])",
          "in",
          "    Source"
        ],
        "lineageTag": "6f50cec1-8816-4bca-aad7-a76536c6db22",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "P_StartDate",
        "kind": "m",
        "expression": "null meta [IsParameterQuery=true, Type=\"Date\", IsParameterQueryRequired=false]",
        "queryGroup": "Parameter",
        "lineageTag": "28a39168-6cb7-4ae3-98f5-1192ac201a61",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Null"
          }
        ]
      },
      {
        "name": "P_EndDate",
        "kind": "m",
        "expression": "null meta [IsParameterQuery=true, Type=\"Date\", IsParameterQueryRequired=false]",
        "queryGroup": "Parameter",
        "lineageTag": "4ab62782-8dab-4ea5-a5f5-03cdeee39902",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Null"
          }
        ]
      },
      {
        "name": "P_Date",
        "kind": "m",
        "expression": "#date(2023, 3, 31) meta [IsParameterQuery=true, Type=\"Date\", IsParameterQueryRequired=false]",
        "queryGroup": "Parameter",
        "lineageTag": "0501841b-37b6-4692-a695-b78a68ac3616",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Date"
          }
        ]
      },
      {
        "name": "User List1",
        "kind": "m",
        "expression": [
          "let",
          "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"rV3ZUuPIEv2Vin6eUFgla/HbNQbMZuBiGmgm5kHYaiSwpb5e6DZff6tSXjKrRx2h\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [S.No = _t, #\"First Name\" = _t, #\"Last Name\" = _t, Name = _t, #\"Email ID\" = _t, Country = _t, Regional = _t]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"S.No\", Int64.Type}, {\"First Name\", type text}, {\"Last Name\", type text}, {\"Name\", type text}, {\"Email ID\", type text}, {\"Country\", type text}, {\"Regional\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "lineageTag": "c15be32f-43a3-4ac8-a8aa-d9924a7da83e",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "User List2",
        "kind": "m",
        "expression": [
          "let",
          "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"tZptT9tIFIX/SsTnKnIc37Hn24YmhLfQEkMrUlWrtGQXBA27vKzU/vpNBtreY22V\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [S.No = _t, #\"First Name\" = _t, #\"Last Name\" = _t, Name = _t, #\"Email ID\" = _t, Country = _t, Regional = _t]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"S.No\", Int64.Type}, {\"First Name\", type text}, {\"Last Name\", type text}, {\"Name\", type text}, {\"Email ID\", type text}, {\"Country\", type text}, {\"Regional\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "lineageTag": "e17f7d84-d922-4180-8a00-e932dd7e7b22",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "User List3",
        "kind": "m",
        "expression": [
          "let",
          "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"pZxLbxtHEIT/iqGzIXC798G9hVw+RS5N8SVagg9GIsQGFAuIg/z+yNvVTnKtuhiW\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [S.No = _t, #\"First Name\" = _t, #\"Last Name\" = _t, Name = _t, #\"Email ID\" = _t, Country = _t]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"S.No\", type text}, {\"First Name\", type text}, {\"Last Name\", type text}, {\"Name\", type text}, {\"Email ID\", type text}, {\"Country\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "lineageTag": "30a0828b-fc74-4d2e-9b10-b7ceda7a3387",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "User List4",
        "kind": "m",
        "expression": [
          "let",
          "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"rdXNboJAFIbhW5nM2pAO/XVXjFYqDBKxbVrigtRJOoloMkKTejVeS69MaD0HW7ffBsKZ5FkwvEOeSyV7cmg+beXsV7GubPMYlK5e/RsLGi5Phl5xv/xYee+bslmYpM1FLnq59FHkY0LkJYoMnoi8QpHRjMhrFJmNibxBkWFE5C2KnL8QeQcjQyL7KFK/EqkuYB/mkE1YPylvkIIF9MwBKVhBKW+RgiWUvLEJa2jQ7REsorjbI1hFUfc+YRlpzSaso5TPJB/WUdL9M2AdxQGbsI4eJmzCOtJTNmEdDbh3v+0oru32ey/a038006PsOBJ/nrzQuNJsT5SfpV+lLSfbrG3R3Md1ZY1zZkczwRNBI49H597iAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [S.No = _t, #\"First Name\" = _t, #\"Last Name\" = _t, Name = _t, #\"Email ID\" = _t, Country = _t, Region = _t]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"S.No\", Int64.Type}, {\"First Name\", type text}, {\"Last Name\", type text}, {\"Name\", type text}, {\"Email ID\", type text}, {\"Country\", type text}, {\"Region\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "lineageTag": "468e086b-c7f8-4eaf-bd63-bd3282efd1a6",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "User List5",
        "kind": "m",
        "expression": [
          "let",
          "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"pZfdS8JQGIf/Fdm1iDtf07uKPkydSVph4sXIoYJNqKT873Pn/UlEXf3em3HeMR44Zw972HyepEkzOa+Wb+Vn47gabvY/swxFHFrbzf5rU1Srs+V623rZvdaPPSSL5jwxPOHiMhKsgjCKBMcTrvuR4HlCbxAJgSfcyjlkCoKcQ4cn9MeR0OUJg14kpG0F4l4QCiuH54JQaDmUF5oqvMxzQSjEzO8EoTAznwlCoeZItEgVbo6eBaGQc3wjCIWdY7HTKOwcixdGYedENmIUdk6xEYWd0ydBKOx8lA+Oqe2c7apVDZisy2p1mk/D4Ti81+vWdrf+px6BBSAeJqMB2EKHBSAdpssCUA7bZgEIh01pgJyBNSwA2bCWBaAa1tEAaYalTUQxLG0iemFpE1ELS5uIVljaRJTC0SaiE442EZVwtIlohKNNRCEcbSL64GgTUQdHm4g2ONpElMHRJqILrjbxar8qq7IxLQ41OV5/3Srj0PooDn+74NssAF3wKQ2QLXjDAk6/FJYFoAvesQB0wXsagDMILABd8BkLQBd8hwZIFzxtIroQaBPRhUCbiC4E2kR0IdAmoguBNhFdCLSJ6EKgTUQXAm0iuhBoE9GFQJuILmS0iehCRpuILmS0iXUXFt8=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [S.No = _t, #\"First Name\" = _t, #\"Last Name\" = _t, Name = _t, #\"Email ID\" = _t, Country = _t]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"S.No\", Int64.Type}, {\"First Name\", type text}, {\"Last Name\", type text}, {\"Name\", type text}, {\"Email ID\", type text}, {\"Country\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "lineageTag": "3238cb50-2520-4aae-bfab-9d0110b888b8",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      }
    ],
    "queryGroups": [
      {
        "folder": "Parameter",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ]
      },
      {
        "folder": "Customer",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "3"
          }
        ]
      },
      {
        "folder": "Loyalty",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "4"
          }
        ]
      },
      {
        "folder": "B2B/B2C",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "5"
          }
        ]
      },
      {
        "folder": "Static Filter Table",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "6"
          }
        ]
      },
      {
        "folder": "Weight Band",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "9"
          }
        ]
      },
      {
        "folder": "Shipment Band",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "10"
          }
        ]
      },
      {
        "folder": "Static Filter",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "8"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Customer Measures\",\"Loyalty Measures\",\"Working Days\",\"Key Measures\",\"Revenue Filter\",\"Year Sort\",\"FTB Measures\",\"TopCustomerFilter\",\"Dynamic Year\",\"Main KPI Measures\",\"Cus/Rev/Ship/Weight\",\"B2C/B2B\",\"Customer Filters\",\"Portfolia Measure\",\"Shipment Band\",\"Shipment Band Measure\",\"Weight Band Measure\",\"Weight Band Filter\",\"Weight Break Group\",\"Shipment Range\",\"P_Country\",\"Loyalty_Sort\",\"New/Regained\",\"FTB Filter\",\"FTB Customer Summary Filter\",\"Period Filter\",\"ShortMonthMapping\",\"Rev/Ship/Weight Filter\",\"Currency Filter\",\"VW_DIM_CUSTOMER\",\"DIM_SALES_FUNCTION\",\"DIM_WEIGHT_BREAK\",\"DIM_WORK_DAYS_GEO\",\"DIM_GEOGRAPHY_OWNER\",\"DIM_PRODUCT\",\"DIM_PERIOD\",\"FCT_COMMERCIAL_SUMMARY\",\"DIM_ACCOUNT\",\"Cockpit Measure New\",\"Country_P\",\"P_StartDate\",\"P_EndDate\",\"P_Date\",\"Date\",\"Loyality Status\",\"Sorting Product\",\"Sales Function Import\",\"User List1\",\"User List2\",\"User List3\",\"User List4\",\"User List5\",\"User List\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.116.622.0 (23.04)"
      },
      {
        "name": "TabularEditor_SerializeOptions",
        "value": "{\"IgnoreInferredObjects\":true,\"IgnoreInferredProperties\":true,\"IgnoreTimestamps\":true,\"SplitMultilineStrings\":true,\"PrefixFilenames\":false,\"LocalTranslations\":false,\"LocalPerspectives\":false,\"LocalRelationships\":false,\"Levels\":[\"Data Sources\",\"Shared Expressions\",\"Perspectives\",\"Relationships\",\"Roles\",\"Tables\",\"Tables/Columns\",\"Tables/Hierarchies\",\"Tables/Measures\",\"Tables/Partitions\",\"Tables/Calculation Items\",\"Translations\"]}"
      }
    ]
  }
}